# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: whatevr/v2/notifications.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'whatevr/v2/notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from whatevr.v2 import people_pb2 as whatevr_dot_v2_dot_people__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ewhatevr/v2/notifications.proto\x12\nwhatevr.v2\x1a\x17whatevr/v2/people.proto\"\x13\n\x11NotificationsView\"\x8f\x02\n\x0fNotificationRow\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n\x07\x63hat_id\x18\x02 \x01(\tR\x06\x63hatId\x12\x1d\n\nmessage_id\x18\x03 \x01(\tR\tmessageId\x12\x14\n\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n\x04\x62ody\x18\x05 \x01(\tR\x04\x62ody\x12*\n\x06sender\x18\x06 \x01(\x0b\x32\x12.whatevr.v2.PersonR\x06sender\x12\x1f\n\x0b\x61vatar_path\x18\x07 \x01(\tR\navatarPath\x12\x14\n\x05\x63ount\x18\x08 \x01(\rR\x05\x63ount\x12\x11\n\x04t_ms\x18\t \x01(\x03R\x03tMs\x12\x14\n\x05sound\x18\n \x01(\x08R\x05sound\"%\n\x13NotificationDismiss\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02idB\xa7\x01\n\x0e\x63om.whatevr.v2B\x12NotificationsProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\nWhatevr.V2\xca\x02\nWhatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\x0bWhatevr::V2\x92\x03\x02\x08\x02\x62\x08\x65\x64itionsp\xe9\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whatevr.v2.notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.whatevr.v2B\022NotificationsProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\242\002\003WXX\252\002\nWhatevr.V2\312\002\nWhatevr\\V2\342\002\026Whatevr\\V2\\GPBMetadata\352\002\013Whatevr::V2\222\003\002\010\002'
  _globals['_NOTIFICATIONSVIEW']._serialized_start=71
  _globals['_NOTIFICATIONSVIEW']._serialized_end=90
  _globals['_NOTIFICATIONROW']._serialized_start=93
  _globals['_NOTIFICATIONROW']._serialized_end=364
  _globals['_NOTIFICATIONDISMISS']._serialized_start=366
  _globals['_NOTIFICATIONDISMISS']._serialized_end=403
# @@protoc_insertion_point(module_scope)
