# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: whatevr/v2/search.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'whatevr/v2/search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from whatevr.v2 import chats_pb2 as whatevr_dot_v2_dot_chats__pb2
from whatevr.v2 import messages_pb2 as whatevr_dot_v2_dot_messages__pb2
from whatevr.v2 import stickers_pb2 as whatevr_dot_v2_dot_stickers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17whatevr/v2/search.proto\x12\nwhatevr.v2\x1a\x16whatevr/v2/chats.proto\x1a\x19whatevr/v2/messages.proto\x1a\x19whatevr/v2/stickers.proto\"9\n\x0bSearchChats\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n\x05limit\x18\x02 \x01(\rR\x05limit\">\n\x11SearchChatsResult\x12)\n\x05\x63hats\x18\x01 \x03(\x0b\x32\x13.whatevr.v2.ChatRowR\x05\x63hats\"m\n\x0eSearchMessages\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n\x07\x63hat_id\x18\x02 \x01(\tR\x06\x63hatId\x12\x14\n\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n\x06\x62\x65\x66ore\x18\x04 \x01(\tR\x06\x62\x65\x66ore\"^\n\x14SearchMessagesResult\x12\x32\n\x08messages\x18\x01 \x03(\x0b\x32\x16.whatevr.v2.MessageRowR\x08messages\x12\x12\n\x04more\x18\x02 \x01(\x08R\x04more\"<\n\x0eSearchStickers\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n\x05limit\x18\x02 \x01(\rR\x05limit\"J\n\x14SearchStickersResult\x12\x32\n\x08stickers\x18\x01 \x03(\x0b\x32\x16.whatevr.v2.StickerRowR\x08stickers\")\n\x11\x43ontactCheckPhone\x12\x14\n\x05phone\x18\x01 \x01(\tR\x05phone\"\x9c\x01\n\x17\x43ontactCheckPhoneResult\x12\x1e\n\nregistered\x18\x01 \x01(\x08R\nregistered\x12\x14\n\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1b\n\tperson_id\x18\x03 \x01(\tR\x08personId\x12\x12\n\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n\x08\x62usiness\x18\x05 \x01(\x08R\x08\x62usinessB\xa0\x01\n\x0e\x63om.whatevr.v2B\x0bSearchProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\nWhatevr.V2\xca\x02\nWhatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\x0bWhatevr::V2\x92\x03\x02\x08\x02\x62\x08\x65\x64itionsp\xe9\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whatevr.v2.search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.whatevr.v2B\013SearchProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\242\002\003WXX\252\002\nWhatevr.V2\312\002\nWhatevr\\V2\342\002\026Whatevr\\V2\\GPBMetadata\352\002\013Whatevr::V2\222\003\002\010\002'
  _globals['_SEARCHCHATS']._serialized_start=117
  _globals['_SEARCHCHATS']._serialized_end=174
  _globals['_SEARCHCHATSRESULT']._serialized_start=176
  _globals['_SEARCHCHATSRESULT']._serialized_end=238
  _globals['_SEARCHMESSAGES']._serialized_start=240
  _globals['_SEARCHMESSAGES']._serialized_end=349
  _globals['_SEARCHMESSAGESRESULT']._serialized_start=351
  _globals['_SEARCHMESSAGESRESULT']._serialized_end=445
  _globals['_SEARCHSTICKERS']._serialized_start=447
  _globals['_SEARCHSTICKERS']._serialized_end=507
  _globals['_SEARCHSTICKERSRESULT']._serialized_start=509
  _globals['_SEARCHSTICKERSRESULT']._serialized_end=583
  _globals['_CONTACTCHECKPHONE']._serialized_start=585
  _globals['_CONTACTCHECKPHONE']._serialized_end=626
  _globals['_CONTACTCHECKPHONERESULT']._serialized_start=629
  _globals['_CONTACTCHECKPHONERESULT']._serialized_end=785
# @@protoc_insertion_point(module_scope)
