// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/account.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionState int32

const (
	ConnectionState_CONNECTION_STATE_UNSPECIFIED ConnectionState = 0
	ConnectionState_CONNECTION_STATE_STARTING    ConnectionState = 1
	ConnectionState_CONNECTION_STATE_NEED_LOGIN  ConnectionState = 2
	ConnectionState_CONNECTION_STATE_CONNECTING  ConnectionState = 3
	ConnectionState_CONNECTION_STATE_ONLINE      ConnectionState = 4
	// waiting out a backoff before the next attempt
	ConnectionState_CONNECTION_STATE_WAITING ConnectionState = 5
	ConnectionState_CONNECTION_STATE_OFFLINE ConnectionState = 6
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "CONNECTION_STATE_STARTING",
		2: "CONNECTION_STATE_NEED_LOGIN",
		3: "CONNECTION_STATE_CONNECTING",
		4: "CONNECTION_STATE_ONLINE",
		5: "CONNECTION_STATE_WAITING",
		6: "CONNECTION_STATE_OFFLINE",
	}
	ConnectionState_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED": 0,
		"CONNECTION_STATE_STARTING":    1,
		"CONNECTION_STATE_NEED_LOGIN":  2,
		"CONNECTION_STATE_CONNECTING":  3,
		"CONNECTION_STATE_ONLINE":      4,
		"CONNECTION_STATE_WAITING":     5,
		"CONNECTION_STATE_OFFLINE":     6,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_account_proto_enumTypes[0].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_whatevr_v2_account_proto_enumTypes[0]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ConnectionCause int32

const (
	ConnectionCause_CONNECTION_CAUSE_UNSPECIFIED ConnectionCause = 0
	// the dial failed: no route, refused, dns
	ConnectionCause_CONNECTION_CAUSE_UNREACHABLE ConnectionCause = 1
	// a socket that never got to success
	ConnectionCause_CONNECTION_CAUSE_NO_ANSWER ConnectionCause = 2
	// the server said no at login
	ConnectionCause_CONNECTION_CAUSE_REFUSED ConnectionCause = 3
	// a connection that went quiet
	ConnectionCause_CONNECTION_CAUSE_SILENT ConnectionCause = 4
	ConnectionCause_CONNECTION_CAUSE_CLOSED ConnectionCause = 5
)

// Enum value maps for ConnectionCause.
var (
	ConnectionCause_name = map[int32]string{
		0: "CONNECTION_CAUSE_UNSPECIFIED",
		1: "CONNECTION_CAUSE_UNREACHABLE",
		2: "CONNECTION_CAUSE_NO_ANSWER",
		3: "CONNECTION_CAUSE_REFUSED",
		4: "CONNECTION_CAUSE_SILENT",
		5: "CONNECTION_CAUSE_CLOSED",
	}
	ConnectionCause_value = map[string]int32{
		"CONNECTION_CAUSE_UNSPECIFIED": 0,
		"CONNECTION_CAUSE_UNREACHABLE": 1,
		"CONNECTION_CAUSE_NO_ANSWER":   2,
		"CONNECTION_CAUSE_REFUSED":     3,
		"CONNECTION_CAUSE_SILENT":      4,
		"CONNECTION_CAUSE_CLOSED":      5,
	}
)

func (x ConnectionCause) Enum() *ConnectionCause {
	p := new(ConnectionCause)
	*p = x
	return p
}

func (x ConnectionCause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionCause) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_account_proto_enumTypes[1].Descriptor()
}

func (ConnectionCause) Type() protoreflect.EnumType {
	return &file_whatevr_v2_account_proto_enumTypes[1]
}

func (x ConnectionCause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type LoginState int32

const (
	LoginState_LOGIN_STATE_UNSPECIFIED LoginState = 0
	LoginState_LOGIN_STATE_LOGGED_IN   LoginState = 1
	LoginState_LOGIN_STATE_QR          LoginState = 2
	// scanned, the phone and daemon are finishing the pairing
	LoginState_LOGIN_STATE_PAIRING LoginState = 3
	LoginState_LOGIN_STATE_FAILED  LoginState = 4
)

// Enum value maps for LoginState.
var (
	LoginState_name = map[int32]string{
		0: "LOGIN_STATE_UNSPECIFIED",
		1: "LOGIN_STATE_LOGGED_IN",
		2: "LOGIN_STATE_QR",
		3: "LOGIN_STATE_PAIRING",
		4: "LOGIN_STATE_FAILED",
	}
	LoginState_value = map[string]int32{
		"LOGIN_STATE_UNSPECIFIED": 0,
		"LOGIN_STATE_LOGGED_IN":   1,
		"LOGIN_STATE_QR":          2,
		"LOGIN_STATE_PAIRING":     3,
		"LOGIN_STATE_FAILED":      4,
	}
)

func (x LoginState) Enum() *LoginState {
	p := new(LoginState)
	*p = x
	return p
}

func (x LoginState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginState) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_account_proto_enumTypes[2].Descriptor()
}

func (LoginState) Type() protoreflect.EnumType {
	return &file_whatevr_v2_account_proto_enumTypes[2]
}

func (x LoginState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SyncType int32

const (
	SyncType_SYNC_TYPE_UNSPECIFIED SyncType = 0
	SyncType_SYNC_TYPE_INITIAL     SyncType = 1
	SyncType_SYNC_TYPE_RECENT      SyncType = 2
	SyncType_SYNC_TYPE_FULL        SyncType = 3
	SyncType_SYNC_TYPE_ON_DEMAND   SyncType = 4
	SyncType_SYNC_TYPE_PUSH_NAMES  SyncType = 5
)

// Enum value maps for SyncType.
var (
	SyncType_name = map[int32]string{
		0: "SYNC_TYPE_UNSPECIFIED",
		1: "SYNC_TYPE_INITIAL",
		2: "SYNC_TYPE_RECENT",
		3: "SYNC_TYPE_FULL",
		4: "SYNC_TYPE_ON_DEMAND",
		5: "SYNC_TYPE_PUSH_NAMES",
	}
	SyncType_value = map[string]int32{
		"SYNC_TYPE_UNSPECIFIED": 0,
		"SYNC_TYPE_INITIAL":     1,
		"SYNC_TYPE_RECENT":      2,
		"SYNC_TYPE_FULL":        3,
		"SYNC_TYPE_ON_DEMAND":   4,
		"SYNC_TYPE_PUSH_NAMES":  5,
	}
)

func (x SyncType) Enum() *SyncType {
	p := new(SyncType)
	*p = x
	return p
}

func (x SyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_account_proto_enumTypes[3].Descriptor()
}

func (SyncType) Type() protoreflect.EnumType {
	return &file_whatevr_v2_account_proto_enumTypes[3]
}

func (x SyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SyncPhase int32

const (
	SyncPhase_SYNC_PHASE_UNSPECIFIED SyncPhase = 0
	SyncPhase_SYNC_PHASE_IDLE        SyncPhase = 1
	SyncPhase_SYNC_PHASE_RUNNING     SyncPhase = 2
	// the phone stopped sending before it said it was done
	SyncPhase_SYNC_PHASE_STALLED SyncPhase = 3
	SyncPhase_SYNC_PHASE_DONE    SyncPhase = 4
)

// Enum value maps for SyncPhase.
var (
	SyncPhase_name = map[int32]string{
		0: "SYNC_PHASE_UNSPECIFIED",
		1: "SYNC_PHASE_IDLE",
		2: "SYNC_PHASE_RUNNING",
		3: "SYNC_PHASE_STALLED",
		4: "SYNC_PHASE_DONE",
	}
	SyncPhase_value = map[string]int32{
		"SYNC_PHASE_UNSPECIFIED": 0,
		"SYNC_PHASE_IDLE":        1,
		"SYNC_PHASE_RUNNING":     2,
		"SYNC_PHASE_STALLED":     3,
		"SYNC_PHASE_DONE":        4,
	}
)

func (x SyncPhase) Enum() *SyncPhase {
	p := new(SyncPhase)
	*p = x
	return p
}

func (x SyncPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_account_proto_enumTypes[4].Descriptor()
}

func (SyncPhase) Type() protoreflect.EnumType {
	return &file_whatevr_v2_account_proto_enumTypes[4]
}

func (x SyncPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ProblemKind int32

const (
	ProblemKind_PROBLEM_KIND_UNSPECIFIED ProblemKind = 0
	// whatsapp can't be reached
	ProblemKind_PROBLEM_KIND_OFFLINE    ProblemKind = 1
	ProblemKind_PROBLEM_KIND_LOGGED_OUT ProblemKind = 2
	// whatsapp suspended this account for a while
	ProblemKind_PROBLEM_KIND_TEMP_BANNED ProblemKind = 3
	// whatsapp wants a newer client version
	ProblemKind_PROBLEM_KIND_CLIENT_OUTDATED ProblemKind = 4
	// sends are queued and failing
	ProblemKind_PROBLEM_KIND_SEND_FAILING    ProblemKind = 5
	ProblemKind_PROBLEM_KIND_HISTORY_STALLED ProblemKind = 6
	// an app state collection can't be read (missing keys, a bad patch)
	ProblemKind_PROBLEM_KIND_APP_STATE ProblemKind = 7
	// messages waiting on a resend from the sender's phone
	ProblemKind_PROBLEM_KIND_UNDECRYPTED ProblemKind = 8
	// the disk is full or the database can't be written
	ProblemKind_PROBLEM_KIND_STORAGE ProblemKind = 9
	// connected, but whatsapp never said we're logged in
	ProblemKind_PROBLEM_KIND_STUCK_BEFORE_LOGIN ProblemKind = 10
	// whatsapp turned the login down, text says why
	ProblemKind_PROBLEM_KIND_SERVER_REFUSED ProblemKind = 11
	// whatsapp was opened on another computer; reconnecting takes it back
	ProblemKind_PROBLEM_KIND_STREAM_REPLACED ProblemKind = 12
	// the connection went quiet and is being replaced
	ProblemKind_PROBLEM_KIND_KEEPALIVE_LOST ProblemKind = 13
	// downloads keep failing, not just one message's
	ProblemKind_PROBLEM_KIND_MEDIA_FAILING ProblemKind = 14
)

// Enum value maps for ProblemKind.
var (
	ProblemKind_name = map[int32]string{
		0:  "PROBLEM_KIND_UNSPECIFIED",
		1:  "PROBLEM_KIND_OFFLINE",
		2:  "PROBLEM_KIND_LOGGED_OUT",
		3:  "PROBLEM_KIND_TEMP_BANNED",
		4:  "PROBLEM_KIND_CLIENT_OUTDATED",
		5:  "PROBLEM_KIND_SEND_FAILING",
		6:  "PROBLEM_KIND_HISTORY_STALLED",
		7:  "PROBLEM_KIND_APP_STATE",
		8:  "PROBLEM_KIND_UNDECRYPTED",
		9:  "PROBLEM_KIND_STORAGE",
		10: "PROBLEM_KIND_STUCK_BEFORE_LOGIN",
		11: "PROBLEM_KIND_SERVER_REFUSED",
		12: "PROBLEM_KIND_STREAM_REPLACED",
		13: "PROBLEM_KIND_KEEPALIVE_LOST",
		14: "PROBLEM_KIND_MEDIA_FAILING",
	}
	ProblemKind_value = map[string]int32{
		"PROBLEM_KIND_UNSPECIFIED":        0,
		"PROBLEM_KIND_OFFLINE":            1,
		"PROBLEM_KIND_LOGGED_OUT":         2,
		"PROBLEM_KIND_TEMP_BANNED":        3,
		"PROBLEM_KIND_CLIENT_OUTDATED":    4,
		"PROBLEM_KIND_SEND_FAILING":       5,
		"PROBLEM_KIND_HISTORY_STALLED":    6,
		"PROBLEM_KIND_APP_STATE":          7,
		"PROBLEM_KIND_UNDECRYPTED":        8,
		"PROBLEM_KIND_STORAGE":            9,
		"PROBLEM_KIND_STUCK_BEFORE_LOGIN": 10,
		"PROBLEM_KIND_SERVER_REFUSED":     11,
		"PROBLEM_KIND_STREAM_REPLACED":    12,
		"PROBLEM_KIND_KEEPALIVE_LOST":     13,
		"PROBLEM_KIND_MEDIA_FAILING":      14,
	}
)

func (x ProblemKind) Enum() *ProblemKind {
	p := new(ProblemKind)
	*p = x
	return p
}

func (x ProblemKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProblemKind) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_account_proto_enumTypes[5].Descriptor()
}

func (ProblemKind) Type() protoreflect.EnumType {
	return &file_whatevr_v2_account_proto_enumTypes[5]
}

func (x ProblemKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// the daemon's link to whatsapp
type ConnectionView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionView) Reset() {
	*x = ConnectionView{}
	mi := &file_whatevr_v2_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionView) ProtoMessage() {}

func (x *ConnectionView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConnectionView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConnectionView_builder) Build() *ConnectionView {
	m0 := &ConnectionView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConnectionRow struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State           ConnectionState        `protobuf:"varint,1,opt,name=state,enum=whatevr.v2.ConnectionState"`
	xxx_hidden_SinceMs         int64                  `protobuf:"varint,2,opt,name=since_ms,json=sinceMs"`
	xxx_hidden_Detail          string                 `protobuf:"bytes,3,opt,name=detail"`
	xxx_hidden_Cause           ConnectionCause        `protobuf:"varint,4,opt,name=cause,enum=whatevr.v2.ConnectionCause"`
	xxx_hidden_Attempt         uint32                 `protobuf:"varint,5,opt,name=attempt"`
	xxx_hidden_NextRetryMs     int64                  `protobuf:"varint,6,opt,name=next_retry_ms,json=nextRetryMs"`
	xxx_hidden_CanReconnect    bool                   `protobuf:"varint,7,opt,name=can_reconnect,json=canReconnect"`
	xxx_hidden_PendingOutgoing uint32                 `protobuf:"varint,8,opt,name=pending_outgoing,json=pendingOutgoing"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ConnectionRow) Reset() {
	*x = ConnectionRow{}
	mi := &file_whatevr_v2_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRow) ProtoMessage() {}

func (x *ConnectionRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionRow) GetState() ConnectionState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ConnectionState_CONNECTION_STATE_UNSPECIFIED
}

func (x *ConnectionRow) GetSinceMs() int64 {
	if x != nil {
		return x.xxx_hidden_SinceMs
	}
	return 0
}

func (x *ConnectionRow) GetDetail() string {
	if x != nil {
		return x.xxx_hidden_Detail
	}
	return ""
}

func (x *ConnectionRow) GetCause() ConnectionCause {
	if x != nil {
		return x.xxx_hidden_Cause
	}
	return ConnectionCause_CONNECTION_CAUSE_UNSPECIFIED
}

func (x *ConnectionRow) GetAttempt() uint32 {
	if x != nil {
		return x.xxx_hidden_Attempt
	}
	return 0
}

func (x *ConnectionRow) GetNextRetryMs() int64 {
	if x != nil {
		return x.xxx_hidden_NextRetryMs
	}
	return 0
}

func (x *ConnectionRow) GetCanReconnect() bool {
	if x != nil {
		return x.xxx_hidden_CanReconnect
	}
	return false
}

func (x *ConnectionRow) GetPendingOutgoing() uint32 {
	if x != nil {
		return x.xxx_hidden_PendingOutgoing
	}
	return 0
}

func (x *ConnectionRow) SetState(v ConnectionState) {
	x.xxx_hidden_State = v
}

func (x *ConnectionRow) SetSinceMs(v int64) {
	x.xxx_hidden_SinceMs = v
}

func (x *ConnectionRow) SetDetail(v string) {
	x.xxx_hidden_Detail = v
}

func (x *ConnectionRow) SetCause(v ConnectionCause) {
	x.xxx_hidden_Cause = v
}

func (x *ConnectionRow) SetAttempt(v uint32) {
	x.xxx_hidden_Attempt = v
}

func (x *ConnectionRow) SetNextRetryMs(v int64) {
	x.xxx_hidden_NextRetryMs = v
}

func (x *ConnectionRow) SetCanReconnect(v bool) {
	x.xxx_hidden_CanReconnect = v
}

func (x *ConnectionRow) SetPendingOutgoing(v uint32) {
	x.xxx_hidden_PendingOutgoing = v
}

type ConnectionRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	State   ConnectionState
	SinceMs int64
	// a finished sentence for a status bar
	Detail string
	// how the last attempt or connection ended, while connecting or waiting
	Cause       ConnectionCause
	Attempt     uint32
	NextRetryMs int64
	// daemon_reconnect would do something now
	CanReconnect    bool
	PendingOutgoing uint32
}

func (b0 ConnectionRow_builder) Build() *ConnectionRow {
	m0 := &ConnectionRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	x.xxx_hidden_SinceMs = b.SinceMs
	x.xxx_hidden_Detail = b.Detail
	x.xxx_hidden_Cause = b.Cause
	x.xxx_hidden_Attempt = b.Attempt
	x.xxx_hidden_NextRetryMs = b.NextRetryMs
	x.xxx_hidden_CanReconnect = b.CanReconnect
	x.xxx_hidden_PendingOutgoing = b.PendingOutgoing
	return m0
}

// subscribing starts the qr pairing flow when logged out, or joins it
type LoginView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginView) Reset() {
	*x = LoginView{}
	mi := &file_whatevr_v2_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginView) ProtoMessage() {}

func (x *LoginView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LoginView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LoginView_builder) Build() *LoginView {
	m0 := &LoginView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LoginRow struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State       LoginState             `protobuf:"varint,1,opt,name=state,enum=whatevr.v2.LoginState"`
	xxx_hidden_Detail      string                 `protobuf:"bytes,2,opt,name=detail"`
	xxx_hidden_Qr          string                 `protobuf:"bytes,3,opt,name=qr"`
	xxx_hidden_QrExpiresMs int64                  `protobuf:"varint,4,opt,name=qr_expires_ms,json=qrExpiresMs"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRow) Reset() {
	*x = LoginRow{}
	mi := &file_whatevr_v2_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRow) ProtoMessage() {}

func (x *LoginRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRow) GetState() LoginState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return LoginState_LOGIN_STATE_UNSPECIFIED
}

func (x *LoginRow) GetDetail() string {
	if x != nil {
		return x.xxx_hidden_Detail
	}
	return ""
}

func (x *LoginRow) GetQr() string {
	if x != nil {
		return x.xxx_hidden_Qr
	}
	return ""
}

func (x *LoginRow) GetQrExpiresMs() int64 {
	if x != nil {
		return x.xxx_hidden_QrExpiresMs
	}
	return 0
}

func (x *LoginRow) SetState(v LoginState) {
	x.xxx_hidden_State = v
}

func (x *LoginRow) SetDetail(v string) {
	x.xxx_hidden_Detail = v
}

func (x *LoginRow) SetQr(v string) {
	x.xxx_hidden_Qr = v
}

func (x *LoginRow) SetQrExpiresMs(v int64) {
	x.xxx_hidden_QrExpiresMs = v
}

type LoginRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	State  LoginState
	Detail string
	// the code to draw, empty outside LOGIN_STATE_QR
	Qr          string
	QrExpiresMs int64
}

func (b0 LoginRow_builder) Build() *LoginRow {
	m0 := &LoginRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Detail = b.Detail
	x.xxx_hidden_Qr = b.Qr
	x.xxx_hidden_QrExpiresMs = b.QrExpiresMs
	return m0
}

// history sync progress
type SyncView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncView) Reset() {
	*x = SyncView{}
	mi := &file_whatevr_v2_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncView) ProtoMessage() {}

func (x *SyncView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SyncView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SyncView_builder) Build() *SyncView {
	m0 := &SyncView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SyncRow struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type          SyncType               `protobuf:"varint,1,opt,name=type,enum=whatevr.v2.SyncType"`
	xxx_hidden_Phase         SyncPhase              `protobuf:"varint,2,opt,name=phase,enum=whatevr.v2.SyncPhase"`
	xxx_hidden_Percent       uint32                 `protobuf:"varint,3,opt,name=percent"`
	xxx_hidden_Chunk         uint32                 `protobuf:"varint,4,opt,name=chunk"`
	xxx_hidden_ChunkChats    uint32                 `protobuf:"varint,5,opt,name=chunk_chats,json=chunkChats"`
	xxx_hidden_ChunkMessages uint32                 `protobuf:"varint,6,opt,name=chunk_messages,json=chunkMessages"`
	xxx_hidden_DoneChats     uint32                 `protobuf:"varint,7,opt,name=done_chats,json=doneChats"`
	xxx_hidden_DoneMessages  uint32                 `protobuf:"varint,8,opt,name=done_messages,json=doneMessages"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SyncRow) Reset() {
	*x = SyncRow{}
	mi := &file_whatevr_v2_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRow) ProtoMessage() {}

func (x *SyncRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncRow) GetType() SyncType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return SyncType_SYNC_TYPE_UNSPECIFIED
}

func (x *SyncRow) GetPhase() SyncPhase {
	if x != nil {
		return x.xxx_hidden_Phase
	}
	return SyncPhase_SYNC_PHASE_UNSPECIFIED
}

func (x *SyncRow) GetPercent() uint32 {
	if x != nil {
		return x.xxx_hidden_Percent
	}
	return 0
}

func (x *SyncRow) GetChunk() uint32 {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return 0
}

func (x *SyncRow) GetChunkChats() uint32 {
	if x != nil {
		return x.xxx_hidden_ChunkChats
	}
	return 0
}

func (x *SyncRow) GetChunkMessages() uint32 {
	if x != nil {
		return x.xxx_hidden_ChunkMessages
	}
	return 0
}

func (x *SyncRow) GetDoneChats() uint32 {
	if x != nil {
		return x.xxx_hidden_DoneChats
	}
	return 0
}

func (x *SyncRow) GetDoneMessages() uint32 {
	if x != nil {
		return x.xxx_hidden_DoneMessages
	}
	return 0
}

func (x *SyncRow) SetType(v SyncType) {
	x.xxx_hidden_Type = v
}

func (x *SyncRow) SetPhase(v SyncPhase) {
	x.xxx_hidden_Phase = v
}

func (x *SyncRow) SetPercent(v uint32) {
	x.xxx_hidden_Percent = v
}

func (x *SyncRow) SetChunk(v uint32) {
	x.xxx_hidden_Chunk = v
}

func (x *SyncRow) SetChunkChats(v uint32) {
	x.xxx_hidden_ChunkChats = v
}

func (x *SyncRow) SetChunkMessages(v uint32) {
	x.xxx_hidden_ChunkMessages = v
}

func (x *SyncRow) SetDoneChats(v uint32) {
	x.xxx_hidden_DoneChats = v
}

func (x *SyncRow) SetDoneMessages(v uint32) {
	x.xxx_hidden_DoneMessages = v
}

type SyncRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type          SyncType
	Phase         SyncPhase
	Percent       uint32
	Chunk         uint32
	ChunkChats    uint32
	ChunkMessages uint32
	DoneChats     uint32
	DoneMessages  uint32
}

func (b0 SyncRow_builder) Build() *SyncRow {
	m0 := &SyncRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Phase = b.Phase
	x.xxx_hidden_Percent = b.Percent
	x.xxx_hidden_Chunk = b.Chunk
	x.xxx_hidden_ChunkChats = b.ChunkChats
	x.xxx_hidden_ChunkMessages = b.ChunkMessages
	x.xxx_hidden_DoneChats = b.DoneChats
	x.xxx_hidden_DoneMessages = b.DoneMessages
	return m0
}

// one item per live problem, most severe first
type ProblemsView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemsView) Reset() {
	*x = ProblemsView{}
	mi := &file_whatevr_v2_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemsView) ProtoMessage() {}

func (x *ProblemsView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ProblemsView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ProblemsView_builder) Build() *ProblemsView {
	m0 := &ProblemsView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ProblemRow struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind        ProblemKind            `protobuf:"varint,1,opt,name=kind,enum=whatevr.v2.ProblemKind"`
	xxx_hidden_SinceMs     int64                  `protobuf:"varint,2,opt,name=since_ms,json=sinceMs"`
	xxx_hidden_NextRetryMs int64                  `protobuf:"varint,3,opt,name=next_retry_ms,json=nextRetryMs"`
	xxx_hidden_Text        string                 `protobuf:"bytes,4,opt,name=text"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProblemRow) Reset() {
	*x = ProblemRow{}
	mi := &file_whatevr_v2_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemRow) ProtoMessage() {}

func (x *ProblemRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProblemRow) GetKind() ProblemKind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ProblemKind_PROBLEM_KIND_UNSPECIFIED
}

func (x *ProblemRow) GetSinceMs() int64 {
	if x != nil {
		return x.xxx_hidden_SinceMs
	}
	return 0
}

func (x *ProblemRow) GetNextRetryMs() int64 {
	if x != nil {
		return x.xxx_hidden_NextRetryMs
	}
	return 0
}

func (x *ProblemRow) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *ProblemRow) SetKind(v ProblemKind) {
	x.xxx_hidden_Kind = v
}

func (x *ProblemRow) SetSinceMs(v int64) {
	x.xxx_hidden_SinceMs = v
}

func (x *ProblemRow) SetNextRetryMs(v int64) {
	x.xxx_hidden_NextRetryMs = v
}

func (x *ProblemRow) SetText(v string) {
	x.xxx_hidden_Text = v
}

type ProblemRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Kind    ProblemKind
	SinceMs int64
	// when the daemon tries again by itself, 0 for never
	NextRetryMs int64
	// a finished sentence for humans
	Text string
}

func (b0 ProblemRow_builder) Build() *ProblemRow {
	m0 := &ProblemRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_SinceMs = b.SinceMs
	x.xxx_hidden_NextRetryMs = b.NextRetryMs
	x.xxx_hidden_Text = b.Text
	return m0
}

// what this frontend is doing, for notifications and routing
type SessionUpdate struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Focused            bool                   `protobuf:"varint,1,opt,name=focused"`
	xxx_hidden_ActiveChatId       string                 `protobuf:"bytes,2,opt,name=active_chat_id,json=activeChatId"`
	xxx_hidden_ShowsNotifications bool                   `protobuf:"varint,3,opt,name=shows_notifications,json=showsNotifications"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SessionUpdate) Reset() {
	*x = SessionUpdate{}
	mi := &file_whatevr_v2_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUpdate) ProtoMessage() {}

func (x *SessionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SessionUpdate) GetFocused() bool {
	if x != nil {
		return x.xxx_hidden_Focused
	}
	return false
}

func (x *SessionUpdate) GetActiveChatId() string {
	if x != nil {
		return x.xxx_hidden_ActiveChatId
	}
	return ""
}

func (x *SessionUpdate) GetShowsNotifications() bool {
	if x != nil {
		return x.xxx_hidden_ShowsNotifications
	}
	return false
}

func (x *SessionUpdate) SetFocused(v bool) {
	x.xxx_hidden_Focused = v
}

func (x *SessionUpdate) SetActiveChatId(v string) {
	x.xxx_hidden_ActiveChatId = v
}

func (x *SessionUpdate) SetShowsNotifications(v bool) {
	x.xxx_hidden_ShowsNotifications = v
}

type SessionUpdate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Focused      bool
	ActiveChatId string
	// this frontend shows notifications itself; the daemon's own notifier
	// stays quiet while any connected session says so
	ShowsNotifications bool
}

func (b0 SessionUpdate_builder) Build() *SessionUpdate {
	m0 := &SessionUpdate{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Focused = b.Focused
	x.xxx_hidden_ActiveChatId = b.ActiveChatId
	x.xxx_hidden_ShowsNotifications = b.ShowsNotifications
	return m0
}

type DaemonReconnect struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonReconnect) Reset() {
	*x = DaemonReconnect{}
	mi := &file_whatevr_v2_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonReconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonReconnect) ProtoMessage() {}

func (x *DaemonReconnect) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DaemonReconnect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DaemonReconnect_builder) Build() *DaemonReconnect {
	m0 := &DaemonReconnect{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AccountLogout struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLogout) Reset() {
	*x = AccountLogout{}
	mi := &file_whatevr_v2_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLogout) ProtoMessage() {}

func (x *AccountLogout) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AccountLogout_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AccountLogout_builder) Build() *AccountLogout {
	m0 := &AccountLogout{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// a frontend's own diagnostics, landing in the run log the logs view tails
type LogMessage struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message string                 `protobuf:"bytes,1,opt,name=message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_whatevr_v2_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *LogMessage) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type LogMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message string
}

func (b0 LogMessage_builder) Build() *LogMessage {
	m0 := &LogMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	return m0
}

// the daemon's own run log, newest first; a debug page, not history
type LogsView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsView) Reset() {
	*x = LogsView{}
	mi := &file_whatevr_v2_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsView) ProtoMessage() {}

func (x *LogsView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogsView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogsView_builder) Build() *LogsView {
	m0 := &LogsView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// one log line: the byte offset is the stable id, the timestamp is when it
// was written, the level is the zerolog level name
type LogRow struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id    string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_TMs   int64                  `protobuf:"varint,2,opt,name=t_ms,json=tMs"`
	xxx_hidden_Level string                 `protobuf:"bytes,3,opt,name=level"`
	xxx_hidden_Text  string                 `protobuf:"bytes,4,opt,name=text"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogRow) Reset() {
	*x = LogRow{}
	mi := &file_whatevr_v2_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRow) ProtoMessage() {}

func (x *LogRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogRow) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *LogRow) GetTMs() int64 {
	if x != nil {
		return x.xxx_hidden_TMs
	}
	return 0
}

func (x *LogRow) GetLevel() string {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return ""
}

func (x *LogRow) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *LogRow) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *LogRow) SetTMs(v int64) {
	x.xxx_hidden_TMs = v
}

func (x *LogRow) SetLevel(v string) {
	x.xxx_hidden_Level = v
}

func (x *LogRow) SetText(v string) {
	x.xxx_hidden_Text = v
}

type LogRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    string
	TMs   int64
	Level string
	Text  string
}

func (b0 LogRow_builder) Build() *LogRow {
	m0 := &LogRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_TMs = b.TMs
	x.xxx_hidden_Level = b.Level
	x.xxx_hidden_Text = b.Text
	return m0
}

var File_whatevr_v2_account_proto protoreflect.FileDescriptor

const file_whatevr_v2_account_proto_rawDesc = "" +
	"\n" +
	"\x18whatevr/v2/account.proto\x12\n" +
	"whatevr.v2\"\x10\n" +
	"\x0eConnectionView\"\xb6\x02\n" +
	"\rConnectionRow\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.whatevr.v2.ConnectionStateR\x05state\x12\x19\n" +
	"\bsince_ms\x18\x02 \x01(\x03R\asinceMs\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x121\n" +
	"\x05cause\x18\x04 \x01(\x0e2\x1b.whatevr.v2.ConnectionCauseR\x05cause\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\rR\aattempt\x12\"\n" +
	"\rnext_retry_ms\x18\x06 \x01(\x03R\vnextRetryMs\x12#\n" +
	"\rcan_reconnect\x18\a \x01(\bR\fcanReconnect\x12)\n" +
	"\x10pending_outgoing\x18\b \x01(\rR\x0fpendingOutgoing\"\v\n" +
	"\tLoginView\"\x84\x01\n" +
	"\bLoginRow\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.whatevr.v2.LoginStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x0e\n" +
	"\x02qr\x18\x03 \x01(\tR\x02qr\x12\"\n" +
	"\rqr_expires_ms\x18\x04 \x01(\x03R\vqrExpiresMs\"\n" +
	"\n" +
	"\bSyncView\"\x9c\x02\n" +
	"\aSyncRow\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.whatevr.v2.SyncTypeR\x04type\x12+\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x15.whatevr.v2.SyncPhaseR\x05phase\x12\x18\n" +
	"\apercent\x18\x03 \x01(\rR\apercent\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\rR\x05chunk\x12\x1f\n" +
	"\vchunk_chats\x18\x05 \x01(\rR\n" +
	"chunkChats\x12%\n" +
	"\x0echunk_messages\x18\x06 \x01(\rR\rchunkMessages\x12\x1d\n" +
	"\n" +
	"done_chats\x18\a \x01(\rR\tdoneChats\x12#\n" +
	"\rdone_messages\x18\b \x01(\rR\fdoneMessages\"\x0e\n" +
	"\fProblemsView\"\x8c\x01\n" +
	"\n" +
	"ProblemRow\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.whatevr.v2.ProblemKindR\x04kind\x12\x19\n" +
	"\bsince_ms\x18\x02 \x01(\x03R\asinceMs\x12\"\n" +
	"\rnext_retry_ms\x18\x03 \x01(\x03R\vnextRetryMs\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\x80\x01\n" +
	"\rSessionUpdate\x12\x18\n" +
	"\afocused\x18\x01 \x01(\bR\afocused\x12$\n" +
	"\x0eactive_chat_id\x18\x02 \x01(\tR\factiveChatId\x12/\n" +
	"\x13shows_notifications\x18\x03 \x01(\bR\x12showsNotifications\"\x11\n" +
	"\x0fDaemonReconnect\"\x0f\n" +
	"\rAccountLogout\"&\n" +
	"\n" +
	"LogMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\n" +
	"\n" +
	"\bLogsView\"U\n" +
	"\x06LogRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x11\n" +
	"\x04t_ms\x18\x02 \x01(\x03R\x03tMs\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text*\xed\x01\n" +
	"\x0fConnectionState\x12 \n" +
	"\x1cCONNECTION_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CONNECTION_STATE_STARTING\x10\x01\x12\x1f\n" +
	"\x1bCONNECTION_STATE_NEED_LOGIN\x10\x02\x12\x1f\n" +
	"\x1bCONNECTION_STATE_CONNECTING\x10\x03\x12\x1b\n" +
	"\x17CONNECTION_STATE_ONLINE\x10\x04\x12\x1c\n" +
	"\x18CONNECTION_STATE_WAITING\x10\x05\x12\x1c\n" +
	"\x18CONNECTION_STATE_OFFLINE\x10\x06*\xcd\x01\n" +
	"\x0fConnectionCause\x12 \n" +
	"\x1cCONNECTION_CAUSE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONNECTION_CAUSE_UNREACHABLE\x10\x01\x12\x1e\n" +
	"\x1aCONNECTION_CAUSE_NO_ANSWER\x10\x02\x12\x1c\n" +
	"\x18CONNECTION_CAUSE_REFUSED\x10\x03\x12\x1b\n" +
	"\x17CONNECTION_CAUSE_SILENT\x10\x04\x12\x1b\n" +
	"\x17CONNECTION_CAUSE_CLOSED\x10\x05*\x89\x01\n" +
	"\n" +
	"LoginState\x12\x1b\n" +
	"\x17LOGIN_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LOGIN_STATE_LOGGED_IN\x10\x01\x12\x12\n" +
	"\x0eLOGIN_STATE_QR\x10\x02\x12\x17\n" +
	"\x13LOGIN_STATE_PAIRING\x10\x03\x12\x16\n" +
	"\x12LOGIN_STATE_FAILED\x10\x04*\x99\x01\n" +
	"\bSyncType\x12\x19\n" +
	"\x15SYNC_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SYNC_TYPE_INITIAL\x10\x01\x12\x14\n" +
	"\x10SYNC_TYPE_RECENT\x10\x02\x12\x12\n" +
	"\x0eSYNC_TYPE_FULL\x10\x03\x12\x17\n" +
	"\x13SYNC_TYPE_ON_DEMAND\x10\x04\x12\x18\n" +
	"\x14SYNC_TYPE_PUSH_NAMES\x10\x05*\x81\x01\n" +
	"\tSyncPhase\x12\x1a\n" +
	"\x16SYNC_PHASE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSYNC_PHASE_IDLE\x10\x01\x12\x16\n" +
	"\x12SYNC_PHASE_RUNNING\x10\x02\x12\x16\n" +
	"\x12SYNC_PHASE_STALLED\x10\x03\x12\x13\n" +
	"\x0fSYNC_PHASE_DONE\x10\x04*\xe0\x03\n" +
	"\vProblemKind\x12\x1c\n" +
	"\x18PROBLEM_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROBLEM_KIND_OFFLINE\x10\x01\x12\x1b\n" +
	"\x17PROBLEM_KIND_LOGGED_OUT\x10\x02\x12\x1c\n" +
	"\x18PROBLEM_KIND_TEMP_BANNED\x10\x03\x12 \n" +
	"\x1cPROBLEM_KIND_CLIENT_OUTDATED\x10\x04\x12\x1d\n" +
	"\x19PROBLEM_KIND_SEND_FAILING\x10\x05\x12 \n" +
	"\x1cPROBLEM_KIND_HISTORY_STALLED\x10\x06\x12\x1a\n" +
	"\x16PROBLEM_KIND_APP_STATE\x10\a\x12\x1c\n" +
	"\x18PROBLEM_KIND_UNDECRYPTED\x10\b\x12\x18\n" +
	"\x14PROBLEM_KIND_STORAGE\x10\t\x12#\n" +
	"\x1fPROBLEM_KIND_STUCK_BEFORE_LOGIN\x10\n" +
	"\x12\x1f\n" +
	"\x1bPROBLEM_KIND_SERVER_REFUSED\x10\v\x12 \n" +
	"\x1cPROBLEM_KIND_STREAM_REPLACED\x10\f\x12\x1f\n" +
	"\x1bPROBLEM_KIND_KEEPALIVE_LOST\x10\r\x12\x1e\n" +
	"\x1aPROBLEM_KIND_MEDIA_FAILING\x10\x0eB\xa1\x01\n" +
	"\x0ecom.whatevr.v2B\fAccountProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_account_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_whatevr_v2_account_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_whatevr_v2_account_proto_goTypes = []any{
	(ConnectionState)(0),    // 0: whatevr.v2.ConnectionState
	(ConnectionCause)(0),    // 1: whatevr.v2.ConnectionCause
	(LoginState)(0),         // 2: whatevr.v2.LoginState
	(SyncType)(0),           // 3: whatevr.v2.SyncType
	(SyncPhase)(0),          // 4: whatevr.v2.SyncPhase
	(ProblemKind)(0),        // 5: whatevr.v2.ProblemKind
	(*ConnectionView)(nil),  // 6: whatevr.v2.ConnectionView
	(*ConnectionRow)(nil),   // 7: whatevr.v2.ConnectionRow
	(*LoginView)(nil),       // 8: whatevr.v2.LoginView
	(*LoginRow)(nil),        // 9: whatevr.v2.LoginRow
	(*SyncView)(nil),        // 10: whatevr.v2.SyncView
	(*SyncRow)(nil),         // 11: whatevr.v2.SyncRow
	(*ProblemsView)(nil),    // 12: whatevr.v2.ProblemsView
	(*ProblemRow)(nil),      // 13: whatevr.v2.ProblemRow
	(*SessionUpdate)(nil),   // 14: whatevr.v2.SessionUpdate
	(*DaemonReconnect)(nil), // 15: whatevr.v2.DaemonReconnect
	(*AccountLogout)(nil),   // 16: whatevr.v2.AccountLogout
	(*LogMessage)(nil),      // 17: whatevr.v2.LogMessage
	(*LogsView)(nil),        // 18: whatevr.v2.LogsView
	(*LogRow)(nil),          // 19: whatevr.v2.LogRow
}
var file_whatevr_v2_account_proto_depIdxs = []int32{
	0, // 0: whatevr.v2.ConnectionRow.state:type_name -> whatevr.v2.ConnectionState
	1, // 1: whatevr.v2.ConnectionRow.cause:type_name -> whatevr.v2.ConnectionCause
	2, // 2: whatevr.v2.LoginRow.state:type_name -> whatevr.v2.LoginState
	3, // 3: whatevr.v2.SyncRow.type:type_name -> whatevr.v2.SyncType
	4, // 4: whatevr.v2.SyncRow.phase:type_name -> whatevr.v2.SyncPhase
	5, // 5: whatevr.v2.ProblemRow.kind:type_name -> whatevr.v2.ProblemKind
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_whatevr_v2_account_proto_init() }
func file_whatevr_v2_account_proto_init() {
	if File_whatevr_v2_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_account_proto_rawDesc), len(file_whatevr_v2_account_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_account_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_account_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_account_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_account_proto_msgTypes,
	}.Build()
	File_whatevr_v2_account_proto = out.File
	file_whatevr_v2_account_proto_goTypes = nil
	file_whatevr_v2_account_proto_depIdxs = nil
}
