// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/chats.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatFilter int32

const (
	ChatFilter_CHAT_FILTER_UNSPECIFIED ChatFilter = 0
	ChatFilter_CHAT_FILTER_ALL         ChatFilter = 1
	ChatFilter_CHAT_FILTER_DIRECT      ChatFilter = 2
	ChatFilter_CHAT_FILTER_GROUPS      ChatFilter = 3
)

// Enum value maps for ChatFilter.
var (
	ChatFilter_name = map[int32]string{
		0: "CHAT_FILTER_UNSPECIFIED",
		1: "CHAT_FILTER_ALL",
		2: "CHAT_FILTER_DIRECT",
		3: "CHAT_FILTER_GROUPS",
	}
	ChatFilter_value = map[string]int32{
		"CHAT_FILTER_UNSPECIFIED": 0,
		"CHAT_FILTER_ALL":         1,
		"CHAT_FILTER_DIRECT":      2,
		"CHAT_FILTER_GROUPS":      3,
	}
)

func (x ChatFilter) Enum() *ChatFilter {
	p := new(ChatFilter)
	*p = x
	return p
}

func (x ChatFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_chats_proto_enumTypes[0].Descriptor()
}

func (ChatFilter) Type() protoreflect.EnumType {
	return &file_whatevr_v2_chats_proto_enumTypes[0]
}

func (x ChatFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ChatType int32

const (
	ChatType_CHAT_TYPE_UNSPECIFIED ChatType = 0
	ChatType_CHAT_TYPE_DIRECT      ChatType = 1
	ChatType_CHAT_TYPE_GROUP       ChatType = 2
	ChatType_CHAT_TYPE_COMMUNITY   ChatType = 3
	ChatType_CHAT_TYPE_NEWSLETTER  ChatType = 4
	ChatType_CHAT_TYPE_BROADCAST   ChatType = 5
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "CHAT_TYPE_UNSPECIFIED",
		1: "CHAT_TYPE_DIRECT",
		2: "CHAT_TYPE_GROUP",
		3: "CHAT_TYPE_COMMUNITY",
		4: "CHAT_TYPE_NEWSLETTER",
		5: "CHAT_TYPE_BROADCAST",
	}
	ChatType_value = map[string]int32{
		"CHAT_TYPE_UNSPECIFIED": 0,
		"CHAT_TYPE_DIRECT":      1,
		"CHAT_TYPE_GROUP":       2,
		"CHAT_TYPE_COMMUNITY":   3,
		"CHAT_TYPE_NEWSLETTER":  4,
		"CHAT_TYPE_BROADCAST":   5,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_chats_proto_enumTypes[1].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_whatevr_v2_chats_proto_enumTypes[1]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ChatsView struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filter   ChatFilter             `protobuf:"varint,1,opt,name=filter,enum=whatevr.v2.ChatFilter"`
	xxx_hidden_Archived bool                   `protobuf:"varint,2,opt,name=archived"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatsView) Reset() {
	*x = ChatsView{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatsView) ProtoMessage() {}

func (x *ChatsView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatsView) GetFilter() ChatFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return ChatFilter_CHAT_FILTER_UNSPECIFIED
}

func (x *ChatsView) GetArchived() bool {
	if x != nil {
		return x.xxx_hidden_Archived
	}
	return false
}

func (x *ChatsView) SetFilter(v ChatFilter) {
	x.xxx_hidden_Filter = v
}

func (x *ChatsView) SetArchived(v bool) {
	x.xxx_hidden_Archived = v
}

type ChatsView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filter   ChatFilter
	Archived bool
}

func (b0 ChatsView_builder) Build() *ChatsView {
	m0 := &ChatsView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filter = b.Filter
	x.xxx_hidden_Archived = b.Archived
	return m0
}

// the same row chats sends, outside any filter or window
type ChatView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatView) Reset() {
	*x = ChatView{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatView) ProtoMessage() {}

func (x *ChatView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatView) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *ChatView) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type ChatView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 ChatView_builder) Build() *ChatView {
	m0 := &ChatView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type ChatRow struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name             string                 `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Type             ChatType               `protobuf:"varint,3,opt,name=type,enum=whatevr.v2.ChatType"`
	xxx_hidden_AvatarPath       string                 `protobuf:"bytes,4,opt,name=avatar_path,json=avatarPath"`
	xxx_hidden_Preview          *ChatPreview           `protobuf:"bytes,5,opt,name=preview"`
	xxx_hidden_LastMs           int64                  `protobuf:"varint,6,opt,name=last_ms,json=lastMs"`
	xxx_hidden_Unread           uint32                 `protobuf:"varint,7,opt,name=unread"`
	xxx_hidden_MarkedUnread     bool                   `protobuf:"varint,8,opt,name=marked_unread,json=markedUnread"`
	xxx_hidden_Pinned           bool                   `protobuf:"varint,9,opt,name=pinned"`
	xxx_hidden_Archived         bool                   `protobuf:"varint,10,opt,name=archived"`
	xxx_hidden_Muted            bool                   `protobuf:"varint,11,opt,name=muted"`
	xxx_hidden_MuteEndMs        int64                  `protobuf:"varint,12,opt,name=mute_end_ms,json=muteEndMs"`
	xxx_hidden_HistoryExhausted bool                   `protobuf:"varint,13,opt,name=history_exhausted,json=historyExhausted"`
	xxx_hidden_EphemeralSecs    uint32                 `protobuf:"varint,14,opt,name=ephemeral_secs,json=ephemeralSecs"`
	xxx_hidden_ReadOnly         bool                   `protobuf:"varint,15,opt,name=read_only,json=readOnly"`
	xxx_hidden_LoadingOlder     bool                   `protobuf:"varint,16,opt,name=loading_older,json=loadingOlder"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ChatRow) Reset() {
	*x = ChatRow{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRow) ProtoMessage() {}

func (x *ChatRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatRow) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ChatRow) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ChatRow) GetType() ChatType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ChatType_CHAT_TYPE_UNSPECIFIED
}

func (x *ChatRow) GetAvatarPath() string {
	if x != nil {
		return x.xxx_hidden_AvatarPath
	}
	return ""
}

func (x *ChatRow) GetPreview() *ChatPreview {
	if x != nil {
		return x.xxx_hidden_Preview
	}
	return nil
}

func (x *ChatRow) GetLastMs() int64 {
	if x != nil {
		return x.xxx_hidden_LastMs
	}
	return 0
}

func (x *ChatRow) GetUnread() uint32 {
	if x != nil {
		return x.xxx_hidden_Unread
	}
	return 0
}

func (x *ChatRow) GetMarkedUnread() bool {
	if x != nil {
		return x.xxx_hidden_MarkedUnread
	}
	return false
}

func (x *ChatRow) GetPinned() bool {
	if x != nil {
		return x.xxx_hidden_Pinned
	}
	return false
}

func (x *ChatRow) GetArchived() bool {
	if x != nil {
		return x.xxx_hidden_Archived
	}
	return false
}

func (x *ChatRow) GetMuted() bool {
	if x != nil {
		return x.xxx_hidden_Muted
	}
	return false
}

func (x *ChatRow) GetMuteEndMs() int64 {
	if x != nil {
		return x.xxx_hidden_MuteEndMs
	}
	return 0
}

func (x *ChatRow) GetHistoryExhausted() bool {
	if x != nil {
		return x.xxx_hidden_HistoryExhausted
	}
	return false
}

func (x *ChatRow) GetEphemeralSecs() uint32 {
	if x != nil {
		return x.xxx_hidden_EphemeralSecs
	}
	return 0
}

func (x *ChatRow) GetReadOnly() bool {
	if x != nil {
		return x.xxx_hidden_ReadOnly
	}
	return false
}

func (x *ChatRow) GetLoadingOlder() bool {
	if x != nil {
		return x.xxx_hidden_LoadingOlder
	}
	return false
}

func (x *ChatRow) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ChatRow) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ChatRow) SetType(v ChatType) {
	x.xxx_hidden_Type = v
}

func (x *ChatRow) SetAvatarPath(v string) {
	x.xxx_hidden_AvatarPath = v
}

func (x *ChatRow) SetPreview(v *ChatPreview) {
	x.xxx_hidden_Preview = v
}

func (x *ChatRow) SetLastMs(v int64) {
	x.xxx_hidden_LastMs = v
}

func (x *ChatRow) SetUnread(v uint32) {
	x.xxx_hidden_Unread = v
}

func (x *ChatRow) SetMarkedUnread(v bool) {
	x.xxx_hidden_MarkedUnread = v
}

func (x *ChatRow) SetPinned(v bool) {
	x.xxx_hidden_Pinned = v
}

func (x *ChatRow) SetArchived(v bool) {
	x.xxx_hidden_Archived = v
}

func (x *ChatRow) SetMuted(v bool) {
	x.xxx_hidden_Muted = v
}

func (x *ChatRow) SetMuteEndMs(v int64) {
	x.xxx_hidden_MuteEndMs = v
}

func (x *ChatRow) SetHistoryExhausted(v bool) {
	x.xxx_hidden_HistoryExhausted = v
}

func (x *ChatRow) SetEphemeralSecs(v uint32) {
	x.xxx_hidden_EphemeralSecs = v
}

func (x *ChatRow) SetReadOnly(v bool) {
	x.xxx_hidden_ReadOnly = v
}

func (x *ChatRow) SetLoadingOlder(v bool) {
	x.xxx_hidden_LoadingOlder = v
}

func (x *ChatRow) HasPreview() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Preview != nil
}

func (x *ChatRow) ClearPreview() {
	x.xxx_hidden_Preview = nil
}

type ChatRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         string
	Name       string
	Type       ChatType
	AvatarPath string
	// the newest message as the list shows it
	Preview *ChatPreview
	LastMs  int64
	Unread  uint32
	// the phone's mark as unread, no count behind it
	MarkedUnread bool
	Pinned       bool
	Archived     bool
	Muted        bool
	// 0 with muted set is forever
	MuteEndMs int64
	// the phone has nothing older to give
	HistoryExhausted bool
	// the disappearing message timer, 0 for off
	EphemeralSecs uint32
	// we can't send here (an announcement group, a left group)
	ReadOnly bool
	// a chat_request_older is out
	LoadingOlder bool
}

func (b0 ChatRow_builder) Build() *ChatRow {
	m0 := &ChatRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_AvatarPath = b.AvatarPath
	x.xxx_hidden_Preview = b.Preview
	x.xxx_hidden_LastMs = b.LastMs
	x.xxx_hidden_Unread = b.Unread
	x.xxx_hidden_MarkedUnread = b.MarkedUnread
	x.xxx_hidden_Pinned = b.Pinned
	x.xxx_hidden_Archived = b.Archived
	x.xxx_hidden_Muted = b.Muted
	x.xxx_hidden_MuteEndMs = b.MuteEndMs
	x.xxx_hidden_HistoryExhausted = b.HistoryExhausted
	x.xxx_hidden_EphemeralSecs = b.EphemeralSecs
	x.xxx_hidden_ReadOnly = b.ReadOnly
	x.xxx_hidden_LoadingOlder = b.LoadingOlder
	return m0
}

type ChatPreview struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text   string                 `protobuf:"bytes,1,opt,name=text"`
	xxx_hidden_FromMe bool                   `protobuf:"varint,2,opt,name=from_me,json=fromMe"`
	xxx_hidden_Status MessageStatus          `protobuf:"varint,3,opt,name=status,enum=whatevr.v2.MessageStatus"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatPreview) Reset() {
	*x = ChatPreview{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPreview) ProtoMessage() {}

func (x *ChatPreview) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatPreview) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *ChatPreview) GetFromMe() bool {
	if x != nil {
		return x.xxx_hidden_FromMe
	}
	return false
}

func (x *ChatPreview) GetStatus() MessageStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *ChatPreview) SetText(v string) {
	x.xxx_hidden_Text = v
}

func (x *ChatPreview) SetFromMe(v bool) {
	x.xxx_hidden_FromMe = v
}

func (x *ChatPreview) SetStatus(v MessageStatus) {
	x.xxx_hidden_Status = v
}

type ChatPreview_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// one line, sender prefix included in groups
	Text   string
	FromMe bool
	Status MessageStatus
}

func (b0 ChatPreview_builder) Build() *ChatPreview {
	m0 := &ChatPreview{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	x.xxx_hidden_FromMe = b.FromMe
	x.xxx_hidden_Status = b.Status
	return m0
}

type ChatMarkRead struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_UpToMessageId string                 `protobuf:"bytes,2,opt,name=up_to_message_id,json=upToMessageId"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ChatMarkRead) Reset() {
	*x = ChatMarkRead{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMarkRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMarkRead) ProtoMessage() {}

func (x *ChatMarkRead) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatMarkRead) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *ChatMarkRead) GetUpToMessageId() string {
	if x != nil {
		return x.xxx_hidden_UpToMessageId
	}
	return ""
}

func (x *ChatMarkRead) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *ChatMarkRead) SetUpToMessageId(v string) {
	x.xxx_hidden_UpToMessageId = v
}

type ChatMarkRead_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
	// the newest message the user actually saw
	UpToMessageId string
}

func (b0 ChatMarkRead_builder) Build() *ChatMarkRead {
	m0 := &ChatMarkRead{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_UpToMessageId = b.UpToMessageId
	return m0
}

type ChatPin struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Pinned bool                   `protobuf:"varint,2,opt,name=pinned"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatPin) Reset() {
	*x = ChatPin{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPin) ProtoMessage() {}

func (x *ChatPin) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatPin) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *ChatPin) GetPinned() bool {
	if x != nil {
		return x.xxx_hidden_Pinned
	}
	return false
}

func (x *ChatPin) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *ChatPin) SetPinned(v bool) {
	x.xxx_hidden_Pinned = v
}

type ChatPin_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
	Pinned bool
}

func (b0 ChatPin_builder) Build() *ChatPin {
	m0 := &ChatPin{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Pinned = b.Pinned
	return m0
}

type ChatArchive struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId   string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Archived bool                   `protobuf:"varint,2,opt,name=archived"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatArchive) Reset() {
	*x = ChatArchive{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatArchive) ProtoMessage() {}

func (x *ChatArchive) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatArchive) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *ChatArchive) GetArchived() bool {
	if x != nil {
		return x.xxx_hidden_Archived
	}
	return false
}

func (x *ChatArchive) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *ChatArchive) SetArchived(v bool) {
	x.xxx_hidden_Archived = v
}

type ChatArchive_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId   string
	Archived bool
}

func (b0 ChatArchive_builder) Build() *ChatArchive {
	m0 := &ChatArchive{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Archived = b.Archived
	return m0
}

type ChatMute struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId     string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Muted      bool                   `protobuf:"varint,2,opt,name=muted"`
	xxx_hidden_DurationMs int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ChatMute) Reset() {
	*x = ChatMute{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMute) ProtoMessage() {}

func (x *ChatMute) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatMute) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *ChatMute) GetMuted() bool {
	if x != nil {
		return x.xxx_hidden_Muted
	}
	return false
}

func (x *ChatMute) GetDurationMs() int64 {
	if x != nil {
		return x.xxx_hidden_DurationMs
	}
	return 0
}

func (x *ChatMute) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *ChatMute) SetMuted(v bool) {
	x.xxx_hidden_Muted = v
}

func (x *ChatMute) SetDurationMs(v int64) {
	x.xxx_hidden_DurationMs = v
}

type ChatMute_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
	Muted  bool
	// 0 is forever
	DurationMs int64
}

func (b0 ChatMute_builder) Build() *ChatMute {
	m0 := &ChatMute{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Muted = b.Muted
	x.xxx_hidden_DurationMs = b.DurationMs
	return m0
}

type ChatTyping struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId    string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Composing bool                   `protobuf:"varint,2,opt,name=composing"`
	xxx_hidden_Recording bool                   `protobuf:"varint,3,opt,name=recording"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChatTyping) Reset() {
	*x = ChatTyping{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTyping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTyping) ProtoMessage() {}

func (x *ChatTyping) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatTyping) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *ChatTyping) GetComposing() bool {
	if x != nil {
		return x.xxx_hidden_Composing
	}
	return false
}

func (x *ChatTyping) GetRecording() bool {
	if x != nil {
		return x.xxx_hidden_Recording
	}
	return false
}

func (x *ChatTyping) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *ChatTyping) SetComposing(v bool) {
	x.xxx_hidden_Composing = v
}

func (x *ChatTyping) SetRecording(v bool) {
	x.xxx_hidden_Recording = v
}

type ChatTyping_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId    string
	Composing bool
	Recording bool
}

func (b0 ChatTyping_builder) Build() *ChatTyping {
	m0 := &ChatTyping{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Composing = b.Composing
	x.xxx_hidden_Recording = b.Recording
	return m0
}

// asks the phone for older history; results land as message upserts
type ChatRequestOlder struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatRequestOlder) Reset() {
	*x = ChatRequestOlder{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequestOlder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequestOlder) ProtoMessage() {}

func (x *ChatRequestOlder) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatRequestOlder) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *ChatRequestOlder) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type ChatRequestOlder_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 ChatRequestOlder_builder) Build() *ChatRequestOlder {
	m0 := &ChatRequestOlder{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type ChatRequestOlderResult struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Requested bool                   `protobuf:"varint,1,opt,name=requested"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChatRequestOlderResult) Reset() {
	*x = ChatRequestOlderResult{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequestOlderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequestOlderResult) ProtoMessage() {}

func (x *ChatRequestOlderResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatRequestOlderResult) GetRequested() bool {
	if x != nil {
		return x.xxx_hidden_Requested
	}
	return false
}

func (x *ChatRequestOlderResult) SetRequested(v bool) {
	x.xxx_hidden_Requested = v
}

type ChatRequestOlderResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// false when the phone has nothing older or a request is in flight
	Requested bool
}

func (b0 ChatRequestOlderResult_builder) Build() *ChatRequestOlderResult {
	m0 := &ChatRequestOlderResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Requested = b.Requested
	return m0
}

// the direct chat with someone, there to open even before anything is in it
type ChatEnsureDirect struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person *Address               `protobuf:"bytes,1,opt,name=person"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatEnsureDirect) Reset() {
	*x = ChatEnsureDirect{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEnsureDirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEnsureDirect) ProtoMessage() {}

func (x *ChatEnsureDirect) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatEnsureDirect) GetPerson() *Address {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *ChatEnsureDirect) SetPerson(v *Address) {
	x.xxx_hidden_Person = v
}

func (x *ChatEnsureDirect) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *ChatEnsureDirect) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type ChatEnsureDirect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person *Address
}

func (b0 ChatEnsureDirect_builder) Build() *ChatEnsureDirect {
	m0 := &ChatEnsureDirect{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	return m0
}

type ChatEnsureDirectResult struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatEnsureDirectResult) Reset() {
	*x = ChatEnsureDirectResult{}
	mi := &file_whatevr_v2_chats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEnsureDirectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEnsureDirectResult) ProtoMessage() {}

func (x *ChatEnsureDirectResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_chats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatEnsureDirectResult) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *ChatEnsureDirectResult) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type ChatEnsureDirectResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 ChatEnsureDirectResult_builder) Build() *ChatEnsureDirectResult {
	m0 := &ChatEnsureDirectResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

var File_whatevr_v2_chats_proto protoreflect.FileDescriptor

const file_whatevr_v2_chats_proto_rawDesc = "" +
	"\n" +
	"\x16whatevr/v2/chats.proto\x12\n" +
	"whatevr.v2\x1a\x19whatevr/v2/messages.proto\x1a\x17whatevr/v2/people.proto\"W\n" +
	"\tChatsView\x12.\n" +
	"\x06filter\x18\x01 \x01(\x0e2\x16.whatevr.v2.ChatFilterR\x06filter\x12\x1a\n" +
	"\barchived\x18\x02 \x01(\bR\barchived\"#\n" +
	"\bChatView\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\x81\x04\n" +
	"\aChatRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.whatevr.v2.ChatTypeR\x04type\x12\x1f\n" +
	"\vavatar_path\x18\x04 \x01(\tR\n" +
	"avatarPath\x121\n" +
	"\apreview\x18\x05 \x01(\v2\x17.whatevr.v2.ChatPreviewR\apreview\x12\x17\n" +
	"\alast_ms\x18\x06 \x01(\x03R\x06lastMs\x12\x16\n" +
	"\x06unread\x18\a \x01(\rR\x06unread\x12#\n" +
	"\rmarked_unread\x18\b \x01(\bR\fmarkedUnread\x12\x16\n" +
	"\x06pinned\x18\t \x01(\bR\x06pinned\x12\x1a\n" +
	"\barchived\x18\n" +
	" \x01(\bR\barchived\x12\x14\n" +
	"\x05muted\x18\v \x01(\bR\x05muted\x12\x1e\n" +
	"\vmute_end_ms\x18\f \x01(\x03R\tmuteEndMs\x12+\n" +
	"\x11history_exhausted\x18\r \x01(\bR\x10historyExhausted\x12%\n" +
	"\x0eephemeral_secs\x18\x0e \x01(\rR\rephemeralSecs\x12\x1b\n" +
	"\tread_only\x18\x0f \x01(\bR\breadOnly\x12#\n" +
	"\rloading_older\x18\x10 \x01(\bR\floadingOlder\"m\n" +
	"\vChatPreview\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\afrom_me\x18\x02 \x01(\bR\x06fromMe\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.whatevr.v2.MessageStatusR\x06status\"P\n" +
	"\fChatMarkRead\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12'\n" +
	"\x10up_to_message_id\x18\x02 \x01(\tR\rupToMessageId\":\n" +
	"\aChatPin\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06pinned\x18\x02 \x01(\bR\x06pinned\"B\n" +
	"\vChatArchive\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1a\n" +
	"\barchived\x18\x02 \x01(\bR\barchived\"Z\n" +
	"\bChatMute\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05muted\x18\x02 \x01(\bR\x05muted\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"a\n" +
	"\n" +
	"ChatTyping\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1c\n" +
	"\tcomposing\x18\x02 \x01(\bR\tcomposing\x12\x1c\n" +
	"\trecording\x18\x03 \x01(\bR\trecording\"+\n" +
	"\x10ChatRequestOlder\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"6\n" +
	"\x16ChatRequestOlderResult\x12\x1c\n" +
	"\trequested\x18\x01 \x01(\bR\trequested\"?\n" +
	"\x10ChatEnsureDirect\x12+\n" +
	"\x06person\x18\x01 \x01(\v2\x13.whatevr.v2.AddressR\x06person\"1\n" +
	"\x16ChatEnsureDirectResult\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId*n\n" +
	"\n" +
	"ChatFilter\x12\x1b\n" +
	"\x17CHAT_FILTER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHAT_FILTER_ALL\x10\x01\x12\x16\n" +
	"\x12CHAT_FILTER_DIRECT\x10\x02\x12\x16\n" +
	"\x12CHAT_FILTER_GROUPS\x10\x03*\x9c\x01\n" +
	"\bChatType\x12\x19\n" +
	"\x15CHAT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CHAT_TYPE_DIRECT\x10\x01\x12\x13\n" +
	"\x0fCHAT_TYPE_GROUP\x10\x02\x12\x17\n" +
	"\x13CHAT_TYPE_COMMUNITY\x10\x03\x12\x18\n" +
	"\x14CHAT_TYPE_NEWSLETTER\x10\x04\x12\x17\n" +
	"\x13CHAT_TYPE_BROADCAST\x10\x05B\x9f\x01\n" +
	"\x0ecom.whatevr.v2B\n" +
	"ChatsProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_chats_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_whatevr_v2_chats_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_whatevr_v2_chats_proto_goTypes = []any{
	(ChatFilter)(0),                // 0: whatevr.v2.ChatFilter
	(ChatType)(0),                  // 1: whatevr.v2.ChatType
	(*ChatsView)(nil),              // 2: whatevr.v2.ChatsView
	(*ChatView)(nil),               // 3: whatevr.v2.ChatView
	(*ChatRow)(nil),                // 4: whatevr.v2.ChatRow
	(*ChatPreview)(nil),            // 5: whatevr.v2.ChatPreview
	(*ChatMarkRead)(nil),           // 6: whatevr.v2.ChatMarkRead
	(*ChatPin)(nil),                // 7: whatevr.v2.ChatPin
	(*ChatArchive)(nil),            // 8: whatevr.v2.ChatArchive
	(*ChatMute)(nil),               // 9: whatevr.v2.ChatMute
	(*ChatTyping)(nil),             // 10: whatevr.v2.ChatTyping
	(*ChatRequestOlder)(nil),       // 11: whatevr.v2.ChatRequestOlder
	(*ChatRequestOlderResult)(nil), // 12: whatevr.v2.ChatRequestOlderResult
	(*ChatEnsureDirect)(nil),       // 13: whatevr.v2.ChatEnsureDirect
	(*ChatEnsureDirectResult)(nil), // 14: whatevr.v2.ChatEnsureDirectResult
	(MessageStatus)(0),             // 15: whatevr.v2.MessageStatus
	(*Address)(nil),                // 16: whatevr.v2.Address
}
var file_whatevr_v2_chats_proto_depIdxs = []int32{
	0,  // 0: whatevr.v2.ChatsView.filter:type_name -> whatevr.v2.ChatFilter
	1,  // 1: whatevr.v2.ChatRow.type:type_name -> whatevr.v2.ChatType
	5,  // 2: whatevr.v2.ChatRow.preview:type_name -> whatevr.v2.ChatPreview
	15, // 3: whatevr.v2.ChatPreview.status:type_name -> whatevr.v2.MessageStatus
	16, // 4: whatevr.v2.ChatEnsureDirect.person:type_name -> whatevr.v2.Address
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_whatevr_v2_chats_proto_init() }
func file_whatevr_v2_chats_proto_init() {
	if File_whatevr_v2_chats_proto != nil {
		return
	}
	file_whatevr_v2_messages_proto_init()
	file_whatevr_v2_people_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_chats_proto_rawDesc), len(file_whatevr_v2_chats_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_chats_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_chats_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_chats_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_chats_proto_msgTypes,
	}.Build()
	File_whatevr_v2_chats_proto = out.File
	file_whatevr_v2_chats_proto_goTypes = nil
	file_whatevr_v2_chats_proto_depIdxs = nil
}
