// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/frontends.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// where the daemon found a frontend. when two share an id, user beats
// native beats system.
type FrontendSource int32

const (
	FrontendSource_FRONTEND_SOURCE_UNSPECIFIED FrontendSource = 0
	// a manifest a package installed
	FrontendSource_FRONTEND_SOURCE_SYSTEM FrontendSource = 1
	// a .desktop entry, or a macOS app declaring the whatevr-frontend scheme
	FrontendSource_FRONTEND_SOURCE_NATIVE FrontendSource = 2
	// a manifest in the user's config dir
	FrontendSource_FRONTEND_SOURCE_USER FrontendSource = 3
)

// Enum value maps for FrontendSource.
var (
	FrontendSource_name = map[int32]string{
		0: "FRONTEND_SOURCE_UNSPECIFIED",
		1: "FRONTEND_SOURCE_SYSTEM",
		2: "FRONTEND_SOURCE_NATIVE",
		3: "FRONTEND_SOURCE_USER",
	}
	FrontendSource_value = map[string]int32{
		"FRONTEND_SOURCE_UNSPECIFIED": 0,
		"FRONTEND_SOURCE_SYSTEM":      1,
		"FRONTEND_SOURCE_NATIVE":      2,
		"FRONTEND_SOURCE_USER":        3,
	}
)

func (x FrontendSource) Enum() *FrontendSource {
	p := new(FrontendSource)
	*p = x
	return p
}

func (x FrontendSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrontendSource) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_frontends_proto_enumTypes[0].Descriptor()
}

func (FrontendSource) Type() protoreflect.EnumType {
	return &file_whatevr_v2_frontends_proto_enumTypes[0]
}

func (x FrontendSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Frontend struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name      string                 `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Terminal  bool                   `protobuf:"varint,3,opt,name=terminal"`
	xxx_hidden_Source    FrontendSource         `protobuf:"varint,4,opt,name=source,enum=whatevr.v2.FrontendSource"`
	xxx_hidden_Connected bool                   `protobuf:"varint,5,opt,name=connected"`
	xxx_hidden_IsDefault bool                   `protobuf:"varint,6,opt,name=is_default,json=isDefault"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Frontend) Reset() {
	*x = Frontend{}
	mi := &file_whatevr_v2_frontends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frontend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frontend) ProtoMessage() {}

func (x *Frontend) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_frontends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Frontend) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Frontend) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Frontend) GetTerminal() bool {
	if x != nil {
		return x.xxx_hidden_Terminal
	}
	return false
}

func (x *Frontend) GetSource() FrontendSource {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return FrontendSource_FRONTEND_SOURCE_UNSPECIFIED
}

func (x *Frontend) GetConnected() bool {
	if x != nil {
		return x.xxx_hidden_Connected
	}
	return false
}

func (x *Frontend) GetIsDefault() bool {
	if x != nil {
		return x.xxx_hidden_IsDefault
	}
	return false
}

func (x *Frontend) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Frontend) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Frontend) SetTerminal(v bool) {
	x.xxx_hidden_Terminal = v
}

func (x *Frontend) SetSource(v FrontendSource) {
	x.xxx_hidden_Source = v
}

func (x *Frontend) SetConnected(v bool) {
	x.xxx_hidden_Connected = v
}

func (x *Frontend) SetIsDefault(v bool) {
	x.xxx_hidden_IsDefault = v
}

type Frontend_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
	// runs in a terminal the daemon opens for it
	Terminal bool
	// unspecified for one that is connected but the daemon can't start
	Source FrontendSource
	// a connection that said hello with this id is open
	Connected bool
	// the one a click or link starts when no frontend is connected
	IsDefault bool
}

func (b0 Frontend_builder) Build() *Frontend {
	m0 := &Frontend{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Terminal = b.Terminal
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Connected = b.Connected
	x.xxx_hidden_IsDefault = b.IsDefault
	return m0
}

type FrontendList struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendList) Reset() {
	*x = FrontendList{}
	mi := &file_whatevr_v2_frontends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendList) ProtoMessage() {}

func (x *FrontendList) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_frontends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FrontendList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 FrontendList_builder) Build() *FrontendList {
	m0 := &FrontendList{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type FrontendListResult struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Frontends *[]*Frontend           `protobuf:"bytes,1,rep,name=frontends"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FrontendListResult) Reset() {
	*x = FrontendListResult{}
	mi := &file_whatevr_v2_frontends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendListResult) ProtoMessage() {}

func (x *FrontendListResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_frontends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FrontendListResult) GetFrontends() []*Frontend {
	if x != nil {
		if x.xxx_hidden_Frontends != nil {
			return *x.xxx_hidden_Frontends
		}
	}
	return nil
}

func (x *FrontendListResult) SetFrontends(v []*Frontend) {
	x.xxx_hidden_Frontends = &v
}

type FrontendListResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Frontends []*Frontend
}

func (b0 FrontendListResult_builder) Build() *FrontendListResult {
	m0 := &FrontendListResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Frontends = &b.Frontends
	return m0
}

// makes id the default. it has to be one the daemon can start.
type FrontendSetDefault struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendSetDefault) Reset() {
	*x = FrontendSetDefault{}
	mi := &file_whatevr_v2_frontends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendSetDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendSetDefault) ProtoMessage() {}

func (x *FrontendSetDefault) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_frontends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FrontendSetDefault) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *FrontendSetDefault) SetId(v string) {
	x.xxx_hidden_Id = v
}

type FrontendSetDefault_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 FrontendSetDefault_builder) Build() *FrontendSetDefault {
	m0 := &FrontendSetDefault{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

// opens a whatevr:// link: a chat by id or address, or no chat at all, which
// brings a frontend forward. it only ever navigates, never sends.
type LinkOpen struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Url string                 `protobuf:"bytes,1,opt,name=url"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LinkOpen) Reset() {
	*x = LinkOpen{}
	mi := &file_whatevr_v2_frontends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkOpen) ProtoMessage() {}

func (x *LinkOpen) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_frontends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LinkOpen) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *LinkOpen) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

type LinkOpen_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url string
}

func (b0 LinkOpen_builder) Build() *LinkOpen {
	m0 := &LinkOpen{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Url = b.Url
	return m0
}

// someone opened whatevr itself, the app or the launcher entry, with no chat
// in mind. a frontend that can raise its window does; one that can't
// ignores it
type Activate struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activate) Reset() {
	*x = Activate{}
	mi := &file_whatevr_v2_frontends_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activate) ProtoMessage() {}

func (x *Activate) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_frontends_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Activate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Activate_builder) Build() *Activate {
	m0 := &Activate{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_whatevr_v2_frontends_proto protoreflect.FileDescriptor

const file_whatevr_v2_frontends_proto_rawDesc = "" +
	"\n" +
	"\x1awhatevr/v2/frontends.proto\x12\n" +
	"whatevr.v2\"\xbb\x01\n" +
	"\bFrontend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bterminal\x18\x03 \x01(\bR\bterminal\x122\n" +
	"\x06source\x18\x04 \x01(\x0e2\x1a.whatevr.v2.FrontendSourceR\x06source\x12\x1c\n" +
	"\tconnected\x18\x05 \x01(\bR\tconnected\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\"\x0e\n" +
	"\fFrontendList\"H\n" +
	"\x12FrontendListResult\x122\n" +
	"\tfrontends\x18\x01 \x03(\v2\x14.whatevr.v2.FrontendR\tfrontends\"$\n" +
	"\x12FrontendSetDefault\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\bLinkOpen\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\n" +
	"\n" +
	"\bActivate*\x83\x01\n" +
	"\x0eFrontendSource\x12\x1f\n" +
	"\x1bFRONTEND_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FRONTEND_SOURCE_SYSTEM\x10\x01\x12\x1a\n" +
	"\x16FRONTEND_SOURCE_NATIVE\x10\x02\x12\x18\n" +
	"\x14FRONTEND_SOURCE_USER\x10\x03B\xa3\x01\n" +
	"\x0ecom.whatevr.v2B\x0eFrontendsProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_frontends_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whatevr_v2_frontends_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_whatevr_v2_frontends_proto_goTypes = []any{
	(FrontendSource)(0),        // 0: whatevr.v2.FrontendSource
	(*Frontend)(nil),           // 1: whatevr.v2.Frontend
	(*FrontendList)(nil),       // 2: whatevr.v2.FrontendList
	(*FrontendListResult)(nil), // 3: whatevr.v2.FrontendListResult
	(*FrontendSetDefault)(nil), // 4: whatevr.v2.FrontendSetDefault
	(*LinkOpen)(nil),           // 5: whatevr.v2.LinkOpen
	(*Activate)(nil),           // 6: whatevr.v2.Activate
}
var file_whatevr_v2_frontends_proto_depIdxs = []int32{
	0, // 0: whatevr.v2.Frontend.source:type_name -> whatevr.v2.FrontendSource
	1, // 1: whatevr.v2.FrontendListResult.frontends:type_name -> whatevr.v2.Frontend
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_whatevr_v2_frontends_proto_init() }
func file_whatevr_v2_frontends_proto_init() {
	if File_whatevr_v2_frontends_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_frontends_proto_rawDesc), len(file_whatevr_v2_frontends_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_frontends_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_frontends_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_frontends_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_frontends_proto_msgTypes,
	}.Build()
	File_whatevr_v2_frontends_proto = out.File
	file_whatevr_v2_frontends_proto_goTypes = nil
	file_whatevr_v2_frontends_proto_depIdxs = nil
}
