// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/groups.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupRole int32

const (
	GroupRole_GROUP_ROLE_UNSPECIFIED GroupRole = 0
	GroupRole_GROUP_ROLE_MEMBER      GroupRole = 1
	GroupRole_GROUP_ROLE_ADMIN       GroupRole = 2
	GroupRole_GROUP_ROLE_SUPERADMIN  GroupRole = 3
	// not in the group any more
	GroupRole_GROUP_ROLE_LEFT GroupRole = 4
)

// Enum value maps for GroupRole.
var (
	GroupRole_name = map[int32]string{
		0: "GROUP_ROLE_UNSPECIFIED",
		1: "GROUP_ROLE_MEMBER",
		2: "GROUP_ROLE_ADMIN",
		3: "GROUP_ROLE_SUPERADMIN",
		4: "GROUP_ROLE_LEFT",
	}
	GroupRole_value = map[string]int32{
		"GROUP_ROLE_UNSPECIFIED": 0,
		"GROUP_ROLE_MEMBER":      1,
		"GROUP_ROLE_ADMIN":       2,
		"GROUP_ROLE_SUPERADMIN":  3,
		"GROUP_ROLE_LEFT":        4,
	}
)

func (x GroupRole) Enum() *GroupRole {
	p := new(GroupRole)
	*p = x
	return p
}

func (x GroupRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupRole) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_groups_proto_enumTypes[0].Descriptor()
}

func (GroupRole) Type() protoreflect.EnumType {
	return &file_whatevr_v2_groups_proto_enumTypes[0]
}

func (x GroupRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// a group's facts, no members; group_members has those
type GroupView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupView) Reset() {
	*x = GroupView{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupView) ProtoMessage() {}

func (x *GroupView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupView) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupView) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type GroupView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 GroupView_builder) Build() *GroupView {
	m0 := &GroupView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type GroupRow struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId      string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Subject     string                 `protobuf:"bytes,2,opt,name=subject"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_AvatarPath  string                 `protobuf:"bytes,4,opt,name=avatar_path,json=avatarPath"`
	xxx_hidden_CreatedMs   int64                  `protobuf:"varint,5,opt,name=created_ms,json=createdMs"`
	xxx_hidden_Owner       *Person                `protobuf:"bytes,6,opt,name=owner"`
	xxx_hidden_MemberCount uint32                 `protobuf:"varint,7,opt,name=member_count,json=memberCount"`
	xxx_hidden_MyRole      GroupRole              `protobuf:"varint,8,opt,name=my_role,json=myRole,enum=whatevr.v2.GroupRole"`
	xxx_hidden_Announce    bool                   `protobuf:"varint,9,opt,name=announce"`
	xxx_hidden_Locked      bool                   `protobuf:"varint,10,opt,name=locked"`
	xxx_hidden_Approval    bool                   `protobuf:"varint,11,opt,name=approval"`
	xxx_hidden_CommunityId string                 `protobuf:"bytes,12,opt,name=community_id,json=communityId"`
	xxx_hidden_Error       string                 `protobuf:"bytes,13,opt,name=error"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GroupRow) Reset() {
	*x = GroupRow{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRow) ProtoMessage() {}

func (x *GroupRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupRow) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupRow) GetSubject() string {
	if x != nil {
		return x.xxx_hidden_Subject
	}
	return ""
}

func (x *GroupRow) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *GroupRow) GetAvatarPath() string {
	if x != nil {
		return x.xxx_hidden_AvatarPath
	}
	return ""
}

func (x *GroupRow) GetCreatedMs() int64 {
	if x != nil {
		return x.xxx_hidden_CreatedMs
	}
	return 0
}

func (x *GroupRow) GetOwner() *Person {
	if x != nil {
		return x.xxx_hidden_Owner
	}
	return nil
}

func (x *GroupRow) GetMemberCount() uint32 {
	if x != nil {
		return x.xxx_hidden_MemberCount
	}
	return 0
}

func (x *GroupRow) GetMyRole() GroupRole {
	if x != nil {
		return x.xxx_hidden_MyRole
	}
	return GroupRole_GROUP_ROLE_UNSPECIFIED
}

func (x *GroupRow) GetAnnounce() bool {
	if x != nil {
		return x.xxx_hidden_Announce
	}
	return false
}

func (x *GroupRow) GetLocked() bool {
	if x != nil {
		return x.xxx_hidden_Locked
	}
	return false
}

func (x *GroupRow) GetApproval() bool {
	if x != nil {
		return x.xxx_hidden_Approval
	}
	return false
}

func (x *GroupRow) GetCommunityId() string {
	if x != nil {
		return x.xxx_hidden_CommunityId
	}
	return ""
}

func (x *GroupRow) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *GroupRow) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupRow) SetSubject(v string) {
	x.xxx_hidden_Subject = v
}

func (x *GroupRow) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *GroupRow) SetAvatarPath(v string) {
	x.xxx_hidden_AvatarPath = v
}

func (x *GroupRow) SetCreatedMs(v int64) {
	x.xxx_hidden_CreatedMs = v
}

func (x *GroupRow) SetOwner(v *Person) {
	x.xxx_hidden_Owner = v
}

func (x *GroupRow) SetMemberCount(v uint32) {
	x.xxx_hidden_MemberCount = v
}

func (x *GroupRow) SetMyRole(v GroupRole) {
	x.xxx_hidden_MyRole = v
}

func (x *GroupRow) SetAnnounce(v bool) {
	x.xxx_hidden_Announce = v
}

func (x *GroupRow) SetLocked(v bool) {
	x.xxx_hidden_Locked = v
}

func (x *GroupRow) SetApproval(v bool) {
	x.xxx_hidden_Approval = v
}

func (x *GroupRow) SetCommunityId(v string) {
	x.xxx_hidden_CommunityId = v
}

func (x *GroupRow) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *GroupRow) HasOwner() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Owner != nil
}

func (x *GroupRow) ClearOwner() {
	x.xxx_hidden_Owner = nil
}

type GroupRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId      string
	Subject     string
	Description string
	AvatarPath  string
	CreatedMs   int64
	Owner       *Person
	MemberCount uint32
	MyRole      GroupRole
	// only admins send
	Announce bool
	// only admins edit the group's info
	Locked bool
	// joining needs an admin's approval
	Approval bool
	// the community this group belongs to
	CommunityId string
	// why whatsapp wouldn't describe it, empty when it did
	Error string
}

func (b0 GroupRow_builder) Build() *GroupRow {
	m0 := &GroupRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Subject = b.Subject
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_AvatarPath = b.AvatarPath
	x.xxx_hidden_CreatedMs = b.CreatedMs
	x.xxx_hidden_Owner = b.Owner
	x.xxx_hidden_MemberCount = b.MemberCount
	x.xxx_hidden_MyRole = b.MyRole
	x.xxx_hidden_Announce = b.Announce
	x.xxx_hidden_Locked = b.Locked
	x.xxx_hidden_Approval = b.Approval
	x.xxx_hidden_CommunityId = b.CommunityId
	x.xxx_hidden_Error = b.Error
	return m0
}

type GroupMembersView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupMembersView) Reset() {
	*x = GroupMembersView{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersView) ProtoMessage() {}

func (x *GroupMembersView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupMembersView) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupMembersView) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type GroupMembersView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 GroupMembersView_builder) Build() *GroupMembersView {
	m0 := &GroupMembersView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type GroupMemberRow struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person *Person                `protobuf:"bytes,1,opt,name=person"`
	xxx_hidden_Role   GroupRole              `protobuf:"varint,2,opt,name=role,enum=whatevr.v2.GroupRole"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupMemberRow) Reset() {
	*x = GroupMemberRow{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberRow) ProtoMessage() {}

func (x *GroupMemberRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupMemberRow) GetPerson() *Person {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *GroupMemberRow) GetRole() GroupRole {
	if x != nil {
		return x.xxx_hidden_Role
	}
	return GroupRole_GROUP_ROLE_UNSPECIFIED
}

func (x *GroupMemberRow) SetPerson(v *Person) {
	x.xxx_hidden_Person = v
}

func (x *GroupMemberRow) SetRole(v GroupRole) {
	x.xxx_hidden_Role = v
}

func (x *GroupMemberRow) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *GroupMemberRow) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type GroupMemberRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person *Person
	Role   GroupRole
}

func (b0 GroupMemberRow_builder) Build() *GroupMemberRow {
	m0 := &GroupMemberRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	x.xxx_hidden_Role = b.Role
	return m0
}

// creates a group with an optional member list and photo; answers the chat
type GroupCreate struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name      string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Members   []string               `protobuf:"bytes,2,rep,name=members"`
	xxx_hidden_PhotoPath string                 `protobuf:"bytes,3,opt,name=photo_path,json=photoPath"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GroupCreate) Reset() {
	*x = GroupCreate{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreate) ProtoMessage() {}

func (x *GroupCreate) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupCreate) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GroupCreate) GetMembers() []string {
	if x != nil {
		return x.xxx_hidden_Members
	}
	return nil
}

func (x *GroupCreate) GetPhotoPath() string {
	if x != nil {
		return x.xxx_hidden_PhotoPath
	}
	return ""
}

func (x *GroupCreate) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *GroupCreate) SetMembers(v []string) {
	x.xxx_hidden_Members = v
}

func (x *GroupCreate) SetPhotoPath(v string) {
	x.xxx_hidden_PhotoPath = v
}

type GroupCreate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name      string
	Members   []string
	PhotoPath string
}

func (b0 GroupCreate_builder) Build() *GroupCreate {
	m0 := &GroupCreate{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Members = b.Members
	x.xxx_hidden_PhotoPath = b.PhotoPath
	return m0
}

type GroupCreateResult struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupCreateResult) Reset() {
	*x = GroupCreateResult{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateResult) ProtoMessage() {}

func (x *GroupCreateResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupCreateResult) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupCreateResult) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type GroupCreateResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 GroupCreateResult_builder) Build() *GroupCreateResult {
	m0 := &GroupCreateResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type GroupLeave struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupLeave) Reset() {
	*x = GroupLeave{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLeave) ProtoMessage() {}

func (x *GroupLeave) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupLeave) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupLeave) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type GroupLeave_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 GroupLeave_builder) Build() *GroupLeave {
	m0 := &GroupLeave{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type GroupSetName struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Name   string                 `protobuf:"bytes,2,opt,name=name"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupSetName) Reset() {
	*x = GroupSetName{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSetName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSetName) ProtoMessage() {}

func (x *GroupSetName) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupSetName) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupSetName) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GroupSetName) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupSetName) SetName(v string) {
	x.xxx_hidden_Name = v
}

type GroupSetName_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
	Name   string
}

func (b0 GroupSetName_builder) Build() *GroupSetName {
	m0 := &GroupSetName{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Name = b.Name
	return m0
}

type GroupSetTopic struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId      string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GroupSetTopic) Reset() {
	*x = GroupSetTopic{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSetTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSetTopic) ProtoMessage() {}

func (x *GroupSetTopic) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupSetTopic) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupSetTopic) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *GroupSetTopic) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupSetTopic) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

type GroupSetTopic_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId      string
	Description string
}

func (b0 GroupSetTopic_builder) Build() *GroupSetTopic {
	m0 := &GroupSetTopic{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Description = b.Description
	return m0
}

type GroupSetPhoto struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Path   string                 `protobuf:"bytes,2,opt,name=path"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupSetPhoto) Reset() {
	*x = GroupSetPhoto{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSetPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSetPhoto) ProtoMessage() {}

func (x *GroupSetPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupSetPhoto) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupSetPhoto) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *GroupSetPhoto) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupSetPhoto) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type GroupSetPhoto_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
	// empty clears the photo, otherwise a local file to upload
	Path string
}

func (b0 GroupSetPhoto_builder) Build() *GroupSetPhoto {
	m0 := &GroupSetPhoto{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Path = b.Path
	return m0
}

type GroupInviteLink struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Reset_ bool                   `protobuf:"varint,2,opt,name=reset"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupInviteLink) Reset() {
	*x = GroupInviteLink{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteLink) ProtoMessage() {}

func (x *GroupInviteLink) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupInviteLink) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupInviteLink) GetReset() bool {
	if x != nil {
		return x.xxx_hidden_Reset_
	}
	return false
}

func (x *GroupInviteLink) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupInviteLink) SetReset(v bool) {
	x.xxx_hidden_Reset_ = v
}

type GroupInviteLink_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
	Reset  bool
}

func (b0 GroupInviteLink_builder) Build() *GroupInviteLink {
	m0 := &GroupInviteLink{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Reset_ = b.Reset
	return m0
}

type GroupInviteLinkResult struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Link string                 `protobuf:"bytes,1,opt,name=link"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupInviteLinkResult) Reset() {
	*x = GroupInviteLinkResult{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteLinkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteLinkResult) ProtoMessage() {}

func (x *GroupInviteLinkResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupInviteLinkResult) GetLink() string {
	if x != nil {
		return x.xxx_hidden_Link
	}
	return ""
}

func (x *GroupInviteLinkResult) SetLink(v string) {
	x.xxx_hidden_Link = v
}

type GroupInviteLinkResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Link string
}

func (b0 GroupInviteLinkResult_builder) Build() *GroupInviteLinkResult {
	m0 := &GroupInviteLinkResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Link = b.Link
	return m0
}

type GroupMembers struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId  string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Action  string                 `protobuf:"bytes,2,opt,name=action"`
	xxx_hidden_Members []string               `protobuf:"bytes,3,rep,name=members"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupMembers) Reset() {
	*x = GroupMembers{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembers) ProtoMessage() {}

func (x *GroupMembers) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupMembers) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupMembers) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *GroupMembers) GetMembers() []string {
	if x != nil {
		return x.xxx_hidden_Members
	}
	return nil
}

func (x *GroupMembers) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupMembers) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *GroupMembers) SetMembers(v []string) {
	x.xxx_hidden_Members = v
}

type GroupMembers_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
	// one of add, remove, promote, demote
	Action  string
	Members []string
}

func (b0 GroupMembers_builder) Build() *GroupMembers {
	m0 := &GroupMembers{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Action = b.Action
	x.xxx_hidden_Members = b.Members
	return m0
}

type GroupSetAnnounce struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId  string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Enabled bool                   `protobuf:"varint,2,opt,name=enabled"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupSetAnnounce) Reset() {
	*x = GroupSetAnnounce{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSetAnnounce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSetAnnounce) ProtoMessage() {}

func (x *GroupSetAnnounce) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupSetAnnounce) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupSetAnnounce) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *GroupSetAnnounce) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupSetAnnounce) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
}

type GroupSetAnnounce_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId  string
	Enabled bool
}

func (b0 GroupSetAnnounce_builder) Build() *GroupSetAnnounce {
	m0 := &GroupSetAnnounce{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Enabled = b.Enabled
	return m0
}

type GroupSetLocked struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId  string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Enabled bool                   `protobuf:"varint,2,opt,name=enabled"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupSetLocked) Reset() {
	*x = GroupSetLocked{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSetLocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSetLocked) ProtoMessage() {}

func (x *GroupSetLocked) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupSetLocked) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupSetLocked) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *GroupSetLocked) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupSetLocked) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
}

type GroupSetLocked_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId  string
	Enabled bool
}

func (b0 GroupSetLocked_builder) Build() *GroupSetLocked {
	m0 := &GroupSetLocked{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Enabled = b.Enabled
	return m0
}

type CommunityLink struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CommunityId string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId"`
	xxx_hidden_GroupId     string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CommunityLink) Reset() {
	*x = CommunityLink{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityLink) ProtoMessage() {}

func (x *CommunityLink) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommunityLink) GetCommunityId() string {
	if x != nil {
		return x.xxx_hidden_CommunityId
	}
	return ""
}

func (x *CommunityLink) GetGroupId() string {
	if x != nil {
		return x.xxx_hidden_GroupId
	}
	return ""
}

func (x *CommunityLink) SetCommunityId(v string) {
	x.xxx_hidden_CommunityId = v
}

func (x *CommunityLink) SetGroupId(v string) {
	x.xxx_hidden_GroupId = v
}

type CommunityLink_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CommunityId string
	GroupId     string
}

func (b0 CommunityLink_builder) Build() *CommunityLink {
	m0 := &CommunityLink{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CommunityId = b.CommunityId
	x.xxx_hidden_GroupId = b.GroupId
	return m0
}

type CommunityUnlink struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CommunityId string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId"`
	xxx_hidden_GroupId     string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CommunityUnlink) Reset() {
	*x = CommunityUnlink{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityUnlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityUnlink) ProtoMessage() {}

func (x *CommunityUnlink) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommunityUnlink) GetCommunityId() string {
	if x != nil {
		return x.xxx_hidden_CommunityId
	}
	return ""
}

func (x *CommunityUnlink) GetGroupId() string {
	if x != nil {
		return x.xxx_hidden_GroupId
	}
	return ""
}

func (x *CommunityUnlink) SetCommunityId(v string) {
	x.xxx_hidden_CommunityId = v
}

func (x *CommunityUnlink) SetGroupId(v string) {
	x.xxx_hidden_GroupId = v
}

type CommunityUnlink_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CommunityId string
	GroupId     string
}

func (b0 CommunityUnlink_builder) Build() *CommunityUnlink {
	m0 := &CommunityUnlink{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CommunityId = b.CommunityId
	x.xxx_hidden_GroupId = b.GroupId
	return m0
}

var File_whatevr_v2_groups_proto protoreflect.FileDescriptor

const file_whatevr_v2_groups_proto_rawDesc = "" +
	"\n" +
	"\x17whatevr/v2/groups.proto\x12\n" +
	"whatevr.v2\x1a\x17whatevr/v2/people.proto\"$\n" +
	"\tGroupView\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\xa5\x03\n" +
	"\bGroupRow\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vavatar_path\x18\x04 \x01(\tR\n" +
	"avatarPath\x12\x1d\n" +
	"\n" +
	"created_ms\x18\x05 \x01(\x03R\tcreatedMs\x12(\n" +
	"\x05owner\x18\x06 \x01(\v2\x12.whatevr.v2.PersonR\x05owner\x12!\n" +
	"\fmember_count\x18\a \x01(\rR\vmemberCount\x12.\n" +
	"\amy_role\x18\b \x01(\x0e2\x15.whatevr.v2.GroupRoleR\x06myRole\x12\x1a\n" +
	"\bannounce\x18\t \x01(\bR\bannounce\x12\x16\n" +
	"\x06locked\x18\n" +
	" \x01(\bR\x06locked\x12\x1a\n" +
	"\bapproval\x18\v \x01(\bR\bapproval\x12!\n" +
	"\fcommunity_id\x18\f \x01(\tR\vcommunityId\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\"+\n" +
	"\x10GroupMembersView\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"g\n" +
	"\x0eGroupMemberRow\x12*\n" +
	"\x06person\x18\x01 \x01(\v2\x12.whatevr.v2.PersonR\x06person\x12)\n" +
	"\x04role\x18\x02 \x01(\x0e2\x15.whatevr.v2.GroupRoleR\x04role\"Z\n" +
	"\vGroupCreate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\x12\x1d\n" +
	"\n" +
	"photo_path\x18\x03 \x01(\tR\tphotoPath\",\n" +
	"\x11GroupCreateResult\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"%\n" +
	"\n" +
	"GroupLeave\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\";\n" +
	"\fGroupSetName\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"J\n" +
	"\rGroupSetTopic\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"<\n" +
	"\rGroupSetPhoto\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"@\n" +
	"\x0fGroupInviteLink\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\"+\n" +
	"\x15GroupInviteLinkResult\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\"Y\n" +
	"\fGroupMembers\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\amembers\x18\x03 \x03(\tR\amembers\"E\n" +
	"\x10GroupSetAnnounce\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"C\n" +
	"\x0eGroupSetLocked\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"M\n" +
	"\rCommunityLink\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"O\n" +
	"\x0fCommunityUnlink\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId*\x84\x01\n" +
	"\tGroupRole\x12\x1a\n" +
	"\x16GROUP_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11GROUP_ROLE_MEMBER\x10\x01\x12\x14\n" +
	"\x10GROUP_ROLE_ADMIN\x10\x02\x12\x19\n" +
	"\x15GROUP_ROLE_SUPERADMIN\x10\x03\x12\x13\n" +
	"\x0fGROUP_ROLE_LEFT\x10\x04B\xa0\x01\n" +
	"\x0ecom.whatevr.v2B\vGroupsProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_groups_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whatevr_v2_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_whatevr_v2_groups_proto_goTypes = []any{
	(GroupRole)(0),                // 0: whatevr.v2.GroupRole
	(*GroupView)(nil),             // 1: whatevr.v2.GroupView
	(*GroupRow)(nil),              // 2: whatevr.v2.GroupRow
	(*GroupMembersView)(nil),      // 3: whatevr.v2.GroupMembersView
	(*GroupMemberRow)(nil),        // 4: whatevr.v2.GroupMemberRow
	(*GroupCreate)(nil),           // 5: whatevr.v2.GroupCreate
	(*GroupCreateResult)(nil),     // 6: whatevr.v2.GroupCreateResult
	(*GroupLeave)(nil),            // 7: whatevr.v2.GroupLeave
	(*GroupSetName)(nil),          // 8: whatevr.v2.GroupSetName
	(*GroupSetTopic)(nil),         // 9: whatevr.v2.GroupSetTopic
	(*GroupSetPhoto)(nil),         // 10: whatevr.v2.GroupSetPhoto
	(*GroupInviteLink)(nil),       // 11: whatevr.v2.GroupInviteLink
	(*GroupInviteLinkResult)(nil), // 12: whatevr.v2.GroupInviteLinkResult
	(*GroupMembers)(nil),          // 13: whatevr.v2.GroupMembers
	(*GroupSetAnnounce)(nil),      // 14: whatevr.v2.GroupSetAnnounce
	(*GroupSetLocked)(nil),        // 15: whatevr.v2.GroupSetLocked
	(*CommunityLink)(nil),         // 16: whatevr.v2.CommunityLink
	(*CommunityUnlink)(nil),       // 17: whatevr.v2.CommunityUnlink
	(*Person)(nil),                // 18: whatevr.v2.Person
}
var file_whatevr_v2_groups_proto_depIdxs = []int32{
	18, // 0: whatevr.v2.GroupRow.owner:type_name -> whatevr.v2.Person
	0,  // 1: whatevr.v2.GroupRow.my_role:type_name -> whatevr.v2.GroupRole
	18, // 2: whatevr.v2.GroupMemberRow.person:type_name -> whatevr.v2.Person
	0,  // 3: whatevr.v2.GroupMemberRow.role:type_name -> whatevr.v2.GroupRole
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_whatevr_v2_groups_proto_init() }
func file_whatevr_v2_groups_proto_init() {
	if File_whatevr_v2_groups_proto != nil {
		return
	}
	file_whatevr_v2_people_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_groups_proto_rawDesc), len(file_whatevr_v2_groups_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_groups_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_groups_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_groups_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_groups_proto_msgTypes,
	}.Build()
	File_whatevr_v2_groups_proto = out.File
	file_whatevr_v2_groups_proto_goTypes = nil
	file_whatevr_v2_groups_proto_depIdxs = nil
}
