// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/groups.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupRole int32

const (
	GroupRole_GROUP_ROLE_UNSPECIFIED GroupRole = 0
	GroupRole_GROUP_ROLE_MEMBER      GroupRole = 1
	GroupRole_GROUP_ROLE_ADMIN       GroupRole = 2
	GroupRole_GROUP_ROLE_SUPERADMIN  GroupRole = 3
	// not in the group any more
	GroupRole_GROUP_ROLE_LEFT GroupRole = 4
)

// Enum value maps for GroupRole.
var (
	GroupRole_name = map[int32]string{
		0: "GROUP_ROLE_UNSPECIFIED",
		1: "GROUP_ROLE_MEMBER",
		2: "GROUP_ROLE_ADMIN",
		3: "GROUP_ROLE_SUPERADMIN",
		4: "GROUP_ROLE_LEFT",
	}
	GroupRole_value = map[string]int32{
		"GROUP_ROLE_UNSPECIFIED": 0,
		"GROUP_ROLE_MEMBER":      1,
		"GROUP_ROLE_ADMIN":       2,
		"GROUP_ROLE_SUPERADMIN":  3,
		"GROUP_ROLE_LEFT":        4,
	}
)

func (x GroupRole) Enum() *GroupRole {
	p := new(GroupRole)
	*p = x
	return p
}

func (x GroupRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupRole) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_groups_proto_enumTypes[0].Descriptor()
}

func (GroupRole) Type() protoreflect.EnumType {
	return &file_whatevr_v2_groups_proto_enumTypes[0]
}

func (x GroupRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// a group's facts, no members; group_members has those
type GroupView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupView) Reset() {
	*x = GroupView{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupView) ProtoMessage() {}

func (x *GroupView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupView) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupView) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type GroupView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 GroupView_builder) Build() *GroupView {
	m0 := &GroupView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type GroupRow struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId      string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Subject     string                 `protobuf:"bytes,2,opt,name=subject"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_AvatarPath  string                 `protobuf:"bytes,4,opt,name=avatar_path,json=avatarPath"`
	xxx_hidden_CreatedMs   int64                  `protobuf:"varint,5,opt,name=created_ms,json=createdMs"`
	xxx_hidden_Owner       *Person                `protobuf:"bytes,6,opt,name=owner"`
	xxx_hidden_MemberCount uint32                 `protobuf:"varint,7,opt,name=member_count,json=memberCount"`
	xxx_hidden_MyRole      GroupRole              `protobuf:"varint,8,opt,name=my_role,json=myRole,enum=whatevr.v2.GroupRole"`
	xxx_hidden_Announce    bool                   `protobuf:"varint,9,opt,name=announce"`
	xxx_hidden_Locked      bool                   `protobuf:"varint,10,opt,name=locked"`
	xxx_hidden_Approval    bool                   `protobuf:"varint,11,opt,name=approval"`
	xxx_hidden_CommunityId string                 `protobuf:"bytes,12,opt,name=community_id,json=communityId"`
	xxx_hidden_Error       string                 `protobuf:"bytes,13,opt,name=error"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GroupRow) Reset() {
	*x = GroupRow{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRow) ProtoMessage() {}

func (x *GroupRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupRow) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupRow) GetSubject() string {
	if x != nil {
		return x.xxx_hidden_Subject
	}
	return ""
}

func (x *GroupRow) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *GroupRow) GetAvatarPath() string {
	if x != nil {
		return x.xxx_hidden_AvatarPath
	}
	return ""
}

func (x *GroupRow) GetCreatedMs() int64 {
	if x != nil {
		return x.xxx_hidden_CreatedMs
	}
	return 0
}

func (x *GroupRow) GetOwner() *Person {
	if x != nil {
		return x.xxx_hidden_Owner
	}
	return nil
}

func (x *GroupRow) GetMemberCount() uint32 {
	if x != nil {
		return x.xxx_hidden_MemberCount
	}
	return 0
}

func (x *GroupRow) GetMyRole() GroupRole {
	if x != nil {
		return x.xxx_hidden_MyRole
	}
	return GroupRole_GROUP_ROLE_UNSPECIFIED
}

func (x *GroupRow) GetAnnounce() bool {
	if x != nil {
		return x.xxx_hidden_Announce
	}
	return false
}

func (x *GroupRow) GetLocked() bool {
	if x != nil {
		return x.xxx_hidden_Locked
	}
	return false
}

func (x *GroupRow) GetApproval() bool {
	if x != nil {
		return x.xxx_hidden_Approval
	}
	return false
}

func (x *GroupRow) GetCommunityId() string {
	if x != nil {
		return x.xxx_hidden_CommunityId
	}
	return ""
}

func (x *GroupRow) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *GroupRow) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *GroupRow) SetSubject(v string) {
	x.xxx_hidden_Subject = v
}

func (x *GroupRow) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *GroupRow) SetAvatarPath(v string) {
	x.xxx_hidden_AvatarPath = v
}

func (x *GroupRow) SetCreatedMs(v int64) {
	x.xxx_hidden_CreatedMs = v
}

func (x *GroupRow) SetOwner(v *Person) {
	x.xxx_hidden_Owner = v
}

func (x *GroupRow) SetMemberCount(v uint32) {
	x.xxx_hidden_MemberCount = v
}

func (x *GroupRow) SetMyRole(v GroupRole) {
	x.xxx_hidden_MyRole = v
}

func (x *GroupRow) SetAnnounce(v bool) {
	x.xxx_hidden_Announce = v
}

func (x *GroupRow) SetLocked(v bool) {
	x.xxx_hidden_Locked = v
}

func (x *GroupRow) SetApproval(v bool) {
	x.xxx_hidden_Approval = v
}

func (x *GroupRow) SetCommunityId(v string) {
	x.xxx_hidden_CommunityId = v
}

func (x *GroupRow) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *GroupRow) HasOwner() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Owner != nil
}

func (x *GroupRow) ClearOwner() {
	x.xxx_hidden_Owner = nil
}

type GroupRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId      string
	Subject     string
	Description string
	AvatarPath  string
	CreatedMs   int64
	Owner       *Person
	MemberCount uint32
	MyRole      GroupRole
	// only admins send
	Announce bool
	// only admins edit the group's info
	Locked bool
	// joining needs an admin's approval
	Approval bool
	// the community this group belongs to
	CommunityId string
	// why whatsapp wouldn't describe it, empty when it did
	Error string
}

func (b0 GroupRow_builder) Build() *GroupRow {
	m0 := &GroupRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Subject = b.Subject
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_AvatarPath = b.AvatarPath
	x.xxx_hidden_CreatedMs = b.CreatedMs
	x.xxx_hidden_Owner = b.Owner
	x.xxx_hidden_MemberCount = b.MemberCount
	x.xxx_hidden_MyRole = b.MyRole
	x.xxx_hidden_Announce = b.Announce
	x.xxx_hidden_Locked = b.Locked
	x.xxx_hidden_Approval = b.Approval
	x.xxx_hidden_CommunityId = b.CommunityId
	x.xxx_hidden_Error = b.Error
	return m0
}

type GroupMembersView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupMembersView) Reset() {
	*x = GroupMembersView{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersView) ProtoMessage() {}

func (x *GroupMembersView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupMembersView) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *GroupMembersView) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type GroupMembersView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 GroupMembersView_builder) Build() *GroupMembersView {
	m0 := &GroupMembersView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type GroupMemberRow struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person *Person                `protobuf:"bytes,1,opt,name=person"`
	xxx_hidden_Role   GroupRole              `protobuf:"varint,2,opt,name=role,enum=whatevr.v2.GroupRole"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupMemberRow) Reset() {
	*x = GroupMemberRow{}
	mi := &file_whatevr_v2_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberRow) ProtoMessage() {}

func (x *GroupMemberRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupMemberRow) GetPerson() *Person {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *GroupMemberRow) GetRole() GroupRole {
	if x != nil {
		return x.xxx_hidden_Role
	}
	return GroupRole_GROUP_ROLE_UNSPECIFIED
}

func (x *GroupMemberRow) SetPerson(v *Person) {
	x.xxx_hidden_Person = v
}

func (x *GroupMemberRow) SetRole(v GroupRole) {
	x.xxx_hidden_Role = v
}

func (x *GroupMemberRow) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *GroupMemberRow) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type GroupMemberRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person *Person
	Role   GroupRole
}

func (b0 GroupMemberRow_builder) Build() *GroupMemberRow {
	m0 := &GroupMemberRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	x.xxx_hidden_Role = b.Role
	return m0
}

var File_whatevr_v2_groups_proto protoreflect.FileDescriptor

const file_whatevr_v2_groups_proto_rawDesc = "" +
	"\n" +
	"\x17whatevr/v2/groups.proto\x12\n" +
	"whatevr.v2\x1a\x17whatevr/v2/people.proto\"$\n" +
	"\tGroupView\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\xa5\x03\n" +
	"\bGroupRow\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vavatar_path\x18\x04 \x01(\tR\n" +
	"avatarPath\x12\x1d\n" +
	"\n" +
	"created_ms\x18\x05 \x01(\x03R\tcreatedMs\x12(\n" +
	"\x05owner\x18\x06 \x01(\v2\x12.whatevr.v2.PersonR\x05owner\x12!\n" +
	"\fmember_count\x18\a \x01(\rR\vmemberCount\x12.\n" +
	"\amy_role\x18\b \x01(\x0e2\x15.whatevr.v2.GroupRoleR\x06myRole\x12\x1a\n" +
	"\bannounce\x18\t \x01(\bR\bannounce\x12\x16\n" +
	"\x06locked\x18\n" +
	" \x01(\bR\x06locked\x12\x1a\n" +
	"\bapproval\x18\v \x01(\bR\bapproval\x12!\n" +
	"\fcommunity_id\x18\f \x01(\tR\vcommunityId\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\"+\n" +
	"\x10GroupMembersView\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"g\n" +
	"\x0eGroupMemberRow\x12*\n" +
	"\x06person\x18\x01 \x01(\v2\x12.whatevr.v2.PersonR\x06person\x12)\n" +
	"\x04role\x18\x02 \x01(\x0e2\x15.whatevr.v2.GroupRoleR\x04role*\x84\x01\n" +
	"\tGroupRole\x12\x1a\n" +
	"\x16GROUP_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11GROUP_ROLE_MEMBER\x10\x01\x12\x14\n" +
	"\x10GROUP_ROLE_ADMIN\x10\x02\x12\x19\n" +
	"\x15GROUP_ROLE_SUPERADMIN\x10\x03\x12\x13\n" +
	"\x0fGROUP_ROLE_LEFT\x10\x04B\xa0\x01\n" +
	"\x0ecom.whatevr.v2B\vGroupsProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_groups_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whatevr_v2_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_whatevr_v2_groups_proto_goTypes = []any{
	(GroupRole)(0),           // 0: whatevr.v2.GroupRole
	(*GroupView)(nil),        // 1: whatevr.v2.GroupView
	(*GroupRow)(nil),         // 2: whatevr.v2.GroupRow
	(*GroupMembersView)(nil), // 3: whatevr.v2.GroupMembersView
	(*GroupMemberRow)(nil),   // 4: whatevr.v2.GroupMemberRow
	(*Person)(nil),           // 5: whatevr.v2.Person
}
var file_whatevr_v2_groups_proto_depIdxs = []int32{
	5, // 0: whatevr.v2.GroupRow.owner:type_name -> whatevr.v2.Person
	0, // 1: whatevr.v2.GroupRow.my_role:type_name -> whatevr.v2.GroupRole
	5, // 2: whatevr.v2.GroupMemberRow.person:type_name -> whatevr.v2.Person
	0, // 3: whatevr.v2.GroupMemberRow.role:type_name -> whatevr.v2.GroupRole
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_whatevr_v2_groups_proto_init() }
func file_whatevr_v2_groups_proto_init() {
	if File_whatevr_v2_groups_proto != nil {
		return
	}
	file_whatevr_v2_people_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_groups_proto_rawDesc), len(file_whatevr_v2_groups_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_groups_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_groups_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_groups_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_groups_proto_msgTypes,
	}.Build()
	File_whatevr_v2_groups_proto = out.File
	file_whatevr_v2_groups_proto_goTypes = nil
	file_whatevr_v2_groups_proto_depIdxs = nil
}
