// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/media.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferDirection int32

const (
	TransferDirection_TRANSFER_DIRECTION_UNSPECIFIED TransferDirection = 0
	TransferDirection_TRANSFER_DIRECTION_DOWNLOAD    TransferDirection = 1
	TransferDirection_TRANSFER_DIRECTION_UPLOAD      TransferDirection = 2
)

// Enum value maps for TransferDirection.
var (
	TransferDirection_name = map[int32]string{
		0: "TRANSFER_DIRECTION_UNSPECIFIED",
		1: "TRANSFER_DIRECTION_DOWNLOAD",
		2: "TRANSFER_DIRECTION_UPLOAD",
	}
	TransferDirection_value = map[string]int32{
		"TRANSFER_DIRECTION_UNSPECIFIED": 0,
		"TRANSFER_DIRECTION_DOWNLOAD":    1,
		"TRANSFER_DIRECTION_UPLOAD":      2,
	}
)

func (x TransferDirection) Enum() *TransferDirection {
	p := new(TransferDirection)
	*p = x
	return p
}

func (x TransferDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_media_proto_enumTypes[0].Descriptor()
}

func (TransferDirection) Type() protoreflect.EnumType {
	return &file_whatevr_v2_media_proto_enumTypes[0]
}

func (x TransferDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MediaStreamState int32

const (
	MediaStreamState_MEDIA_STREAM_STATE_UNSPECIFIED MediaStreamState = 0
	// fell back to a whole download; play path instead
	MediaStreamState_MEDIA_STREAM_STATE_LOCAL  MediaStreamState = 1
	MediaStreamState_MEDIA_STREAM_STATE_FAILED MediaStreamState = 2
)

// Enum value maps for MediaStreamState.
var (
	MediaStreamState_name = map[int32]string{
		0: "MEDIA_STREAM_STATE_UNSPECIFIED",
		1: "MEDIA_STREAM_STATE_LOCAL",
		2: "MEDIA_STREAM_STATE_FAILED",
	}
	MediaStreamState_value = map[string]int32{
		"MEDIA_STREAM_STATE_UNSPECIFIED": 0,
		"MEDIA_STREAM_STATE_LOCAL":       1,
		"MEDIA_STREAM_STATE_FAILED":      2,
	}
)

func (x MediaStreamState) Enum() *MediaStreamState {
	p := new(MediaStreamState)
	*p = x
	return p
}

func (x MediaStreamState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaStreamState) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_media_proto_enumTypes[1].Descriptor()
}

func (MediaStreamState) Type() protoreflect.EnumType {
	return &file_whatevr_v2_media_proto_enumTypes[1]
}

func (x MediaStreamState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// in-flight transfers and their byte counts; removed when one ends
type TransfersView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransfersView) Reset() {
	*x = TransfersView{}
	mi := &file_whatevr_v2_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransfersView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransfersView) ProtoMessage() {}

func (x *TransfersView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TransfersView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TransfersView_builder) Build() *TransfersView {
	m0 := &TransfersView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TransferRow struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageId  string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId"`
	xxx_hidden_ChatId     string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId"`
	xxx_hidden_Direction  TransferDirection      `protobuf:"varint,3,opt,name=direction,enum=whatevr.v2.TransferDirection"`
	xxx_hidden_DoneBytes  uint64                 `protobuf:"varint,4,opt,name=done_bytes,json=doneBytes"`
	xxx_hidden_TotalBytes uint64                 `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes"`
	xxx_hidden_Error      string                 `protobuf:"bytes,6,opt,name=error"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TransferRow) Reset() {
	*x = TransferRow{}
	mi := &file_whatevr_v2_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRow) ProtoMessage() {}

func (x *TransferRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TransferRow) GetMessageId() string {
	if x != nil {
		return x.xxx_hidden_MessageId
	}
	return ""
}

func (x *TransferRow) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *TransferRow) GetDirection() TransferDirection {
	if x != nil {
		return x.xxx_hidden_Direction
	}
	return TransferDirection_TRANSFER_DIRECTION_UNSPECIFIED
}

func (x *TransferRow) GetDoneBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_DoneBytes
	}
	return 0
}

func (x *TransferRow) GetTotalBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_TotalBytes
	}
	return 0
}

func (x *TransferRow) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *TransferRow) SetMessageId(v string) {
	x.xxx_hidden_MessageId = v
}

func (x *TransferRow) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *TransferRow) SetDirection(v TransferDirection) {
	x.xxx_hidden_Direction = v
}

func (x *TransferRow) SetDoneBytes(v uint64) {
	x.xxx_hidden_DoneBytes = v
}

func (x *TransferRow) SetTotalBytes(v uint64) {
	x.xxx_hidden_TotalBytes = v
}

func (x *TransferRow) SetError(v string) {
	x.xxx_hidden_Error = v
}

type TransferRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageId  string
	ChatId     string
	Direction  TransferDirection
	DoneBytes  uint64
	TotalBytes uint64
	// an error the transfer is retrying through
	Error string
}

func (b0 TransferRow_builder) Build() *TransferRow {
	m0 := &TransferRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MessageId = b.MessageId
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Direction = b.Direction
	x.xxx_hidden_DoneBytes = b.DoneBytes
	x.xxx_hidden_TotalBytes = b.TotalBytes
	x.xxx_hidden_Error = b.Error
	return m0
}

// progress in transfers, the path lands on the message row
type MediaDownload struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaDownload) Reset() {
	*x = MediaDownload{}
	mi := &file_whatevr_v2_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaDownload) ProtoMessage() {}

func (x *MediaDownload) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaDownload) GetMessageId() string {
	if x != nil {
		return x.xxx_hidden_MessageId
	}
	return ""
}

func (x *MediaDownload) SetMessageId(v string) {
	x.xxx_hidden_MessageId = v
}

type MediaDownload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageId string
}

func (b0 MediaDownload_builder) Build() *MediaDownload {
	m0 := &MediaDownload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MessageId = b.MessageId
	return m0
}

// a loopback http range url a player can open before the download ends
type MediaStream struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaStream) Reset() {
	*x = MediaStream{}
	mi := &file_whatevr_v2_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStream) ProtoMessage() {}

func (x *MediaStream) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaStream) GetMessageId() string {
	if x != nil {
		return x.xxx_hidden_MessageId
	}
	return ""
}

func (x *MediaStream) SetMessageId(v string) {
	x.xxx_hidden_MessageId = v
}

type MediaStream_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageId string
}

func (b0 MediaStream_builder) Build() *MediaStream {
	m0 := &MediaStream{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MessageId = b.MessageId
	return m0
}

type MediaStreamResult struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StreamId   string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId"`
	xxx_hidden_Url        string                 `protobuf:"bytes,2,opt,name=url"`
	xxx_hidden_Mime       string                 `protobuf:"bytes,3,opt,name=mime"`
	xxx_hidden_SizeBytes  uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes"`
	xxx_hidden_DurationMs int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MediaStreamResult) Reset() {
	*x = MediaStreamResult{}
	mi := &file_whatevr_v2_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStreamResult) ProtoMessage() {}

func (x *MediaStreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaStreamResult) GetStreamId() string {
	if x != nil {
		return x.xxx_hidden_StreamId
	}
	return ""
}

func (x *MediaStreamResult) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *MediaStreamResult) GetMime() string {
	if x != nil {
		return x.xxx_hidden_Mime
	}
	return ""
}

func (x *MediaStreamResult) GetSizeBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *MediaStreamResult) GetDurationMs() int64 {
	if x != nil {
		return x.xxx_hidden_DurationMs
	}
	return 0
}

func (x *MediaStreamResult) SetStreamId(v string) {
	x.xxx_hidden_StreamId = v
}

func (x *MediaStreamResult) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

func (x *MediaStreamResult) SetMime(v string) {
	x.xxx_hidden_Mime = v
}

func (x *MediaStreamResult) SetSizeBytes(v uint64) {
	x.xxx_hidden_SizeBytes = v
}

func (x *MediaStreamResult) SetDurationMs(v int64) {
	x.xxx_hidden_DurationMs = v
}

type MediaStreamResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	StreamId   string
	Url        string
	Mime       string
	SizeBytes  uint64
	DurationMs int64
}

func (b0 MediaStreamResult_builder) Build() *MediaStreamResult {
	m0 := &MediaStreamResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StreamId = b.StreamId
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Mime = b.Mime
	x.xxx_hidden_SizeBytes = b.SizeBytes
	x.xxx_hidden_DurationMs = b.DurationMs
	return m0
}

// sent once, to the connection that asked, when a stream fails late
type MediaStreamUpdate struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StreamId  string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId"`
	xxx_hidden_MessageId string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId"`
	xxx_hidden_State     MediaStreamState       `protobuf:"varint,3,opt,name=state,enum=whatevr.v2.MediaStreamState"`
	xxx_hidden_Path      string                 `protobuf:"bytes,4,opt,name=path"`
	xxx_hidden_Error     string                 `protobuf:"bytes,5,opt,name=error"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaStreamUpdate) Reset() {
	*x = MediaStreamUpdate{}
	mi := &file_whatevr_v2_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStreamUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStreamUpdate) ProtoMessage() {}

func (x *MediaStreamUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaStreamUpdate) GetStreamId() string {
	if x != nil {
		return x.xxx_hidden_StreamId
	}
	return ""
}

func (x *MediaStreamUpdate) GetMessageId() string {
	if x != nil {
		return x.xxx_hidden_MessageId
	}
	return ""
}

func (x *MediaStreamUpdate) GetState() MediaStreamState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return MediaStreamState_MEDIA_STREAM_STATE_UNSPECIFIED
}

func (x *MediaStreamUpdate) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *MediaStreamUpdate) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *MediaStreamUpdate) SetStreamId(v string) {
	x.xxx_hidden_StreamId = v
}

func (x *MediaStreamUpdate) SetMessageId(v string) {
	x.xxx_hidden_MessageId = v
}

func (x *MediaStreamUpdate) SetState(v MediaStreamState) {
	x.xxx_hidden_State = v
}

func (x *MediaStreamUpdate) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *MediaStreamUpdate) SetError(v string) {
	x.xxx_hidden_Error = v
}

type MediaStreamUpdate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	StreamId  string
	MessageId string
	State     MediaStreamState
	// the whole file, for MEDIA_STREAM_STATE_LOCAL
	Path  string
	Error string
}

func (b0 MediaStreamUpdate_builder) Build() *MediaStreamUpdate {
	m0 := &MediaStreamUpdate{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StreamId = b.StreamId
	x.xxx_hidden_MessageId = b.MessageId
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Error = b.Error
	return m0
}

// stops a download or stream; what landed is kept for a resume
type MediaCancelDownload struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaCancelDownload) Reset() {
	*x = MediaCancelDownload{}
	mi := &file_whatevr_v2_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaCancelDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaCancelDownload) ProtoMessage() {}

func (x *MediaCancelDownload) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaCancelDownload) GetMessageId() string {
	if x != nil {
		return x.xxx_hidden_MessageId
	}
	return ""
}

func (x *MediaCancelDownload) SetMessageId(v string) {
	x.xxx_hidden_MessageId = v
}

type MediaCancelDownload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageId string
}

func (b0 MediaCancelDownload_builder) Build() *MediaCancelDownload {
	m0 := &MediaCancelDownload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MessageId = b.MessageId
	return m0
}

// a file's bytes over the socket, for a frontend that can't open the path.
// one chunk per request; ask again at offset + len(data) until eof
type MediaRead struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path     string                 `protobuf:"bytes,1,opt,name=path"`
	xxx_hidden_Offset   uint64                 `protobuf:"varint,2,opt,name=offset"`
	xxx_hidden_MaxBytes uint32                 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MediaRead) Reset() {
	*x = MediaRead{}
	mi := &file_whatevr_v2_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRead) ProtoMessage() {}

func (x *MediaRead) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaRead) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *MediaRead) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *MediaRead) GetMaxBytes() uint32 {
	if x != nil {
		return x.xxx_hidden_MaxBytes
	}
	return 0
}

func (x *MediaRead) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *MediaRead) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
}

func (x *MediaRead) SetMaxBytes(v uint32) {
	x.xxx_hidden_MaxBytes = v
}

type MediaRead_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// any path the daemon put on a row
	Path   string
	Offset uint64
	// 0 for the daemon's chunk size; capped by the daemon
	MaxBytes uint32
}

func (b0 MediaRead_builder) Build() *MediaRead {
	m0 := &MediaRead{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_MaxBytes = b.MaxBytes
	return m0
}

type MediaReadResult struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data      []byte                 `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_SizeBytes uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes"`
	xxx_hidden_Eof       bool                   `protobuf:"varint,3,opt,name=eof"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaReadResult) Reset() {
	*x = MediaReadResult{}
	mi := &file_whatevr_v2_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaReadResult) ProtoMessage() {}

func (x *MediaReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaReadResult) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *MediaReadResult) GetSizeBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *MediaReadResult) GetEof() bool {
	if x != nil {
		return x.xxx_hidden_Eof
	}
	return false
}

func (x *MediaReadResult) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *MediaReadResult) SetSizeBytes(v uint64) {
	x.xxx_hidden_SizeBytes = v
}

func (x *MediaReadResult) SetEof(v bool) {
	x.xxx_hidden_Eof = v
}

type MediaReadResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data      []byte
	SizeBytes uint64
	Eof       bool
}

func (b0 MediaReadResult_builder) Build() *MediaReadResult {
	m0 := &MediaReadResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_SizeBytes = b.SizeBytes
	x.xxx_hidden_Eof = b.Eof
	return m0
}

// full resolution, for an avatar viewer
type MediaFetchProfilePicture struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person *Address               `protobuf:"bytes,1,opt,name=person"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MediaFetchProfilePicture) Reset() {
	*x = MediaFetchProfilePicture{}
	mi := &file_whatevr_v2_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaFetchProfilePicture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFetchProfilePicture) ProtoMessage() {}

func (x *MediaFetchProfilePicture) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaFetchProfilePicture) GetPerson() *Address {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *MediaFetchProfilePicture) SetPerson(v *Address) {
	x.xxx_hidden_Person = v
}

func (x *MediaFetchProfilePicture) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *MediaFetchProfilePicture) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type MediaFetchProfilePicture_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person *Address
}

func (b0 MediaFetchProfilePicture_builder) Build() *MediaFetchProfilePicture {
	m0 := &MediaFetchProfilePicture{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	return m0
}

type MediaFetchProfilePictureResult struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path string                 `protobuf:"bytes,1,opt,name=path"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaFetchProfilePictureResult) Reset() {
	*x = MediaFetchProfilePictureResult{}
	mi := &file_whatevr_v2_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaFetchProfilePictureResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFetchProfilePictureResult) ProtoMessage() {}

func (x *MediaFetchProfilePictureResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaFetchProfilePictureResult) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *MediaFetchProfilePictureResult) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type MediaFetchProfilePictureResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path string
}

func (b0 MediaFetchProfilePictureResult_builder) Build() *MediaFetchProfilePictureResult {
	m0 := &MediaFetchProfilePictureResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	return m0
}

// copies media out of the daemon cache to a caller-owned path. exactly one
// of message_id (a chat message) or jid (a profile picture) selects the
// source; status_id arrives with the status views
type MediaSave struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId"`
	xxx_hidden_StatusId  string                 `protobuf:"bytes,2,opt,name=status_id,json=statusId"`
	xxx_hidden_Jid       string                 `protobuf:"bytes,3,opt,name=jid"`
	xxx_hidden_Path      string                 `protobuf:"bytes,4,opt,name=path"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaSave) Reset() {
	*x = MediaSave{}
	mi := &file_whatevr_v2_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSave) ProtoMessage() {}

func (x *MediaSave) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaSave) GetMessageId() string {
	if x != nil {
		return x.xxx_hidden_MessageId
	}
	return ""
}

func (x *MediaSave) GetStatusId() string {
	if x != nil {
		return x.xxx_hidden_StatusId
	}
	return ""
}

func (x *MediaSave) GetJid() string {
	if x != nil {
		return x.xxx_hidden_Jid
	}
	return ""
}

func (x *MediaSave) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *MediaSave) SetMessageId(v string) {
	x.xxx_hidden_MessageId = v
}

func (x *MediaSave) SetStatusId(v string) {
	x.xxx_hidden_StatusId = v
}

func (x *MediaSave) SetJid(v string) {
	x.xxx_hidden_Jid = v
}

func (x *MediaSave) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type MediaSave_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageId string
	StatusId  string
	Jid       string
	Path      string
}

func (b0 MediaSave_builder) Build() *MediaSave {
	m0 := &MediaSave{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MessageId = b.MessageId
	x.xxx_hidden_StatusId = b.StatusId
	x.xxx_hidden_Jid = b.Jid
	x.xxx_hidden_Path = b.Path
	return m0
}

type MediaSaveResult struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path string                 `protobuf:"bytes,1,opt,name=path"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaSaveResult) Reset() {
	*x = MediaSaveResult{}
	mi := &file_whatevr_v2_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSaveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSaveResult) ProtoMessage() {}

func (x *MediaSaveResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaSaveResult) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *MediaSaveResult) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type MediaSaveResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path string
}

func (b0 MediaSaveResult_builder) Build() *MediaSaveResult {
	m0 := &MediaSaveResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	return m0
}

var File_whatevr_v2_media_proto protoreflect.FileDescriptor

const file_whatevr_v2_media_proto_rawDesc = "" +
	"\n" +
	"\x16whatevr/v2/media.proto\x12\n" +
	"whatevr.v2\x1a\x17whatevr/v2/people.proto\"\x0f\n" +
	"\rTransfersView\"\xd8\x01\n" +
	"\vTransferRow\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12;\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x1d.whatevr.v2.TransferDirectionR\tdirection\x12\x1d\n" +
	"\n" +
	"done_bytes\x18\x04 \x01(\x04R\tdoneBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x04R\n" +
	"totalBytes\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\".\n" +
	"\rMediaDownload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\",\n" +
	"\vMediaStream\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x96\x01\n" +
	"\x11MediaStreamResult\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"\xad\x01\n" +
	"\x11MediaStreamUpdate\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.whatevr.v2.MediaStreamStateR\x05state\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"4\n" +
	"\x13MediaCancelDownload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"T\n" +
	"\tMediaRead\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\rR\bmaxBytes\"V\n" +
	"\x0fMediaReadResult\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"G\n" +
	"\x18MediaFetchProfilePicture\x12+\n" +
	"\x06person\x18\x01 \x01(\v2\x13.whatevr.v2.AddressR\x06person\"4\n" +
	"\x1eMediaFetchProfilePictureResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"m\n" +
	"\tMediaSave\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tstatus_id\x18\x02 \x01(\tR\bstatusId\x12\x10\n" +
	"\x03jid\x18\x03 \x01(\tR\x03jid\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"%\n" +
	"\x0fMediaSaveResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path*w\n" +
	"\x11TransferDirection\x12\"\n" +
	"\x1eTRANSFER_DIRECTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRANSFER_DIRECTION_DOWNLOAD\x10\x01\x12\x1d\n" +
	"\x19TRANSFER_DIRECTION_UPLOAD\x10\x02*s\n" +
	"\x10MediaStreamState\x12\"\n" +
	"\x1eMEDIA_STREAM_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MEDIA_STREAM_STATE_LOCAL\x10\x01\x12\x1d\n" +
	"\x19MEDIA_STREAM_STATE_FAILED\x10\x02B\x9f\x01\n" +
	"\x0ecom.whatevr.v2B\n" +
	"MediaProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_media_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_whatevr_v2_media_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_whatevr_v2_media_proto_goTypes = []any{
	(TransferDirection)(0),                 // 0: whatevr.v2.TransferDirection
	(MediaStreamState)(0),                  // 1: whatevr.v2.MediaStreamState
	(*TransfersView)(nil),                  // 2: whatevr.v2.TransfersView
	(*TransferRow)(nil),                    // 3: whatevr.v2.TransferRow
	(*MediaDownload)(nil),                  // 4: whatevr.v2.MediaDownload
	(*MediaStream)(nil),                    // 5: whatevr.v2.MediaStream
	(*MediaStreamResult)(nil),              // 6: whatevr.v2.MediaStreamResult
	(*MediaStreamUpdate)(nil),              // 7: whatevr.v2.MediaStreamUpdate
	(*MediaCancelDownload)(nil),            // 8: whatevr.v2.MediaCancelDownload
	(*MediaRead)(nil),                      // 9: whatevr.v2.MediaRead
	(*MediaReadResult)(nil),                // 10: whatevr.v2.MediaReadResult
	(*MediaFetchProfilePicture)(nil),       // 11: whatevr.v2.MediaFetchProfilePicture
	(*MediaFetchProfilePictureResult)(nil), // 12: whatevr.v2.MediaFetchProfilePictureResult
	(*MediaSave)(nil),                      // 13: whatevr.v2.MediaSave
	(*MediaSaveResult)(nil),                // 14: whatevr.v2.MediaSaveResult
	(*Address)(nil),                        // 15: whatevr.v2.Address
}
var file_whatevr_v2_media_proto_depIdxs = []int32{
	0,  // 0: whatevr.v2.TransferRow.direction:type_name -> whatevr.v2.TransferDirection
	1,  // 1: whatevr.v2.MediaStreamUpdate.state:type_name -> whatevr.v2.MediaStreamState
	15, // 2: whatevr.v2.MediaFetchProfilePicture.person:type_name -> whatevr.v2.Address
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_whatevr_v2_media_proto_init() }
func file_whatevr_v2_media_proto_init() {
	if File_whatevr_v2_media_proto != nil {
		return
	}
	file_whatevr_v2_people_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_media_proto_rawDesc), len(file_whatevr_v2_media_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_media_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_media_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_media_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_media_proto_msgTypes,
	}.Build()
	File_whatevr_v2_media_proto = out.File
	file_whatevr_v2_media_proto_goTypes = nil
	file_whatevr_v2_media_proto_depIdxs = nil
}
