// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/notifications.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// what the daemon thinks deserves a notification now; one item each,
// removed when read or dismissed anywhere
type NotificationsView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationsView) Reset() {
	*x = NotificationsView{}
	mi := &file_whatevr_v2_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationsView) ProtoMessage() {}

func (x *NotificationsView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type NotificationsView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 NotificationsView_builder) Build() *NotificationsView {
	m0 := &NotificationsView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type NotificationRow struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id         string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_ChatId     string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId"`
	xxx_hidden_MessageId  string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId"`
	xxx_hidden_Title      string                 `protobuf:"bytes,4,opt,name=title"`
	xxx_hidden_Body       string                 `protobuf:"bytes,5,opt,name=body"`
	xxx_hidden_Sender     *Person                `protobuf:"bytes,6,opt,name=sender"`
	xxx_hidden_AvatarPath string                 `protobuf:"bytes,7,opt,name=avatar_path,json=avatarPath"`
	xxx_hidden_Count      uint32                 `protobuf:"varint,8,opt,name=count"`
	xxx_hidden_TMs        int64                  `protobuf:"varint,9,opt,name=t_ms,json=tMs"`
	xxx_hidden_Sound      bool                   `protobuf:"varint,10,opt,name=sound"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NotificationRow) Reset() {
	*x = NotificationRow{}
	mi := &file_whatevr_v2_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRow) ProtoMessage() {}

func (x *NotificationRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NotificationRow) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *NotificationRow) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *NotificationRow) GetMessageId() string {
	if x != nil {
		return x.xxx_hidden_MessageId
	}
	return ""
}

func (x *NotificationRow) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *NotificationRow) GetBody() string {
	if x != nil {
		return x.xxx_hidden_Body
	}
	return ""
}

func (x *NotificationRow) GetSender() *Person {
	if x != nil {
		return x.xxx_hidden_Sender
	}
	return nil
}

func (x *NotificationRow) GetAvatarPath() string {
	if x != nil {
		return x.xxx_hidden_AvatarPath
	}
	return ""
}

func (x *NotificationRow) GetCount() uint32 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *NotificationRow) GetTMs() int64 {
	if x != nil {
		return x.xxx_hidden_TMs
	}
	return 0
}

func (x *NotificationRow) GetSound() bool {
	if x != nil {
		return x.xxx_hidden_Sound
	}
	return false
}

func (x *NotificationRow) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *NotificationRow) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *NotificationRow) SetMessageId(v string) {
	x.xxx_hidden_MessageId = v
}

func (x *NotificationRow) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *NotificationRow) SetBody(v string) {
	x.xxx_hidden_Body = v
}

func (x *NotificationRow) SetSender(v *Person) {
	x.xxx_hidden_Sender = v
}

func (x *NotificationRow) SetAvatarPath(v string) {
	x.xxx_hidden_AvatarPath = v
}

func (x *NotificationRow) SetCount(v uint32) {
	x.xxx_hidden_Count = v
}

func (x *NotificationRow) SetTMs(v int64) {
	x.xxx_hidden_TMs = v
}

func (x *NotificationRow) SetSound(v bool) {
	x.xxx_hidden_Sound = v
}

func (x *NotificationRow) HasSender() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sender != nil
}

func (x *NotificationRow) ClearSender() {
	x.xxx_hidden_Sender = nil
}

type NotificationRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     string
	ChatId string
	// the newest message it covers
	MessageId string
	// the chat's name
	Title string
	// empty when preferences hide previews
	Body       string
	Sender     *Person
	AvatarPath string
	// how many messages it stands for
	Count uint32
	TMs   int64
	// play a sound for it
	Sound bool
}

func (b0 NotificationRow_builder) Build() *NotificationRow {
	m0 := &NotificationRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_MessageId = b.MessageId
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Body = b.Body
	x.xxx_hidden_Sender = b.Sender
	x.xxx_hidden_AvatarPath = b.AvatarPath
	x.xxx_hidden_Count = b.Count
	x.xxx_hidden_TMs = b.TMs
	x.xxx_hidden_Sound = b.Sound
	return m0
}

type NotificationDismiss struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationDismiss) Reset() {
	*x = NotificationDismiss{}
	mi := &file_whatevr_v2_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationDismiss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationDismiss) ProtoMessage() {}

func (x *NotificationDismiss) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NotificationDismiss) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *NotificationDismiss) SetId(v string) {
	x.xxx_hidden_Id = v
}

type NotificationDismiss_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 NotificationDismiss_builder) Build() *NotificationDismiss {
	m0 := &NotificationDismiss{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

var File_whatevr_v2_notifications_proto protoreflect.FileDescriptor

const file_whatevr_v2_notifications_proto_rawDesc = "" +
	"\n" +
	"\x1ewhatevr/v2/notifications.proto\x12\n" +
	"whatevr.v2\x1a\x17whatevr/v2/people.proto\"\x13\n" +
	"\x11NotificationsView\"\x8f\x02\n" +
	"\x0fNotificationRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12*\n" +
	"\x06sender\x18\x06 \x01(\v2\x12.whatevr.v2.PersonR\x06sender\x12\x1f\n" +
	"\vavatar_path\x18\a \x01(\tR\n" +
	"avatarPath\x12\x14\n" +
	"\x05count\x18\b \x01(\rR\x05count\x12\x11\n" +
	"\x04t_ms\x18\t \x01(\x03R\x03tMs\x12\x14\n" +
	"\x05sound\x18\n" +
	" \x01(\bR\x05sound\"%\n" +
	"\x13NotificationDismiss\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\xa7\x01\n" +
	"\x0ecom.whatevr.v2B\x12NotificationsProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_whatevr_v2_notifications_proto_goTypes = []any{
	(*NotificationsView)(nil),   // 0: whatevr.v2.NotificationsView
	(*NotificationRow)(nil),     // 1: whatevr.v2.NotificationRow
	(*NotificationDismiss)(nil), // 2: whatevr.v2.NotificationDismiss
	(*Person)(nil),              // 3: whatevr.v2.Person
}
var file_whatevr_v2_notifications_proto_depIdxs = []int32{
	3, // 0: whatevr.v2.NotificationRow.sender:type_name -> whatevr.v2.Person
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_whatevr_v2_notifications_proto_init() }
func file_whatevr_v2_notifications_proto_init() {
	if File_whatevr_v2_notifications_proto != nil {
		return
	}
	file_whatevr_v2_people_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_notifications_proto_rawDesc), len(file_whatevr_v2_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_notifications_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_notifications_proto_depIdxs,
		MessageInfos:      file_whatevr_v2_notifications_proto_msgTypes,
	}.Build()
	File_whatevr_v2_notifications_proto = out.File
	file_whatevr_v2_notifications_proto_goTypes = nil
	file_whatevr_v2_notifications_proto_depIdxs = nil
}
