// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/people.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Availability int32

const (
	Availability_AVAILABILITY_UNSPECIFIED Availability = 0
	Availability_AVAILABILITY_ONLINE      Availability = 1
	Availability_AVAILABILITY_OFFLINE     Availability = 2
)

// Enum value maps for Availability.
var (
	Availability_name = map[int32]string{
		0: "AVAILABILITY_UNSPECIFIED",
		1: "AVAILABILITY_ONLINE",
		2: "AVAILABILITY_OFFLINE",
	}
	Availability_value = map[string]int32{
		"AVAILABILITY_UNSPECIFIED": 0,
		"AVAILABILITY_ONLINE":      1,
		"AVAILABILITY_OFFLINE":     2,
	}
)

func (x Availability) Enum() *Availability {
	p := new(Availability)
	*p = x
	return p
}

func (x Availability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Availability) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_people_proto_enumTypes[0].Descriptor()
}

func (Availability) Type() protoreflect.EnumType {
	return &file_whatevr_v2_people_proto_enumTypes[0]
}

func (x Availability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// whoever a command is about, in whatever form the frontend has
type Address struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address isAddress_Address      `protobuf_oneof:"address"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_whatevr_v2_people_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Address) GetId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Address.(*address_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *Address) GetPhone() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Address.(*address_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *Address) GetLid() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Address.(*address_Lid); ok {
			return x.Lid
		}
	}
	return ""
}

func (x *Address) GetUsername() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Address.(*address_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *Address) SetId(v string) {
	x.xxx_hidden_Address = &address_Id{v}
}

func (x *Address) SetPhone(v string) {
	x.xxx_hidden_Address = &address_Phone{v}
}

func (x *Address) SetLid(v string) {
	x.xxx_hidden_Address = &address_Lid{v}
}

func (x *Address) SetUsername(v string) {
	x.xxx_hidden_Address = &address_Username{v}
}

func (x *Address) HasAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Address != nil
}

func (x *Address) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Address.(*address_Id)
	return ok
}

func (x *Address) HasPhone() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Address.(*address_Phone)
	return ok
}

func (x *Address) HasLid() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Address.(*address_Lid)
	return ok
}

func (x *Address) HasUsername() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Address.(*address_Username)
	return ok
}

func (x *Address) ClearAddress() {
	x.xxx_hidden_Address = nil
}

func (x *Address) ClearId() {
	if _, ok := x.xxx_hidden_Address.(*address_Id); ok {
		x.xxx_hidden_Address = nil
	}
}

func (x *Address) ClearPhone() {
	if _, ok := x.xxx_hidden_Address.(*address_Phone); ok {
		x.xxx_hidden_Address = nil
	}
}

func (x *Address) ClearLid() {
	if _, ok := x.xxx_hidden_Address.(*address_Lid); ok {
		x.xxx_hidden_Address = nil
	}
}

func (x *Address) ClearUsername() {
	if _, ok := x.xxx_hidden_Address.(*address_Username); ok {
		x.xxx_hidden_Address = nil
	}
}

const Address_Address_not_set_case case_Address_Address = 0
const Address_Id_case case_Address_Address = 1
const Address_Phone_case case_Address_Address = 2
const Address_Lid_case case_Address_Address = 3
const Address_Username_case case_Address_Address = 4

func (x *Address) WhichAddress() case_Address_Address {
	if x == nil {
		return Address_Address_not_set_case
	}
	switch x.xxx_hidden_Address.(type) {
	case *address_Id:
		return Address_Id_case
	case *address_Phone:
		return Address_Phone_case
	case *address_Lid:
		return Address_Lid_case
	case *address_Username:
		return Address_Username_case
	default:
		return Address_Address_not_set_case
	}
}

type Address_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Address:
	// a person or chat id from a row
	Id *string
	// digits with or without +, spaces and dashes are fine
	Phone    *string
	Lid      *string
	Username *string
	// -- end of xxx_hidden_Address
}

func (b0 Address_builder) Build() *Address {
	m0 := &Address{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Address = &address_Id{*b.Id}
	}
	if b.Phone != nil {
		x.xxx_hidden_Address = &address_Phone{*b.Phone}
	}
	if b.Lid != nil {
		x.xxx_hidden_Address = &address_Lid{*b.Lid}
	}
	if b.Username != nil {
		x.xxx_hidden_Address = &address_Username{*b.Username}
	}
	return m0
}

type case_Address_Address protoreflect.FieldNumber

func (x case_Address_Address) String() string {
	md := file_whatevr_v2_people_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAddress_Address interface {
	isAddress_Address()
}

type address_Id struct {
	// a person or chat id from a row
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}

type address_Phone struct {
	// digits with or without +, spaces and dashes are fine
	Phone string `protobuf:"bytes,2,opt,name=phone,oneof"`
}

type address_Lid struct {
	Lid string `protobuf:"bytes,3,opt,name=lid,oneof"`
}

type address_Username struct {
	Username string `protobuf:"bytes,4,opt,name=username,oneof"`
}

func (*address_Id) isAddress_Address() {}

func (*address_Phone) isAddress_Address() {}

func (*address_Lid) isAddress_Address() {}

func (*address_Username) isAddress_Address() {}

// a person as a row shows them
type Person struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id         string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name       string                 `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Phone      string                 `protobuf:"bytes,3,opt,name=phone"`
	xxx_hidden_AvatarPath string                 `protobuf:"bytes,4,opt,name=avatar_path,json=avatarPath"`
	xxx_hidden_Self       bool                   `protobuf:"varint,5,opt,name=self"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_whatevr_v2_people_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Person) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Person) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Person) GetPhone() string {
	if x != nil {
		return x.xxx_hidden_Phone
	}
	return ""
}

func (x *Person) GetAvatarPath() string {
	if x != nil {
		return x.xxx_hidden_AvatarPath
	}
	return ""
}

func (x *Person) GetSelf() bool {
	if x != nil {
		return x.xxx_hidden_Self
	}
	return false
}

func (x *Person) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Person) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Person) SetPhone(v string) {
	x.xxx_hidden_Phone = v
}

func (x *Person) SetAvatarPath(v string) {
	x.xxx_hidden_AvatarPath = v
}

func (x *Person) SetSelf(v bool) {
	x.xxx_hidden_Self = v
}

type Person_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
	// e164 without +, empty when the daemon doesn't know it
	Phone      string
	AvatarPath string
	Self       bool
}

func (b0 Person_builder) Build() *Person {
	m0 := &Person{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Phone = b.Phone
	x.xxx_hidden_AvatarPath = b.AvatarPath
	x.xxx_hidden_Self = b.Self
	return m0
}

// the account this daemon is logged in as
type SelfView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfView) Reset() {
	*x = SelfView{}
	mi := &file_whatevr_v2_people_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfView) ProtoMessage() {}

func (x *SelfView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SelfView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SelfView_builder) Build() *SelfView {
	m0 := &SelfView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SelfRow struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id         string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Phone      string                 `protobuf:"bytes,2,opt,name=phone"`
	xxx_hidden_PushName   string                 `protobuf:"bytes,3,opt,name=push_name,json=pushName"`
	xxx_hidden_About      string                 `protobuf:"bytes,4,opt,name=about"`
	xxx_hidden_AvatarPath string                 `protobuf:"bytes,5,opt,name=avatar_path,json=avatarPath"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SelfRow) Reset() {
	*x = SelfRow{}
	mi := &file_whatevr_v2_people_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfRow) ProtoMessage() {}

func (x *SelfRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SelfRow) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *SelfRow) GetPhone() string {
	if x != nil {
		return x.xxx_hidden_Phone
	}
	return ""
}

func (x *SelfRow) GetPushName() string {
	if x != nil {
		return x.xxx_hidden_PushName
	}
	return ""
}

func (x *SelfRow) GetAbout() string {
	if x != nil {
		return x.xxx_hidden_About
	}
	return ""
}

func (x *SelfRow) GetAvatarPath() string {
	if x != nil {
		return x.xxx_hidden_AvatarPath
	}
	return ""
}

func (x *SelfRow) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *SelfRow) SetPhone(v string) {
	x.xxx_hidden_Phone = v
}

func (x *SelfRow) SetPushName(v string) {
	x.xxx_hidden_PushName = v
}

func (x *SelfRow) SetAbout(v string) {
	x.xxx_hidden_About = v
}

func (x *SelfRow) SetAvatarPath(v string) {
	x.xxx_hidden_AvatarPath = v
}

type SelfRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         string
	Phone      string
	PushName   string
	About      string
	AvatarPath string
}

func (b0 SelfRow_builder) Build() *SelfRow {
	m0 := &SelfRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Phone = b.Phone
	x.xxx_hidden_PushName = b.PushName
	x.xxx_hidden_About = b.About
	x.xxx_hidden_AvatarPath = b.AvatarPath
	return m0
}

// one contact card; local facts land first, about lands when fetched
type ContactView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person *Address               `protobuf:"bytes,1,opt,name=person"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContactView) Reset() {
	*x = ContactView{}
	mi := &file_whatevr_v2_people_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactView) ProtoMessage() {}

func (x *ContactView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContactView) GetPerson() *Address {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *ContactView) SetPerson(v *Address) {
	x.xxx_hidden_Person = v
}

func (x *ContactView) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *ContactView) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type ContactView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person *Address
}

func (b0 ContactView_builder) Build() *ContactView {
	m0 := &ContactView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	return m0
}

type ContactRow struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Phone        string                 `protobuf:"bytes,2,opt,name=phone"`
	xxx_hidden_SavedName    string                 `protobuf:"bytes,3,opt,name=saved_name,json=savedName"`
	xxx_hidden_PushName     string                 `protobuf:"bytes,4,opt,name=push_name,json=pushName"`
	xxx_hidden_BusinessName string                 `protobuf:"bytes,5,opt,name=business_name,json=businessName"`
	xxx_hidden_Business     bool                   `protobuf:"varint,6,opt,name=business"`
	xxx_hidden_About        string                 `protobuf:"bytes,7,opt,name=about"`
	xxx_hidden_AvatarPath   string                 `protobuf:"bytes,8,opt,name=avatar_path,json=avatarPath"`
	xxx_hidden_Blocked      bool                   `protobuf:"varint,9,opt,name=blocked"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContactRow) Reset() {
	*x = ContactRow{}
	mi := &file_whatevr_v2_people_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRow) ProtoMessage() {}

func (x *ContactRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContactRow) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ContactRow) GetPhone() string {
	if x != nil {
		return x.xxx_hidden_Phone
	}
	return ""
}

func (x *ContactRow) GetSavedName() string {
	if x != nil {
		return x.xxx_hidden_SavedName
	}
	return ""
}

func (x *ContactRow) GetPushName() string {
	if x != nil {
		return x.xxx_hidden_PushName
	}
	return ""
}

func (x *ContactRow) GetBusinessName() string {
	if x != nil {
		return x.xxx_hidden_BusinessName
	}
	return ""
}

func (x *ContactRow) GetBusiness() bool {
	if x != nil {
		return x.xxx_hidden_Business
	}
	return false
}

func (x *ContactRow) GetAbout() string {
	if x != nil {
		return x.xxx_hidden_About
	}
	return ""
}

func (x *ContactRow) GetAvatarPath() string {
	if x != nil {
		return x.xxx_hidden_AvatarPath
	}
	return ""
}

func (x *ContactRow) GetBlocked() bool {
	if x != nil {
		return x.xxx_hidden_Blocked
	}
	return false
}

func (x *ContactRow) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ContactRow) SetPhone(v string) {
	x.xxx_hidden_Phone = v
}

func (x *ContactRow) SetSavedName(v string) {
	x.xxx_hidden_SavedName = v
}

func (x *ContactRow) SetPushName(v string) {
	x.xxx_hidden_PushName = v
}

func (x *ContactRow) SetBusinessName(v string) {
	x.xxx_hidden_BusinessName = v
}

func (x *ContactRow) SetBusiness(v bool) {
	x.xxx_hidden_Business = v
}

func (x *ContactRow) SetAbout(v string) {
	x.xxx_hidden_About = v
}

func (x *ContactRow) SetAvatarPath(v string) {
	x.xxx_hidden_AvatarPath = v
}

func (x *ContactRow) SetBlocked(v bool) {
	x.xxx_hidden_Blocked = v
}

type ContactRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           string
	Phone        string
	SavedName    string
	PushName     string
	BusinessName string
	Business     bool
	About        string
	AvatarPath   string
	Blocked      bool
}

func (b0 ContactRow_builder) Build() *ContactRow {
	m0 := &ContactRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Phone = b.Phone
	x.xxx_hidden_SavedName = b.SavedName
	x.xxx_hidden_PushName = b.PushName
	x.xxx_hidden_BusinessName = b.BusinessName
	x.xxx_hidden_Business = b.Business
	x.xxx_hidden_About = b.About
	x.xxx_hidden_AvatarPath = b.AvatarPath
	x.xxx_hidden_Blocked = b.Blocked
	return m0
}

// one item per person on the blocklist
type BlocklistView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocklistView) Reset() {
	*x = BlocklistView{}
	mi := &file_whatevr_v2_people_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocklistView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocklistView) ProtoMessage() {}

func (x *BlocklistView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type BlocklistView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 BlocklistView_builder) Build() *BlocklistView {
	m0 := &BlocklistView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type BlockedRow struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person *Person                `protobuf:"bytes,1,opt,name=person"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BlockedRow) Reset() {
	*x = BlockedRow{}
	mi := &file_whatevr_v2_people_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedRow) ProtoMessage() {}

func (x *BlockedRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BlockedRow) GetPerson() *Person {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *BlockedRow) SetPerson(v *Person) {
	x.xxx_hidden_Person = v
}

func (x *BlockedRow) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *BlockedRow) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type BlockedRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person *Person
}

func (b0 BlockedRow_builder) Build() *BlockedRow {
	m0 := &BlockedRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	return m0
}

// availability of everyone in a chat; subscribing is what asks whatsapp for it
type PresenceView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PresenceView) Reset() {
	*x = PresenceView{}
	mi := &file_whatevr_v2_people_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceView) ProtoMessage() {}

func (x *PresenceView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PresenceView) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *PresenceView) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

type PresenceView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId string
}

func (b0 PresenceView_builder) Build() *PresenceView {
	m0 := &PresenceView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	return m0
}

type PresenceRow struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person       *Person                `protobuf:"bytes,1,opt,name=person"`
	xxx_hidden_Availability Availability           `protobuf:"varint,2,opt,name=availability,enum=whatevr.v2.Availability"`
	xxx_hidden_LastSeenMs   int64                  `protobuf:"varint,3,opt,name=last_seen_ms,json=lastSeenMs"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PresenceRow) Reset() {
	*x = PresenceRow{}
	mi := &file_whatevr_v2_people_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceRow) ProtoMessage() {}

func (x *PresenceRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PresenceRow) GetPerson() *Person {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *PresenceRow) GetAvailability() Availability {
	if x != nil {
		return x.xxx_hidden_Availability
	}
	return Availability_AVAILABILITY_UNSPECIFIED
}

func (x *PresenceRow) GetLastSeenMs() int64 {
	if x != nil {
		return x.xxx_hidden_LastSeenMs
	}
	return 0
}

func (x *PresenceRow) SetPerson(v *Person) {
	x.xxx_hidden_Person = v
}

func (x *PresenceRow) SetAvailability(v Availability) {
	x.xxx_hidden_Availability = v
}

func (x *PresenceRow) SetLastSeenMs(v int64) {
	x.xxx_hidden_LastSeenMs = v
}

func (x *PresenceRow) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *PresenceRow) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type PresenceRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person       *Person
	Availability Availability
	LastSeenMs   int64
}

func (b0 PresenceRow_builder) Build() *PresenceRow {
	m0 := &PresenceRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	x.xxx_hidden_Availability = b.Availability
	x.xxx_hidden_LastSeenMs = b.LastSeenMs
	return m0
}

// one item per chat with anyone composing, id is the chat id
type TypingView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingView) Reset() {
	*x = TypingView{}
	mi := &file_whatevr_v2_people_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingView) ProtoMessage() {}

func (x *TypingView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TypingView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TypingView_builder) Build() *TypingView {
	m0 := &TypingView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TypingRow struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChatId  string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId"`
	xxx_hidden_Typists *[]*Typist             `protobuf:"bytes,2,rep,name=typists"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TypingRow) Reset() {
	*x = TypingRow{}
	mi := &file_whatevr_v2_people_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingRow) ProtoMessage() {}

func (x *TypingRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TypingRow) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *TypingRow) GetTypists() []*Typist {
	if x != nil {
		if x.xxx_hidden_Typists != nil {
			return *x.xxx_hidden_Typists
		}
	}
	return nil
}

func (x *TypingRow) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *TypingRow) SetTypists(v []*Typist) {
	x.xxx_hidden_Typists = &v
}

type TypingRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChatId  string
	Typists []*Typist
}

func (b0 TypingRow_builder) Build() *TypingRow {
	m0 := &TypingRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Typists = &b.Typists
	return m0
}

type Typist struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person    *Person                `protobuf:"bytes,1,opt,name=person"`
	xxx_hidden_Recording bool                   `protobuf:"varint,2,opt,name=recording"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Typist) Reset() {
	*x = Typist{}
	mi := &file_whatevr_v2_people_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Typist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Typist) ProtoMessage() {}

func (x *Typist) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Typist) GetPerson() *Person {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *Typist) GetRecording() bool {
	if x != nil {
		return x.xxx_hidden_Recording
	}
	return false
}

func (x *Typist) SetPerson(v *Person) {
	x.xxx_hidden_Person = v
}

func (x *Typist) SetRecording(v bool) {
	x.xxx_hidden_Recording = v
}

func (x *Typist) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *Typist) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type Typist_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person    *Person
	Recording bool
}

func (b0 Typist_builder) Build() *Typist {
	m0 := &Typist{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	x.xxx_hidden_Recording = b.Recording
	return m0
}

type ContactBlock struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Person  *Address               `protobuf:"bytes,1,opt,name=person"`
	xxx_hidden_Blocked bool                   `protobuf:"varint,2,opt,name=blocked"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ContactBlock) Reset() {
	*x = ContactBlock{}
	mi := &file_whatevr_v2_people_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactBlock) ProtoMessage() {}

func (x *ContactBlock) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContactBlock) GetPerson() *Address {
	if x != nil {
		return x.xxx_hidden_Person
	}
	return nil
}

func (x *ContactBlock) GetBlocked() bool {
	if x != nil {
		return x.xxx_hidden_Blocked
	}
	return false
}

func (x *ContactBlock) SetPerson(v *Address) {
	x.xxx_hidden_Person = v
}

func (x *ContactBlock) SetBlocked(v bool) {
	x.xxx_hidden_Blocked = v
}

func (x *ContactBlock) HasPerson() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Person != nil
}

func (x *ContactBlock) ClearPerson() {
	x.xxx_hidden_Person = nil
}

type ContactBlock_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Person  *Address
	Blocked bool
}

func (b0 ContactBlock_builder) Build() *ContactBlock {
	m0 := &ContactBlock{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Person = b.Person
	x.xxx_hidden_Blocked = b.Blocked
	return m0
}

type SelfSetAbout struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text string                 `protobuf:"bytes,1,opt,name=text"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SelfSetAbout) Reset() {
	*x = SelfSetAbout{}
	mi := &file_whatevr_v2_people_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfSetAbout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfSetAbout) ProtoMessage() {}

func (x *SelfSetAbout) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_people_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SelfSetAbout) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *SelfSetAbout) SetText(v string) {
	x.xxx_hidden_Text = v
}

type SelfSetAbout_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text string
}

func (b0 SelfSetAbout_builder) Build() *SelfSetAbout {
	m0 := &SelfSetAbout{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	return m0
}

var File_whatevr_v2_people_proto protoreflect.FileDescriptor

const file_whatevr_v2_people_proto_rawDesc = "" +
	"\n" +
	"\x17whatevr/v2/people.proto\x12\n" +
	"whatevr.v2\"p\n" +
	"\aAddress\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x16\n" +
	"\x05phone\x18\x02 \x01(\tH\x00R\x05phone\x12\x12\n" +
	"\x03lid\x18\x03 \x01(\tH\x00R\x03lid\x12\x1c\n" +
	"\busername\x18\x04 \x01(\tH\x00R\busernameB\t\n" +
	"\aaddress\"w\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1f\n" +
	"\vavatar_path\x18\x04 \x01(\tR\n" +
	"avatarPath\x12\x12\n" +
	"\x04self\x18\x05 \x01(\bR\x04self\"\n" +
	"\n" +
	"\bSelfView\"\x83\x01\n" +
	"\aSelfRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1b\n" +
	"\tpush_name\x18\x03 \x01(\tR\bpushName\x12\x14\n" +
	"\x05about\x18\x04 \x01(\tR\x05about\x12\x1f\n" +
	"\vavatar_path\x18\x05 \x01(\tR\n" +
	"avatarPath\":\n" +
	"\vContactView\x12+\n" +
	"\x06person\x18\x01 \x01(\v2\x13.whatevr.v2.AddressR\x06person\"\x80\x02\n" +
	"\n" +
	"ContactRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"saved_name\x18\x03 \x01(\tR\tsavedName\x12\x1b\n" +
	"\tpush_name\x18\x04 \x01(\tR\bpushName\x12#\n" +
	"\rbusiness_name\x18\x05 \x01(\tR\fbusinessName\x12\x1a\n" +
	"\bbusiness\x18\x06 \x01(\bR\bbusiness\x12\x14\n" +
	"\x05about\x18\a \x01(\tR\x05about\x12\x1f\n" +
	"\vavatar_path\x18\b \x01(\tR\n" +
	"avatarPath\x12\x18\n" +
	"\ablocked\x18\t \x01(\bR\ablocked\"\x0f\n" +
	"\rBlocklistView\"8\n" +
	"\n" +
	"BlockedRow\x12*\n" +
	"\x06person\x18\x01 \x01(\v2\x12.whatevr.v2.PersonR\x06person\"'\n" +
	"\fPresenceView\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\x99\x01\n" +
	"\vPresenceRow\x12*\n" +
	"\x06person\x18\x01 \x01(\v2\x12.whatevr.v2.PersonR\x06person\x12<\n" +
	"\favailability\x18\x02 \x01(\x0e2\x18.whatevr.v2.AvailabilityR\favailability\x12 \n" +
	"\flast_seen_ms\x18\x03 \x01(\x03R\n" +
	"lastSeenMs\"\f\n" +
	"\n" +
	"TypingView\"R\n" +
	"\tTypingRow\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12,\n" +
	"\atypists\x18\x02 \x03(\v2\x12.whatevr.v2.TypistR\atypists\"R\n" +
	"\x06Typist\x12*\n" +
	"\x06person\x18\x01 \x01(\v2\x12.whatevr.v2.PersonR\x06person\x12\x1c\n" +
	"\trecording\x18\x02 \x01(\bR\trecording\"U\n" +
	"\fContactBlock\x12+\n" +
	"\x06person\x18\x01 \x01(\v2\x13.whatevr.v2.AddressR\x06person\x12\x18\n" +
	"\ablocked\x18\x02 \x01(\bR\ablocked\"\"\n" +
	"\fSelfSetAbout\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text*_\n" +
	"\fAvailability\x12\x1c\n" +
	"\x18AVAILABILITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AVAILABILITY_ONLINE\x10\x01\x12\x18\n" +
	"\x14AVAILABILITY_OFFLINE\x10\x02B\xa0\x01\n" +
	"\x0ecom.whatevr.v2B\vPeopleProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_people_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whatevr_v2_people_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_whatevr_v2_people_proto_goTypes = []any{
	(Availability)(0),     // 0: whatevr.v2.Availability
	(*Address)(nil),       // 1: whatevr.v2.Address
	(*Person)(nil),        // 2: whatevr.v2.Person
	(*SelfView)(nil),      // 3: whatevr.v2.SelfView
	(*SelfRow)(nil),       // 4: whatevr.v2.SelfRow
	(*ContactView)(nil),   // 5: whatevr.v2.ContactView
	(*ContactRow)(nil),    // 6: whatevr.v2.ContactRow
	(*BlocklistView)(nil), // 7: whatevr.v2.BlocklistView
	(*BlockedRow)(nil),    // 8: whatevr.v2.BlockedRow
	(*PresenceView)(nil),  // 9: whatevr.v2.PresenceView
	(*PresenceRow)(nil),   // 10: whatevr.v2.PresenceRow
	(*TypingView)(nil),    // 11: whatevr.v2.TypingView
	(*TypingRow)(nil),     // 12: whatevr.v2.TypingRow
	(*Typist)(nil),        // 13: whatevr.v2.Typist
	(*ContactBlock)(nil),  // 14: whatevr.v2.ContactBlock
	(*SelfSetAbout)(nil),  // 15: whatevr.v2.SelfSetAbout
}
var file_whatevr_v2_people_proto_depIdxs = []int32{
	1,  // 0: whatevr.v2.ContactView.person:type_name -> whatevr.v2.Address
	2,  // 1: whatevr.v2.BlockedRow.person:type_name -> whatevr.v2.Person
	2,  // 2: whatevr.v2.PresenceRow.person:type_name -> whatevr.v2.Person
	0,  // 3: whatevr.v2.PresenceRow.availability:type_name -> whatevr.v2.Availability
	13, // 4: whatevr.v2.TypingRow.typists:type_name -> whatevr.v2.Typist
	2,  // 5: whatevr.v2.Typist.person:type_name -> whatevr.v2.Person
	1,  // 6: whatevr.v2.ContactBlock.person:type_name -> whatevr.v2.Address
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_whatevr_v2_people_proto_init() }
func file_whatevr_v2_people_proto_init() {
	if File_whatevr_v2_people_proto != nil {
		return
	}
	file_whatevr_v2_people_proto_msgTypes[0].OneofWrappers = []any{
		(*address_Id)(nil),
		(*address_Phone)(nil),
		(*address_Lid)(nil),
		(*address_Username)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_people_proto_rawDesc), len(file_whatevr_v2_people_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_people_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_people_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_people_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_people_proto_msgTypes,
	}.Build()
	File_whatevr_v2_people_proto = out.File
	file_whatevr_v2_people_proto_goTypes = nil
	file_whatevr_v2_people_proto_depIdxs = nil
}
