// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: whatevr/v2/search.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// chat names, in list order
type SearchChats struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Query string                 `protobuf:"bytes,1,opt,name=query"`
	xxx_hidden_Limit uint32                 `protobuf:"varint,2,opt,name=limit"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchChats) Reset() {
	*x = SearchChats{}
	mi := &file_whatevr_v2_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChats) ProtoMessage() {}

func (x *SearchChats) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchChats) GetQuery() string {
	if x != nil {
		return x.xxx_hidden_Query
	}
	return ""
}

func (x *SearchChats) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *SearchChats) SetQuery(v string) {
	x.xxx_hidden_Query = v
}

func (x *SearchChats) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
}

type SearchChats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Query string
	Limit uint32
}

func (b0 SearchChats_builder) Build() *SearchChats {
	m0 := &SearchChats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Query = b.Query
	x.xxx_hidden_Limit = b.Limit
	return m0
}

type SearchChatsResult struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Chats    *[]*ChatRow            `protobuf:"bytes,1,rep,name=chats"`
	xxx_hidden_Contacts *[]*ContactRow         `protobuf:"bytes,2,rep,name=contacts"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchChatsResult) Reset() {
	*x = SearchChatsResult{}
	mi := &file_whatevr_v2_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsResult) ProtoMessage() {}

func (x *SearchChatsResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchChatsResult) GetChats() []*ChatRow {
	if x != nil {
		if x.xxx_hidden_Chats != nil {
			return *x.xxx_hidden_Chats
		}
	}
	return nil
}

func (x *SearchChatsResult) GetContacts() []*ContactRow {
	if x != nil {
		if x.xxx_hidden_Contacts != nil {
			return *x.xxx_hidden_Contacts
		}
	}
	return nil
}

func (x *SearchChatsResult) SetChats(v []*ChatRow) {
	x.xxx_hidden_Chats = &v
}

func (x *SearchChatsResult) SetContacts(v []*ContactRow) {
	x.xxx_hidden_Contacts = &v
}

type SearchChatsResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Chats []*ChatRow
	// saved contacts matching the query that are not already shown as chats,
	// in saved-name order; start one with chat_ensure_direct
	Contacts []*ContactRow
}

func (b0 SearchChatsResult_builder) Build() *SearchChatsResult {
	m0 := &SearchChatsResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Chats = &b.Chats
	x.xxx_hidden_Contacts = &b.Contacts
	return m0
}

// newest first, paged backwards by before
type SearchMessages struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Query  string                 `protobuf:"bytes,1,opt,name=query"`
	xxx_hidden_ChatId string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId"`
	xxx_hidden_Limit  uint32                 `protobuf:"varint,3,opt,name=limit"`
	xxx_hidden_Before string                 `protobuf:"bytes,4,opt,name=before"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchMessages) Reset() {
	*x = SearchMessages{}
	mi := &file_whatevr_v2_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessages) ProtoMessage() {}

func (x *SearchMessages) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchMessages) GetQuery() string {
	if x != nil {
		return x.xxx_hidden_Query
	}
	return ""
}

func (x *SearchMessages) GetChatId() string {
	if x != nil {
		return x.xxx_hidden_ChatId
	}
	return ""
}

func (x *SearchMessages) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *SearchMessages) GetBefore() string {
	if x != nil {
		return x.xxx_hidden_Before
	}
	return ""
}

func (x *SearchMessages) SetQuery(v string) {
	x.xxx_hidden_Query = v
}

func (x *SearchMessages) SetChatId(v string) {
	x.xxx_hidden_ChatId = v
}

func (x *SearchMessages) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
}

func (x *SearchMessages) SetBefore(v string) {
	x.xxx_hidden_Before = v
}

type SearchMessages_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Query string
	// empty for every chat
	ChatId string
	Limit  uint32
	// the last message_id of the previous page
	Before string
}

func (b0 SearchMessages_builder) Build() *SearchMessages {
	m0 := &SearchMessages{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Query = b.Query
	x.xxx_hidden_ChatId = b.ChatId
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Before = b.Before
	return m0
}

type SearchMessagesResult struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Messages *[]*MessageRow         `protobuf:"bytes,1,rep,name=messages"`
	xxx_hidden_More     bool                   `protobuf:"varint,2,opt,name=more"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchMessagesResult) Reset() {
	*x = SearchMessagesResult{}
	mi := &file_whatevr_v2_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesResult) ProtoMessage() {}

func (x *SearchMessagesResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchMessagesResult) GetMessages() []*MessageRow {
	if x != nil {
		if x.xxx_hidden_Messages != nil {
			return *x.xxx_hidden_Messages
		}
	}
	return nil
}

func (x *SearchMessagesResult) GetMore() bool {
	if x != nil {
		return x.xxx_hidden_More
	}
	return false
}

func (x *SearchMessagesResult) SetMessages(v []*MessageRow) {
	x.xxx_hidden_Messages = &v
}

func (x *SearchMessagesResult) SetMore(v bool) {
	x.xxx_hidden_More = v
}

type SearchMessagesResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// chat_name set on each
	Messages []*MessageRow
	More     bool
}

func (b0 SearchMessagesResult_builder) Build() *SearchMessagesResult {
	m0 := &SearchMessagesResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Messages = &b.Messages
	x.xxx_hidden_More = b.More
	return m0
}

type SearchStickers struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Query string                 `protobuf:"bytes,1,opt,name=query"`
	xxx_hidden_Limit uint32                 `protobuf:"varint,2,opt,name=limit"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchStickers) Reset() {
	*x = SearchStickers{}
	mi := &file_whatevr_v2_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStickers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStickers) ProtoMessage() {}

func (x *SearchStickers) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchStickers) GetQuery() string {
	if x != nil {
		return x.xxx_hidden_Query
	}
	return ""
}

func (x *SearchStickers) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *SearchStickers) SetQuery(v string) {
	x.xxx_hidden_Query = v
}

func (x *SearchStickers) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
}

type SearchStickers_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Query string
	Limit uint32
}

func (b0 SearchStickers_builder) Build() *SearchStickers {
	m0 := &SearchStickers{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Query = b.Query
	x.xxx_hidden_Limit = b.Limit
	return m0
}

type SearchStickersResult struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stickers *[]*StickerRow         `protobuf:"bytes,1,rep,name=stickers"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchStickersResult) Reset() {
	*x = SearchStickersResult{}
	mi := &file_whatevr_v2_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStickersResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStickersResult) ProtoMessage() {}

func (x *SearchStickersResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchStickersResult) GetStickers() []*StickerRow {
	if x != nil {
		if x.xxx_hidden_Stickers != nil {
			return *x.xxx_hidden_Stickers
		}
	}
	return nil
}

func (x *SearchStickersResult) SetStickers(v []*StickerRow) {
	x.xxx_hidden_Stickers = &v
}

type SearchStickersResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Stickers []*StickerRow
}

func (b0 SearchStickersResult_builder) Build() *SearchStickersResult {
	m0 := &SearchStickersResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stickers = &b.Stickers
	return m0
}

// whether a phone number is on whatsapp
type ContactCheckPhone struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Phone string                 `protobuf:"bytes,1,opt,name=phone"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContactCheckPhone) Reset() {
	*x = ContactCheckPhone{}
	mi := &file_whatevr_v2_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactCheckPhone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactCheckPhone) ProtoMessage() {}

func (x *ContactCheckPhone) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContactCheckPhone) GetPhone() string {
	if x != nil {
		return x.xxx_hidden_Phone
	}
	return ""
}

func (x *ContactCheckPhone) SetPhone(v string) {
	x.xxx_hidden_Phone = v
}

type ContactCheckPhone_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Phone string
}

func (b0 ContactCheckPhone_builder) Build() *ContactCheckPhone {
	m0 := &ContactCheckPhone{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Phone = b.Phone
	return m0
}

type ContactCheckPhoneResult struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Registered bool                   `protobuf:"varint,1,opt,name=registered"`
	xxx_hidden_Phone      string                 `protobuf:"bytes,2,opt,name=phone"`
	xxx_hidden_PersonId   string                 `protobuf:"bytes,3,opt,name=person_id,json=personId"`
	xxx_hidden_Name       string                 `protobuf:"bytes,4,opt,name=name"`
	xxx_hidden_Business   bool                   `protobuf:"varint,5,opt,name=business"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ContactCheckPhoneResult) Reset() {
	*x = ContactCheckPhoneResult{}
	mi := &file_whatevr_v2_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactCheckPhoneResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactCheckPhoneResult) ProtoMessage() {}

func (x *ContactCheckPhoneResult) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContactCheckPhoneResult) GetRegistered() bool {
	if x != nil {
		return x.xxx_hidden_Registered
	}
	return false
}

func (x *ContactCheckPhoneResult) GetPhone() string {
	if x != nil {
		return x.xxx_hidden_Phone
	}
	return ""
}

func (x *ContactCheckPhoneResult) GetPersonId() string {
	if x != nil {
		return x.xxx_hidden_PersonId
	}
	return ""
}

func (x *ContactCheckPhoneResult) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ContactCheckPhoneResult) GetBusiness() bool {
	if x != nil {
		return x.xxx_hidden_Business
	}
	return false
}

func (x *ContactCheckPhoneResult) SetRegistered(v bool) {
	x.xxx_hidden_Registered = v
}

func (x *ContactCheckPhoneResult) SetPhone(v string) {
	x.xxx_hidden_Phone = v
}

func (x *ContactCheckPhoneResult) SetPersonId(v string) {
	x.xxx_hidden_PersonId = v
}

func (x *ContactCheckPhoneResult) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ContactCheckPhoneResult) SetBusiness(v bool) {
	x.xxx_hidden_Business = v
}

type ContactCheckPhoneResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Registered bool
	// the normalized number
	Phone string
	// the person to open a chat with, when registered
	PersonId string
	Name     string
	Business bool
}

func (b0 ContactCheckPhoneResult_builder) Build() *ContactCheckPhoneResult {
	m0 := &ContactCheckPhoneResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Registered = b.Registered
	x.xxx_hidden_Phone = b.Phone
	x.xxx_hidden_PersonId = b.PersonId
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Business = b.Business
	return m0
}

var File_whatevr_v2_search_proto protoreflect.FileDescriptor

const file_whatevr_v2_search_proto_rawDesc = "" +
	"\n" +
	"\x17whatevr/v2/search.proto\x12\n" +
	"whatevr.v2\x1a\x16whatevr/v2/chats.proto\x1a\x19whatevr/v2/messages.proto\x1a\x17whatevr/v2/people.proto\x1a\x19whatevr/v2/stickers.proto\"9\n" +
	"\vSearchChats\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"r\n" +
	"\x11SearchChatsResult\x12)\n" +
	"\x05chats\x18\x01 \x03(\v2\x13.whatevr.v2.ChatRowR\x05chats\x122\n" +
	"\bcontacts\x18\x02 \x03(\v2\x16.whatevr.v2.ContactRowR\bcontacts\"m\n" +
	"\x0eSearchMessages\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06before\x18\x04 \x01(\tR\x06before\"^\n" +
	"\x14SearchMessagesResult\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.whatevr.v2.MessageRowR\bmessages\x12\x12\n" +
	"\x04more\x18\x02 \x01(\bR\x04more\"<\n" +
	"\x0eSearchStickers\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"J\n" +
	"\x14SearchStickersResult\x122\n" +
	"\bstickers\x18\x01 \x03(\v2\x16.whatevr.v2.StickerRowR\bstickers\")\n" +
	"\x11ContactCheckPhone\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"\x9c\x01\n" +
	"\x17ContactCheckPhoneResult\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\bR\n" +
	"registered\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1b\n" +
	"\tperson_id\x18\x03 \x01(\tR\bpersonId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bbusiness\x18\x05 \x01(\bR\bbusinessB\x05\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_whatevr_v2_search_proto_goTypes = []any{
	(*SearchChats)(nil),             // 0: whatevr.v2.SearchChats
	(*SearchChatsResult)(nil),       // 1: whatevr.v2.SearchChatsResult
	(*SearchMessages)(nil),          // 2: whatevr.v2.SearchMessages
	(*SearchMessagesResult)(nil),    // 3: whatevr.v2.SearchMessagesResult
	(*SearchStickers)(nil),          // 4: whatevr.v2.SearchStickers
	(*SearchStickersResult)(nil),    // 5: whatevr.v2.SearchStickersResult
	(*ContactCheckPhone)(nil),       // 6: whatevr.v2.ContactCheckPhone
	(*ContactCheckPhoneResult)(nil), // 7: whatevr.v2.ContactCheckPhoneResult
	(*ChatRow)(nil),                 // 8: whatevr.v2.ChatRow
	(*ContactRow)(nil),              // 9: whatevr.v2.ContactRow
	(*MessageRow)(nil),              // 10: whatevr.v2.MessageRow
	(*StickerRow)(nil),              // 11: whatevr.v2.StickerRow
}
var file_whatevr_v2_search_proto_depIdxs = []int32{
	8,  // 0: whatevr.v2.SearchChatsResult.chats:type_name -> whatevr.v2.ChatRow
	9,  // 1: whatevr.v2.SearchChatsResult.contacts:type_name -> whatevr.v2.ContactRow
	10, // 2: whatevr.v2.SearchMessagesResult.messages:type_name -> whatevr.v2.MessageRow
	11, // 3: whatevr.v2.SearchStickersResult.stickers:type_name -> whatevr.v2.StickerRow
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_whatevr_v2_search_proto_init() }
func file_whatevr_v2_search_proto_init() {
	if File_whatevr_v2_search_proto != nil {
		return
	}
	file_whatevr_v2_chats_proto_init()
	file_whatevr_v2_messages_proto_init()
	file_whatevr_v2_people_proto_init()
	file_whatevr_v2_stickers_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_search_proto_rawDesc), len(file_whatevr_v2_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_search_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_search_proto_depIdxs,
		MessageInfos:      file_whatevr_v2_search_proto_msgTypes,
	}.Build()
	File_whatevr_v2_search_proto = out.File
	file_whatevr_v2_search_proto_goTypes = nil
	file_whatevr_v2_search_proto_depIdxs = nil
}
