// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/settings.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivacyCategory int32

const (
	PrivacyCategory_PRIVACY_CATEGORY_UNSPECIFIED   PrivacyCategory = 0
	PrivacyCategory_PRIVACY_CATEGORY_LAST_SEEN     PrivacyCategory = 1
	PrivacyCategory_PRIVACY_CATEGORY_ONLINE        PrivacyCategory = 2
	PrivacyCategory_PRIVACY_CATEGORY_PROFILE_PHOTO PrivacyCategory = 3
	PrivacyCategory_PRIVACY_CATEGORY_ABOUT         PrivacyCategory = 4
	PrivacyCategory_PRIVACY_CATEGORY_GROUP_ADD     PrivacyCategory = 5
	PrivacyCategory_PRIVACY_CATEGORY_CALL_ADD      PrivacyCategory = 6
	PrivacyCategory_PRIVACY_CATEGORY_READ_RECEIPTS PrivacyCategory = 7
)

// Enum value maps for PrivacyCategory.
var (
	PrivacyCategory_name = map[int32]string{
		0: "PRIVACY_CATEGORY_UNSPECIFIED",
		1: "PRIVACY_CATEGORY_LAST_SEEN",
		2: "PRIVACY_CATEGORY_ONLINE",
		3: "PRIVACY_CATEGORY_PROFILE_PHOTO",
		4: "PRIVACY_CATEGORY_ABOUT",
		5: "PRIVACY_CATEGORY_GROUP_ADD",
		6: "PRIVACY_CATEGORY_CALL_ADD",
		7: "PRIVACY_CATEGORY_READ_RECEIPTS",
	}
	PrivacyCategory_value = map[string]int32{
		"PRIVACY_CATEGORY_UNSPECIFIED":   0,
		"PRIVACY_CATEGORY_LAST_SEEN":     1,
		"PRIVACY_CATEGORY_ONLINE":        2,
		"PRIVACY_CATEGORY_PROFILE_PHOTO": 3,
		"PRIVACY_CATEGORY_ABOUT":         4,
		"PRIVACY_CATEGORY_GROUP_ADD":     5,
		"PRIVACY_CATEGORY_CALL_ADD":      6,
		"PRIVACY_CATEGORY_READ_RECEIPTS": 7,
	}
)

func (x PrivacyCategory) Enum() *PrivacyCategory {
	p := new(PrivacyCategory)
	*p = x
	return p
}

func (x PrivacyCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivacyCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_settings_proto_enumTypes[0].Descriptor()
}

func (PrivacyCategory) Type() protoreflect.EnumType {
	return &file_whatevr_v2_settings_proto_enumTypes[0]
}

func (x PrivacyCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type PrivacyValue int32

const (
	PrivacyValue_PRIVACY_VALUE_UNSPECIFIED     PrivacyValue = 0
	PrivacyValue_PRIVACY_VALUE_ALL             PrivacyValue = 1
	PrivacyValue_PRIVACY_VALUE_CONTACTS        PrivacyValue = 2
	PrivacyValue_PRIVACY_VALUE_CONTACTS_EXCEPT PrivacyValue = 3
	PrivacyValue_PRIVACY_VALUE_NOBODY          PrivacyValue = 4
	// online only: the same as last seen
	PrivacyValue_PRIVACY_VALUE_MATCH_LAST_SEEN PrivacyValue = 5
	// call add only
	PrivacyValue_PRIVACY_VALUE_KNOWN PrivacyValue = 6
)

// Enum value maps for PrivacyValue.
var (
	PrivacyValue_name = map[int32]string{
		0: "PRIVACY_VALUE_UNSPECIFIED",
		1: "PRIVACY_VALUE_ALL",
		2: "PRIVACY_VALUE_CONTACTS",
		3: "PRIVACY_VALUE_CONTACTS_EXCEPT",
		4: "PRIVACY_VALUE_NOBODY",
		5: "PRIVACY_VALUE_MATCH_LAST_SEEN",
		6: "PRIVACY_VALUE_KNOWN",
	}
	PrivacyValue_value = map[string]int32{
		"PRIVACY_VALUE_UNSPECIFIED":     0,
		"PRIVACY_VALUE_ALL":             1,
		"PRIVACY_VALUE_CONTACTS":        2,
		"PRIVACY_VALUE_CONTACTS_EXCEPT": 3,
		"PRIVACY_VALUE_NOBODY":          4,
		"PRIVACY_VALUE_MATCH_LAST_SEEN": 5,
		"PRIVACY_VALUE_KNOWN":           6,
	}
)

func (x PrivacyValue) Enum() *PrivacyValue {
	p := new(PrivacyValue)
	*p = x
	return p
}

func (x PrivacyValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivacyValue) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_settings_proto_enumTypes[1].Descriptor()
}

func (PrivacyValue) Type() protoreflect.EnumType {
	return &file_whatevr_v2_settings_proto_enumTypes[1]
}

func (x PrivacyValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// whatsapp's privacy settings for this account
type PrivacyView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivacyView) Reset() {
	*x = PrivacyView{}
	mi := &file_whatevr_v2_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacyView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyView) ProtoMessage() {}

func (x *PrivacyView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PrivacyView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PrivacyView_builder) Build() *PrivacyView {
	m0 := &PrivacyView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PrivacyRow struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LastSeen     PrivacyValue           `protobuf:"varint,1,opt,name=last_seen,json=lastSeen,enum=whatevr.v2.PrivacyValue"`
	xxx_hidden_Online       PrivacyValue           `protobuf:"varint,2,opt,name=online,enum=whatevr.v2.PrivacyValue"`
	xxx_hidden_ProfilePhoto PrivacyValue           `protobuf:"varint,3,opt,name=profile_photo,json=profilePhoto,enum=whatevr.v2.PrivacyValue"`
	xxx_hidden_About        PrivacyValue           `protobuf:"varint,4,opt,name=about,enum=whatevr.v2.PrivacyValue"`
	xxx_hidden_GroupAdd     PrivacyValue           `protobuf:"varint,5,opt,name=group_add,json=groupAdd,enum=whatevr.v2.PrivacyValue"`
	xxx_hidden_CallAdd      PrivacyValue           `protobuf:"varint,6,opt,name=call_add,json=callAdd,enum=whatevr.v2.PrivacyValue"`
	xxx_hidden_ReadReceipts bool                   `protobuf:"varint,7,opt,name=read_receipts,json=readReceipts"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PrivacyRow) Reset() {
	*x = PrivacyRow{}
	mi := &file_whatevr_v2_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacyRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyRow) ProtoMessage() {}

func (x *PrivacyRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrivacyRow) GetLastSeen() PrivacyValue {
	if x != nil {
		return x.xxx_hidden_LastSeen
	}
	return PrivacyValue_PRIVACY_VALUE_UNSPECIFIED
}

func (x *PrivacyRow) GetOnline() PrivacyValue {
	if x != nil {
		return x.xxx_hidden_Online
	}
	return PrivacyValue_PRIVACY_VALUE_UNSPECIFIED
}

func (x *PrivacyRow) GetProfilePhoto() PrivacyValue {
	if x != nil {
		return x.xxx_hidden_ProfilePhoto
	}
	return PrivacyValue_PRIVACY_VALUE_UNSPECIFIED
}

func (x *PrivacyRow) GetAbout() PrivacyValue {
	if x != nil {
		return x.xxx_hidden_About
	}
	return PrivacyValue_PRIVACY_VALUE_UNSPECIFIED
}

func (x *PrivacyRow) GetGroupAdd() PrivacyValue {
	if x != nil {
		return x.xxx_hidden_GroupAdd
	}
	return PrivacyValue_PRIVACY_VALUE_UNSPECIFIED
}

func (x *PrivacyRow) GetCallAdd() PrivacyValue {
	if x != nil {
		return x.xxx_hidden_CallAdd
	}
	return PrivacyValue_PRIVACY_VALUE_UNSPECIFIED
}

func (x *PrivacyRow) GetReadReceipts() bool {
	if x != nil {
		return x.xxx_hidden_ReadReceipts
	}
	return false
}

func (x *PrivacyRow) SetLastSeen(v PrivacyValue) {
	x.xxx_hidden_LastSeen = v
}

func (x *PrivacyRow) SetOnline(v PrivacyValue) {
	x.xxx_hidden_Online = v
}

func (x *PrivacyRow) SetProfilePhoto(v PrivacyValue) {
	x.xxx_hidden_ProfilePhoto = v
}

func (x *PrivacyRow) SetAbout(v PrivacyValue) {
	x.xxx_hidden_About = v
}

func (x *PrivacyRow) SetGroupAdd(v PrivacyValue) {
	x.xxx_hidden_GroupAdd = v
}

func (x *PrivacyRow) SetCallAdd(v PrivacyValue) {
	x.xxx_hidden_CallAdd = v
}

func (x *PrivacyRow) SetReadReceipts(v bool) {
	x.xxx_hidden_ReadReceipts = v
}

type PrivacyRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LastSeen     PrivacyValue
	Online       PrivacyValue
	ProfilePhoto PrivacyValue
	About        PrivacyValue
	GroupAdd     PrivacyValue
	CallAdd      PrivacyValue
	ReadReceipts bool
}

func (b0 PrivacyRow_builder) Build() *PrivacyRow {
	m0 := &PrivacyRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LastSeen = b.LastSeen
	x.xxx_hidden_Online = b.Online
	x.xxx_hidden_ProfilePhoto = b.ProfilePhoto
	x.xxx_hidden_About = b.About
	x.xxx_hidden_GroupAdd = b.GroupAdd
	x.xxx_hidden_CallAdd = b.CallAdd
	x.xxx_hidden_ReadReceipts = b.ReadReceipts
	return m0
}

type PrivacySet struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Category PrivacyCategory        `protobuf:"varint,1,opt,name=category,enum=whatevr.v2.PrivacyCategory"`
	xxx_hidden_Value    PrivacyValue           `protobuf:"varint,2,opt,name=value,enum=whatevr.v2.PrivacyValue"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PrivacySet) Reset() {
	*x = PrivacySet{}
	mi := &file_whatevr_v2_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacySet) ProtoMessage() {}

func (x *PrivacySet) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrivacySet) GetCategory() PrivacyCategory {
	if x != nil {
		return x.xxx_hidden_Category
	}
	return PrivacyCategory_PRIVACY_CATEGORY_UNSPECIFIED
}

func (x *PrivacySet) GetValue() PrivacyValue {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return PrivacyValue_PRIVACY_VALUE_UNSPECIFIED
}

func (x *PrivacySet) SetCategory(v PrivacyCategory) {
	x.xxx_hidden_Category = v
}

func (x *PrivacySet) SetValue(v PrivacyValue) {
	x.xxx_hidden_Value = v
}

type PrivacySet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Category PrivacyCategory
	// read receipts take ALL for on, NOBODY for off
	Value PrivacyValue
}

func (b0 PrivacySet_builder) Build() *PrivacySet {
	m0 := &PrivacySet{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Category = b.Category
	x.xxx_hidden_Value = b.Value
	return m0
}

// the daemon's own preferences, kept across restarts
type PreferencesView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferencesView) Reset() {
	*x = PreferencesView{}
	mi := &file_whatevr_v2_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferencesView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferencesView) ProtoMessage() {}

func (x *PreferencesView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PreferencesView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PreferencesView_builder) Build() *PreferencesView {
	m0 := &PreferencesView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PreferencesRow struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Preferences *Preferences           `protobuf:"bytes,1,opt,name=preferences"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PreferencesRow) Reset() {
	*x = PreferencesRow{}
	mi := &file_whatevr_v2_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferencesRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferencesRow) ProtoMessage() {}

func (x *PreferencesRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PreferencesRow) GetPreferences() *Preferences {
	if x != nil {
		return x.xxx_hidden_Preferences
	}
	return nil
}

func (x *PreferencesRow) SetPreferences(v *Preferences) {
	x.xxx_hidden_Preferences = v
}

func (x *PreferencesRow) HasPreferences() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Preferences != nil
}

func (x *PreferencesRow) ClearPreferences() {
	x.xxx_hidden_Preferences = nil
}

type PreferencesRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Preferences *Preferences
}

func (b0 PreferencesRow_builder) Build() *PreferencesRow {
	m0 := &PreferencesRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Preferences = b.Preferences
	return m0
}

type Preferences struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Notifications         bool                   `protobuf:"varint,1,opt,name=notifications"`
	xxx_hidden_NotificationSound     bool                   `protobuf:"varint,2,opt,name=notification_sound,json=notificationSound"`
	xxx_hidden_NotificationPreview   bool                   `protobuf:"varint,3,opt,name=notification_preview,json=notificationPreview"`
	xxx_hidden_AutoDownloadPhotos    bool                   `protobuf:"varint,4,opt,name=auto_download_photos,json=autoDownloadPhotos"`
	xxx_hidden_AutoDownloadVideos    bool                   `protobuf:"varint,5,opt,name=auto_download_videos,json=autoDownloadVideos"`
	xxx_hidden_AutoDownloadAudio     bool                   `protobuf:"varint,6,opt,name=auto_download_audio,json=autoDownloadAudio"`
	xxx_hidden_AutoDownloadDocuments bool                   `protobuf:"varint,7,opt,name=auto_download_documents,json=autoDownloadDocuments"`
	xxx_hidden_AutoDownloadStickers  bool                   `protobuf:"varint,8,opt,name=auto_download_stickers,json=autoDownloadStickers"`
	xxx_hidden_AutoDownloadMaxBytes  uint64                 `protobuf:"varint,9,opt,name=auto_download_max_bytes,json=autoDownloadMaxBytes"`
	xxx_hidden_AutoFetchMaps         bool                   `protobuf:"varint,10,opt,name=auto_fetch_maps,json=autoFetchMaps"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *Preferences) Reset() {
	*x = Preferences{}
	mi := &file_whatevr_v2_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preferences) ProtoMessage() {}

func (x *Preferences) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Preferences) GetNotifications() bool {
	if x != nil {
		return x.xxx_hidden_Notifications
	}
	return false
}

func (x *Preferences) GetNotificationSound() bool {
	if x != nil {
		return x.xxx_hidden_NotificationSound
	}
	return false
}

func (x *Preferences) GetNotificationPreview() bool {
	if x != nil {
		return x.xxx_hidden_NotificationPreview
	}
	return false
}

func (x *Preferences) GetAutoDownloadPhotos() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadPhotos
	}
	return false
}

func (x *Preferences) GetAutoDownloadVideos() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadVideos
	}
	return false
}

func (x *Preferences) GetAutoDownloadAudio() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadAudio
	}
	return false
}

func (x *Preferences) GetAutoDownloadDocuments() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadDocuments
	}
	return false
}

func (x *Preferences) GetAutoDownloadStickers() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadStickers
	}
	return false
}

func (x *Preferences) GetAutoDownloadMaxBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_AutoDownloadMaxBytes
	}
	return 0
}

func (x *Preferences) GetAutoFetchMaps() bool {
	if x != nil {
		return x.xxx_hidden_AutoFetchMaps
	}
	return false
}

func (x *Preferences) SetNotifications(v bool) {
	x.xxx_hidden_Notifications = v
}

func (x *Preferences) SetNotificationSound(v bool) {
	x.xxx_hidden_NotificationSound = v
}

func (x *Preferences) SetNotificationPreview(v bool) {
	x.xxx_hidden_NotificationPreview = v
}

func (x *Preferences) SetAutoDownloadPhotos(v bool) {
	x.xxx_hidden_AutoDownloadPhotos = v
}

func (x *Preferences) SetAutoDownloadVideos(v bool) {
	x.xxx_hidden_AutoDownloadVideos = v
}

func (x *Preferences) SetAutoDownloadAudio(v bool) {
	x.xxx_hidden_AutoDownloadAudio = v
}

func (x *Preferences) SetAutoDownloadDocuments(v bool) {
	x.xxx_hidden_AutoDownloadDocuments = v
}

func (x *Preferences) SetAutoDownloadStickers(v bool) {
	x.xxx_hidden_AutoDownloadStickers = v
}

func (x *Preferences) SetAutoDownloadMaxBytes(v uint64) {
	x.xxx_hidden_AutoDownloadMaxBytes = v
}

func (x *Preferences) SetAutoFetchMaps(v bool) {
	x.xxx_hidden_AutoFetchMaps = v
}

type Preferences_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Notifications         bool
	NotificationSound     bool
	NotificationPreview   bool
	AutoDownloadPhotos    bool
	AutoDownloadVideos    bool
	AutoDownloadAudio     bool
	AutoDownloadDocuments bool
	AutoDownloadStickers  bool
	AutoDownloadMaxBytes  uint64
	// fetch map tiles for a location's picture
	AutoFetchMaps bool
}

func (b0 Preferences_builder) Build() *Preferences {
	m0 := &Preferences{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Notifications = b.Notifications
	x.xxx_hidden_NotificationSound = b.NotificationSound
	x.xxx_hidden_NotificationPreview = b.NotificationPreview
	x.xxx_hidden_AutoDownloadPhotos = b.AutoDownloadPhotos
	x.xxx_hidden_AutoDownloadVideos = b.AutoDownloadVideos
	x.xxx_hidden_AutoDownloadAudio = b.AutoDownloadAudio
	x.xxx_hidden_AutoDownloadDocuments = b.AutoDownloadDocuments
	x.xxx_hidden_AutoDownloadStickers = b.AutoDownloadStickers
	x.xxx_hidden_AutoDownloadMaxBytes = b.AutoDownloadMaxBytes
	x.xxx_hidden_AutoFetchMaps = b.AutoFetchMaps
	return m0
}

// sets the fields that are present; the rest stay as they are
type PreferencesSet struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Notifications         bool                   `protobuf:"varint,1,opt,name=notifications"`
	xxx_hidden_NotificationSound     bool                   `protobuf:"varint,2,opt,name=notification_sound,json=notificationSound"`
	xxx_hidden_NotificationPreview   bool                   `protobuf:"varint,3,opt,name=notification_preview,json=notificationPreview"`
	xxx_hidden_AutoDownloadPhotos    bool                   `protobuf:"varint,4,opt,name=auto_download_photos,json=autoDownloadPhotos"`
	xxx_hidden_AutoDownloadVideos    bool                   `protobuf:"varint,5,opt,name=auto_download_videos,json=autoDownloadVideos"`
	xxx_hidden_AutoDownloadAudio     bool                   `protobuf:"varint,6,opt,name=auto_download_audio,json=autoDownloadAudio"`
	xxx_hidden_AutoDownloadDocuments bool                   `protobuf:"varint,7,opt,name=auto_download_documents,json=autoDownloadDocuments"`
	xxx_hidden_AutoDownloadStickers  bool                   `protobuf:"varint,8,opt,name=auto_download_stickers,json=autoDownloadStickers"`
	xxx_hidden_AutoDownloadMaxBytes  uint64                 `protobuf:"varint,9,opt,name=auto_download_max_bytes,json=autoDownloadMaxBytes"`
	xxx_hidden_AutoFetchMaps         bool                   `protobuf:"varint,10,opt,name=auto_fetch_maps,json=autoFetchMaps"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *PreferencesSet) Reset() {
	*x = PreferencesSet{}
	mi := &file_whatevr_v2_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferencesSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferencesSet) ProtoMessage() {}

func (x *PreferencesSet) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PreferencesSet) GetNotifications() bool {
	if x != nil {
		return x.xxx_hidden_Notifications
	}
	return false
}

func (x *PreferencesSet) GetNotificationSound() bool {
	if x != nil {
		return x.xxx_hidden_NotificationSound
	}
	return false
}

func (x *PreferencesSet) GetNotificationPreview() bool {
	if x != nil {
		return x.xxx_hidden_NotificationPreview
	}
	return false
}

func (x *PreferencesSet) GetAutoDownloadPhotos() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadPhotos
	}
	return false
}

func (x *PreferencesSet) GetAutoDownloadVideos() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadVideos
	}
	return false
}

func (x *PreferencesSet) GetAutoDownloadAudio() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadAudio
	}
	return false
}

func (x *PreferencesSet) GetAutoDownloadDocuments() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadDocuments
	}
	return false
}

func (x *PreferencesSet) GetAutoDownloadStickers() bool {
	if x != nil {
		return x.xxx_hidden_AutoDownloadStickers
	}
	return false
}

func (x *PreferencesSet) GetAutoDownloadMaxBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_AutoDownloadMaxBytes
	}
	return 0
}

func (x *PreferencesSet) GetAutoFetchMaps() bool {
	if x != nil {
		return x.xxx_hidden_AutoFetchMaps
	}
	return false
}

func (x *PreferencesSet) SetNotifications(v bool) {
	x.xxx_hidden_Notifications = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *PreferencesSet) SetNotificationSound(v bool) {
	x.xxx_hidden_NotificationSound = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *PreferencesSet) SetNotificationPreview(v bool) {
	x.xxx_hidden_NotificationPreview = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *PreferencesSet) SetAutoDownloadPhotos(v bool) {
	x.xxx_hidden_AutoDownloadPhotos = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *PreferencesSet) SetAutoDownloadVideos(v bool) {
	x.xxx_hidden_AutoDownloadVideos = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *PreferencesSet) SetAutoDownloadAudio(v bool) {
	x.xxx_hidden_AutoDownloadAudio = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *PreferencesSet) SetAutoDownloadDocuments(v bool) {
	x.xxx_hidden_AutoDownloadDocuments = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *PreferencesSet) SetAutoDownloadStickers(v bool) {
	x.xxx_hidden_AutoDownloadStickers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *PreferencesSet) SetAutoDownloadMaxBytes(v uint64) {
	x.xxx_hidden_AutoDownloadMaxBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *PreferencesSet) SetAutoFetchMaps(v bool) {
	x.xxx_hidden_AutoFetchMaps = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *PreferencesSet) HasNotifications() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PreferencesSet) HasNotificationSound() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PreferencesSet) HasNotificationPreview() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PreferencesSet) HasAutoDownloadPhotos() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PreferencesSet) HasAutoDownloadVideos() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PreferencesSet) HasAutoDownloadAudio() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PreferencesSet) HasAutoDownloadDocuments() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *PreferencesSet) HasAutoDownloadStickers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *PreferencesSet) HasAutoDownloadMaxBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *PreferencesSet) HasAutoFetchMaps() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *PreferencesSet) ClearNotifications() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Notifications = false
}

func (x *PreferencesSet) ClearNotificationSound() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NotificationSound = false
}

func (x *PreferencesSet) ClearNotificationPreview() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NotificationPreview = false
}

func (x *PreferencesSet) ClearAutoDownloadPhotos() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AutoDownloadPhotos = false
}

func (x *PreferencesSet) ClearAutoDownloadVideos() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_AutoDownloadVideos = false
}

func (x *PreferencesSet) ClearAutoDownloadAudio() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_AutoDownloadAudio = false
}

func (x *PreferencesSet) ClearAutoDownloadDocuments() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_AutoDownloadDocuments = false
}

func (x *PreferencesSet) ClearAutoDownloadStickers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_AutoDownloadStickers = false
}

func (x *PreferencesSet) ClearAutoDownloadMaxBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_AutoDownloadMaxBytes = 0
}

func (x *PreferencesSet) ClearAutoFetchMaps() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_AutoFetchMaps = false
}

type PreferencesSet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Notifications         *bool
	NotificationSound     *bool
	NotificationPreview   *bool
	AutoDownloadPhotos    *bool
	AutoDownloadVideos    *bool
	AutoDownloadAudio     *bool
	AutoDownloadDocuments *bool
	AutoDownloadStickers  *bool
	AutoDownloadMaxBytes  *uint64
	AutoFetchMaps         *bool
}

func (b0 PreferencesSet_builder) Build() *PreferencesSet {
	m0 := &PreferencesSet{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Notifications != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Notifications = *b.Notifications
	}
	if b.NotificationSound != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_NotificationSound = *b.NotificationSound
	}
	if b.NotificationPreview != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_NotificationPreview = *b.NotificationPreview
	}
	if b.AutoDownloadPhotos != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_AutoDownloadPhotos = *b.AutoDownloadPhotos
	}
	if b.AutoDownloadVideos != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_AutoDownloadVideos = *b.AutoDownloadVideos
	}
	if b.AutoDownloadAudio != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_AutoDownloadAudio = *b.AutoDownloadAudio
	}
	if b.AutoDownloadDocuments != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_AutoDownloadDocuments = *b.AutoDownloadDocuments
	}
	if b.AutoDownloadStickers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_AutoDownloadStickers = *b.AutoDownloadStickers
	}
	if b.AutoDownloadMaxBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_AutoDownloadMaxBytes = *b.AutoDownloadMaxBytes
	}
	if b.AutoFetchMaps != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_AutoFetchMaps = *b.AutoFetchMaps
	}
	return m0
}

var File_whatevr_v2_settings_proto protoreflect.FileDescriptor

const file_whatevr_v2_settings_proto_rawDesc = "" +
	"\n" +
	"\x19whatevr/v2/settings.proto\x12\n" +
	"whatevr.v2\"\r\n" +
	"\vPrivacyView\"\xf5\x02\n" +
	"\n" +
	"PrivacyRow\x125\n" +
	"\tlast_seen\x18\x01 \x01(\x0e2\x18.whatevr.v2.PrivacyValueR\blastSeen\x120\n" +
	"\x06online\x18\x02 \x01(\x0e2\x18.whatevr.v2.PrivacyValueR\x06online\x12=\n" +
	"\rprofile_photo\x18\x03 \x01(\x0e2\x18.whatevr.v2.PrivacyValueR\fprofilePhoto\x12.\n" +
	"\x05about\x18\x04 \x01(\x0e2\x18.whatevr.v2.PrivacyValueR\x05about\x125\n" +
	"\tgroup_add\x18\x05 \x01(\x0e2\x18.whatevr.v2.PrivacyValueR\bgroupAdd\x123\n" +
	"\bcall_add\x18\x06 \x01(\x0e2\x18.whatevr.v2.PrivacyValueR\acallAdd\x12#\n" +
	"\rread_receipts\x18\a \x01(\bR\freadReceipts\"u\n" +
	"\n" +
	"PrivacySet\x127\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1b.whatevr.v2.PrivacyCategoryR\bcategory\x12.\n" +
	"\x05value\x18\x02 \x01(\x0e2\x18.whatevr.v2.PrivacyValueR\x05value\"\x11\n" +
	"\x0fPreferencesView\"K\n" +
	"\x0ePreferencesRow\x129\n" +
	"\vpreferences\x18\x01 \x01(\v2\x17.whatevr.v2.PreferencesR\vpreferences\"\xf6\x03\n" +
	"\vPreferences\x12$\n" +
	"\rnotifications\x18\x01 \x01(\bR\rnotifications\x12-\n" +
	"\x12notification_sound\x18\x02 \x01(\bR\x11notificationSound\x121\n" +
	"\x14notification_preview\x18\x03 \x01(\bR\x13notificationPreview\x120\n" +
	"\x14auto_download_photos\x18\x04 \x01(\bR\x12autoDownloadPhotos\x120\n" +
	"\x14auto_download_videos\x18\x05 \x01(\bR\x12autoDownloadVideos\x12.\n" +
	"\x13auto_download_audio\x18\x06 \x01(\bR\x11autoDownloadAudio\x126\n" +
	"\x17auto_download_documents\x18\a \x01(\bR\x15autoDownloadDocuments\x124\n" +
	"\x16auto_download_stickers\x18\b \x01(\bR\x14autoDownloadStickers\x125\n" +
	"\x17auto_download_max_bytes\x18\t \x01(\x04R\x14autoDownloadMaxBytes\x12&\n" +
	"\x0fauto_fetch_maps\x18\n" +
	" \x01(\bR\rautoFetchMaps\"\xbf\x04\n" +
	"\x0ePreferencesSet\x12+\n" +
	"\rnotifications\x18\x01 \x01(\bB\x05\xaa\x01\x02\b\x01R\rnotifications\x124\n" +
	"\x12notification_sound\x18\x02 \x01(\bB\x05\xaa\x01\x02\b\x01R\x11notificationSound\x128\n" +
	"\x14notification_preview\x18\x03 \x01(\bB\x05\xaa\x01\x02\b\x01R\x13notificationPreview\x127\n" +
	"\x14auto_download_photos\x18\x04 \x01(\bB\x05\xaa\x01\x02\b\x01R\x12autoDownloadPhotos\x127\n" +
	"\x14auto_download_videos\x18\x05 \x01(\bB\x05\xaa\x01\x02\b\x01R\x12autoDownloadVideos\x125\n" +
	"\x13auto_download_audio\x18\x06 \x01(\bB\x05\xaa\x01\x02\b\x01R\x11autoDownloadAudio\x12=\n" +
	"\x17auto_download_documents\x18\a \x01(\bB\x05\xaa\x01\x02\b\x01R\x15autoDownloadDocuments\x12;\n" +
	"\x16auto_download_stickers\x18\b \x01(\bB\x05\xaa\x01\x02\b\x01R\x14autoDownloadStickers\x12<\n" +
	"\x17auto_download_max_bytes\x18\t \x01(\x04B\x05\xaa\x01\x02\b\x01R\x14autoDownloadMaxBytes\x12-\n" +
	"\x0fauto_fetch_maps\x18\n" +
	" \x01(\bB\x05\xaa\x01\x02\b\x01R\rautoFetchMaps*\x93\x02\n" +
	"\x0fPrivacyCategory\x12 \n" +
	"\x1cPRIVACY_CATEGORY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPRIVACY_CATEGORY_LAST_SEEN\x10\x01\x12\x1b\n" +
	"\x17PRIVACY_CATEGORY_ONLINE\x10\x02\x12\"\n" +
	"\x1ePRIVACY_CATEGORY_PROFILE_PHOTO\x10\x03\x12\x1a\n" +
	"\x16PRIVACY_CATEGORY_ABOUT\x10\x04\x12\x1e\n" +
	"\x1aPRIVACY_CATEGORY_GROUP_ADD\x10\x05\x12\x1d\n" +
	"\x19PRIVACY_CATEGORY_CALL_ADD\x10\x06\x12\"\n" +
	"\x1ePRIVACY_CATEGORY_READ_RECEIPTS\x10\a*\xd9\x01\n" +
	"\fPrivacyValue\x12\x1d\n" +
	"\x19PRIVACY_VALUE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRIVACY_VALUE_ALL\x10\x01\x12\x1a\n" +
	"\x16PRIVACY_VALUE_CONTACTS\x10\x02\x12!\n" +
	"\x1dPRIVACY_VALUE_CONTACTS_EXCEPT\x10\x03\x12\x18\n" +
	"\x14PRIVACY_VALUE_NOBODY\x10\x04\x12!\n" +
	"\x1dPRIVACY_VALUE_MATCH_LAST_SEEN\x10\x05\x12\x17\n" +
	"\x13PRIVACY_VALUE_KNOWN\x10\x06B\xa2\x01\n" +
	"\x0ecom.whatevr.v2B\rSettingsProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_whatevr_v2_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_whatevr_v2_settings_proto_goTypes = []any{
	(PrivacyCategory)(0),    // 0: whatevr.v2.PrivacyCategory
	(PrivacyValue)(0),       // 1: whatevr.v2.PrivacyValue
	(*PrivacyView)(nil),     // 2: whatevr.v2.PrivacyView
	(*PrivacyRow)(nil),      // 3: whatevr.v2.PrivacyRow
	(*PrivacySet)(nil),      // 4: whatevr.v2.PrivacySet
	(*PreferencesView)(nil), // 5: whatevr.v2.PreferencesView
	(*PreferencesRow)(nil),  // 6: whatevr.v2.PreferencesRow
	(*Preferences)(nil),     // 7: whatevr.v2.Preferences
	(*PreferencesSet)(nil),  // 8: whatevr.v2.PreferencesSet
}
var file_whatevr_v2_settings_proto_depIdxs = []int32{
	1, // 0: whatevr.v2.PrivacyRow.last_seen:type_name -> whatevr.v2.PrivacyValue
	1, // 1: whatevr.v2.PrivacyRow.online:type_name -> whatevr.v2.PrivacyValue
	1, // 2: whatevr.v2.PrivacyRow.profile_photo:type_name -> whatevr.v2.PrivacyValue
	1, // 3: whatevr.v2.PrivacyRow.about:type_name -> whatevr.v2.PrivacyValue
	1, // 4: whatevr.v2.PrivacyRow.group_add:type_name -> whatevr.v2.PrivacyValue
	1, // 5: whatevr.v2.PrivacyRow.call_add:type_name -> whatevr.v2.PrivacyValue
	0, // 6: whatevr.v2.PrivacySet.category:type_name -> whatevr.v2.PrivacyCategory
	1, // 7: whatevr.v2.PrivacySet.value:type_name -> whatevr.v2.PrivacyValue
	7, // 8: whatevr.v2.PreferencesRow.preferences:type_name -> whatevr.v2.Preferences
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_whatevr_v2_settings_proto_init() }
func file_whatevr_v2_settings_proto_init() {
	if File_whatevr_v2_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_settings_proto_rawDesc), len(file_whatevr_v2_settings_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_settings_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_settings_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_settings_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_settings_proto_msgTypes,
	}.Build()
	File_whatevr_v2_settings_proto = out.File
	file_whatevr_v2_settings_proto_goTypes = nil
	file_whatevr_v2_settings_proto_depIdxs = nil
}
