// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whatevr/v2/stickers.proto

package whatevrv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StickerSource int32

const (
	StickerSource_STICKER_SOURCE_UNSPECIFIED StickerSource = 0
	StickerSource_STICKER_SOURCE_RECENT      StickerSource = 1
	StickerSource_STICKER_SOURCE_FAVORITE    StickerSource = 2
	StickerSource_STICKER_SOURCE_ALL         StickerSource = 3
)

// Enum value maps for StickerSource.
var (
	StickerSource_name = map[int32]string{
		0: "STICKER_SOURCE_UNSPECIFIED",
		1: "STICKER_SOURCE_RECENT",
		2: "STICKER_SOURCE_FAVORITE",
		3: "STICKER_SOURCE_ALL",
	}
	StickerSource_value = map[string]int32{
		"STICKER_SOURCE_UNSPECIFIED": 0,
		"STICKER_SOURCE_RECENT":      1,
		"STICKER_SOURCE_FAVORITE":    2,
		"STICKER_SOURCE_ALL":         3,
	}
)

func (x StickerSource) Enum() *StickerSource {
	p := new(StickerSource)
	*p = x
	return p
}

func (x StickerSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StickerSource) Descriptor() protoreflect.EnumDescriptor {
	return file_whatevr_v2_stickers_proto_enumTypes[0].Descriptor()
}

func (StickerSource) Type() protoreflect.EnumType {
	return &file_whatevr_v2_stickers_proto_enumTypes[0]
}

func (x StickerSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type StickersView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source StickerSource          `protobuf:"varint,1,opt,name=source,enum=whatevr.v2.StickerSource"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StickersView) Reset() {
	*x = StickersView{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickersView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickersView) ProtoMessage() {}

func (x *StickersView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StickersView) GetSource() StickerSource {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return StickerSource_STICKER_SOURCE_UNSPECIFIED
}

func (x *StickersView) SetSource(v StickerSource) {
	x.xxx_hidden_Source = v
}

type StickersView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Source StickerSource
}

func (b0 StickersView_builder) Build() *StickersView {
	m0 := &StickersView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Source = b.Source
	return m0
}

type StickerRow struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Path              string                 `protobuf:"bytes,2,opt,name=path"`
	xxx_hidden_Mime              string                 `protobuf:"bytes,3,opt,name=mime"`
	xxx_hidden_Animated          bool                   `protobuf:"varint,4,opt,name=animated"`
	xxx_hidden_Lottie            bool                   `protobuf:"varint,5,opt,name=lottie"`
	xxx_hidden_Width             uint32                 `protobuf:"varint,6,opt,name=width"`
	xxx_hidden_Height            uint32                 `protobuf:"varint,7,opt,name=height"`
	xxx_hidden_Emojis            []string               `protobuf:"bytes,8,rep,name=emojis"`
	xxx_hidden_AccessibilityText string                 `protobuf:"bytes,9,opt,name=accessibility_text,json=accessibilityText"`
	xxx_hidden_PackId            string                 `protobuf:"bytes,10,opt,name=pack_id,json=packId"`
	xxx_hidden_Favorite          bool                   `protobuf:"varint,11,opt,name=favorite"`
	xxx_hidden_LastUsedMs        int64                  `protobuf:"varint,12,opt,name=last_used_ms,json=lastUsedMs"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *StickerRow) Reset() {
	*x = StickerRow{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerRow) ProtoMessage() {}

func (x *StickerRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StickerRow) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *StickerRow) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *StickerRow) GetMime() string {
	if x != nil {
		return x.xxx_hidden_Mime
	}
	return ""
}

func (x *StickerRow) GetAnimated() bool {
	if x != nil {
		return x.xxx_hidden_Animated
	}
	return false
}

func (x *StickerRow) GetLottie() bool {
	if x != nil {
		return x.xxx_hidden_Lottie
	}
	return false
}

func (x *StickerRow) GetWidth() uint32 {
	if x != nil {
		return x.xxx_hidden_Width
	}
	return 0
}

func (x *StickerRow) GetHeight() uint32 {
	if x != nil {
		return x.xxx_hidden_Height
	}
	return 0
}

func (x *StickerRow) GetEmojis() []string {
	if x != nil {
		return x.xxx_hidden_Emojis
	}
	return nil
}

func (x *StickerRow) GetAccessibilityText() string {
	if x != nil {
		return x.xxx_hidden_AccessibilityText
	}
	return ""
}

func (x *StickerRow) GetPackId() string {
	if x != nil {
		return x.xxx_hidden_PackId
	}
	return ""
}

func (x *StickerRow) GetFavorite() bool {
	if x != nil {
		return x.xxx_hidden_Favorite
	}
	return false
}

func (x *StickerRow) GetLastUsedMs() int64 {
	if x != nil {
		return x.xxx_hidden_LastUsedMs
	}
	return 0
}

func (x *StickerRow) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *StickerRow) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *StickerRow) SetMime(v string) {
	x.xxx_hidden_Mime = v
}

func (x *StickerRow) SetAnimated(v bool) {
	x.xxx_hidden_Animated = v
}

func (x *StickerRow) SetLottie(v bool) {
	x.xxx_hidden_Lottie = v
}

func (x *StickerRow) SetWidth(v uint32) {
	x.xxx_hidden_Width = v
}

func (x *StickerRow) SetHeight(v uint32) {
	x.xxx_hidden_Height = v
}

func (x *StickerRow) SetEmojis(v []string) {
	x.xxx_hidden_Emojis = v
}

func (x *StickerRow) SetAccessibilityText(v string) {
	x.xxx_hidden_AccessibilityText = v
}

func (x *StickerRow) SetPackId(v string) {
	x.xxx_hidden_PackId = v
}

func (x *StickerRow) SetFavorite(v bool) {
	x.xxx_hidden_Favorite = v
}

func (x *StickerRow) SetLastUsedMs(v int64) {
	x.xxx_hidden_LastUsedMs = v
}

type StickerRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
	// empty until downloaded
	Path              string
	Mime              string
	Animated          bool
	Lottie            bool
	Width             uint32
	Height            uint32
	Emojis            []string
	AccessibilityText string
	PackId            string
	Favorite          bool
	LastUsedMs        int64
}

func (b0 StickerRow_builder) Build() *StickerRow {
	m0 := &StickerRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Mime = b.Mime
	x.xxx_hidden_Animated = b.Animated
	x.xxx_hidden_Lottie = b.Lottie
	x.xxx_hidden_Width = b.Width
	x.xxx_hidden_Height = b.Height
	x.xxx_hidden_Emojis = b.Emojis
	x.xxx_hidden_AccessibilityText = b.AccessibilityText
	x.xxx_hidden_PackId = b.PackId
	x.xxx_hidden_Favorite = b.Favorite
	x.xxx_hidden_LastUsedMs = b.LastUsedMs
	return m0
}

type StickerPacksView struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerPacksView) Reset() {
	*x = StickerPacksView{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerPacksView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerPacksView) ProtoMessage() {}

func (x *StickerPacksView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StickerPacksView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StickerPacksView_builder) Build() *StickerPacksView {
	m0 := &StickerPacksView{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// one pack's stickers; they land as the fetch resolves
type StickerPackView struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PackId string                 `protobuf:"bytes,1,opt,name=pack_id,json=packId"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StickerPackView) Reset() {
	*x = StickerPackView{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerPackView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerPackView) ProtoMessage() {}

func (x *StickerPackView) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StickerPackView) GetPackId() string {
	if x != nil {
		return x.xxx_hidden_PackId
	}
	return ""
}

func (x *StickerPackView) SetPackId(v string) {
	x.xxx_hidden_PackId = v
}

type StickerPackView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PackId string
}

func (b0 StickerPackView_builder) Build() *StickerPackView {
	m0 := &StickerPackView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PackId = b.PackId
	return m0
}

type StickerPackRow struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Publisher   string                 `protobuf:"bytes,3,opt,name=publisher"`
	xxx_hidden_Description string                 `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_Animated    bool                   `protobuf:"varint,5,opt,name=animated"`
	xxx_hidden_Lottie      bool                   `protobuf:"varint,6,opt,name=lottie"`
	xxx_hidden_TrayPath    string                 `protobuf:"bytes,7,opt,name=tray_path,json=trayPath"`
	xxx_hidden_Count       uint32                 `protobuf:"varint,8,opt,name=count"`
	xxx_hidden_Installed   bool                   `protobuf:"varint,9,opt,name=installed"`
	xxx_hidden_Fetched     bool                   `protobuf:"varint,10,opt,name=fetched"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StickerPackRow) Reset() {
	*x = StickerPackRow{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerPackRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerPackRow) ProtoMessage() {}

func (x *StickerPackRow) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StickerPackRow) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *StickerPackRow) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *StickerPackRow) GetPublisher() string {
	if x != nil {
		return x.xxx_hidden_Publisher
	}
	return ""
}

func (x *StickerPackRow) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *StickerPackRow) GetAnimated() bool {
	if x != nil {
		return x.xxx_hidden_Animated
	}
	return false
}

func (x *StickerPackRow) GetLottie() bool {
	if x != nil {
		return x.xxx_hidden_Lottie
	}
	return false
}

func (x *StickerPackRow) GetTrayPath() string {
	if x != nil {
		return x.xxx_hidden_TrayPath
	}
	return ""
}

func (x *StickerPackRow) GetCount() uint32 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *StickerPackRow) GetInstalled() bool {
	if x != nil {
		return x.xxx_hidden_Installed
	}
	return false
}

func (x *StickerPackRow) GetFetched() bool {
	if x != nil {
		return x.xxx_hidden_Fetched
	}
	return false
}

func (x *StickerPackRow) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *StickerPackRow) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *StickerPackRow) SetPublisher(v string) {
	x.xxx_hidden_Publisher = v
}

func (x *StickerPackRow) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *StickerPackRow) SetAnimated(v bool) {
	x.xxx_hidden_Animated = v
}

func (x *StickerPackRow) SetLottie(v bool) {
	x.xxx_hidden_Lottie = v
}

func (x *StickerPackRow) SetTrayPath(v string) {
	x.xxx_hidden_TrayPath = v
}

func (x *StickerPackRow) SetCount(v uint32) {
	x.xxx_hidden_Count = v
}

func (x *StickerPackRow) SetInstalled(v bool) {
	x.xxx_hidden_Installed = v
}

func (x *StickerPackRow) SetFetched(v bool) {
	x.xxx_hidden_Fetched = v
}

type StickerPackRow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          string
	Name        string
	Publisher   string
	Description string
	Animated    bool
	Lottie      bool
	TrayPath    string
	Count       uint32
	Installed   bool
	Fetched     bool
}

func (b0 StickerPackRow_builder) Build() *StickerPackRow {
	m0 := &StickerPackRow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Publisher = b.Publisher
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Animated = b.Animated
	x.xxx_hidden_Lottie = b.Lottie
	x.xxx_hidden_TrayPath = b.TrayPath
	x.xxx_hidden_Count = b.Count
	x.xxx_hidden_Installed = b.Installed
	x.xxx_hidden_Fetched = b.Fetched
	return m0
}

// a sticker is named by its id, or by a message carrying it
type StickerFavorite struct {
	state               protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Sticker  isStickerFavorite_Sticker `protobuf_oneof:"sticker"`
	xxx_hidden_Favorite bool                      `protobuf:"varint,3,opt,name=favorite"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StickerFavorite) Reset() {
	*x = StickerFavorite{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerFavorite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerFavorite) ProtoMessage() {}

func (x *StickerFavorite) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StickerFavorite) GetStickerId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Sticker.(*stickerFavorite_StickerId); ok {
			return x.StickerId
		}
	}
	return ""
}

func (x *StickerFavorite) GetMessageId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Sticker.(*stickerFavorite_MessageId); ok {
			return x.MessageId
		}
	}
	return ""
}

func (x *StickerFavorite) GetFavorite() bool {
	if x != nil {
		return x.xxx_hidden_Favorite
	}
	return false
}

func (x *StickerFavorite) SetStickerId(v string) {
	x.xxx_hidden_Sticker = &stickerFavorite_StickerId{v}
}

func (x *StickerFavorite) SetMessageId(v string) {
	x.xxx_hidden_Sticker = &stickerFavorite_MessageId{v}
}

func (x *StickerFavorite) SetFavorite(v bool) {
	x.xxx_hidden_Favorite = v
}

func (x *StickerFavorite) HasSticker() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sticker != nil
}

func (x *StickerFavorite) HasStickerId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Sticker.(*stickerFavorite_StickerId)
	return ok
}

func (x *StickerFavorite) HasMessageId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Sticker.(*stickerFavorite_MessageId)
	return ok
}

func (x *StickerFavorite) ClearSticker() {
	x.xxx_hidden_Sticker = nil
}

func (x *StickerFavorite) ClearStickerId() {
	if _, ok := x.xxx_hidden_Sticker.(*stickerFavorite_StickerId); ok {
		x.xxx_hidden_Sticker = nil
	}
}

func (x *StickerFavorite) ClearMessageId() {
	if _, ok := x.xxx_hidden_Sticker.(*stickerFavorite_MessageId); ok {
		x.xxx_hidden_Sticker = nil
	}
}

const StickerFavorite_Sticker_not_set_case case_StickerFavorite_Sticker = 0
const StickerFavorite_StickerId_case case_StickerFavorite_Sticker = 1
const StickerFavorite_MessageId_case case_StickerFavorite_Sticker = 2

func (x *StickerFavorite) WhichSticker() case_StickerFavorite_Sticker {
	if x == nil {
		return StickerFavorite_Sticker_not_set_case
	}
	switch x.xxx_hidden_Sticker.(type) {
	case *stickerFavorite_StickerId:
		return StickerFavorite_StickerId_case
	case *stickerFavorite_MessageId:
		return StickerFavorite_MessageId_case
	default:
		return StickerFavorite_Sticker_not_set_case
	}
}

type StickerFavorite_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Sticker:
	StickerId *string
	MessageId *string
	// -- end of xxx_hidden_Sticker
	Favorite bool
}

func (b0 StickerFavorite_builder) Build() *StickerFavorite {
	m0 := &StickerFavorite{}
	b, x := &b0, m0
	_, _ = b, x
	if b.StickerId != nil {
		x.xxx_hidden_Sticker = &stickerFavorite_StickerId{*b.StickerId}
	}
	if b.MessageId != nil {
		x.xxx_hidden_Sticker = &stickerFavorite_MessageId{*b.MessageId}
	}
	x.xxx_hidden_Favorite = b.Favorite
	return m0
}

type case_StickerFavorite_Sticker protoreflect.FieldNumber

func (x case_StickerFavorite_Sticker) String() string {
	md := file_whatevr_v2_stickers_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStickerFavorite_Sticker interface {
	isStickerFavorite_Sticker()
}

type stickerFavorite_StickerId struct {
	StickerId string `protobuf:"bytes,1,opt,name=sticker_id,json=stickerId,oneof"`
}

type stickerFavorite_MessageId struct {
	MessageId string `protobuf:"bytes,2,opt,name=message_id,json=messageId,oneof"`
}

func (*stickerFavorite_StickerId) isStickerFavorite_Sticker() {}

func (*stickerFavorite_MessageId) isStickerFavorite_Sticker() {}

// lands through stickers and sticker_pack upserts
type StickerDownload struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StickerId string                 `protobuf:"bytes,1,opt,name=sticker_id,json=stickerId"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StickerDownload) Reset() {
	*x = StickerDownload{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerDownload) ProtoMessage() {}

func (x *StickerDownload) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StickerDownload) GetStickerId() string {
	if x != nil {
		return x.xxx_hidden_StickerId
	}
	return ""
}

func (x *StickerDownload) SetStickerId(v string) {
	x.xxx_hidden_StickerId = v
}

type StickerDownload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	StickerId string
}

func (b0 StickerDownload_builder) Build() *StickerDownload {
	m0 := &StickerDownload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StickerId = b.StickerId
	return m0
}

type StickerPackInstall struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PackId    string                 `protobuf:"bytes,1,opt,name=pack_id,json=packId"`
	xxx_hidden_Installed bool                   `protobuf:"varint,2,opt,name=installed"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StickerPackInstall) Reset() {
	*x = StickerPackInstall{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerPackInstall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerPackInstall) ProtoMessage() {}

func (x *StickerPackInstall) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StickerPackInstall) GetPackId() string {
	if x != nil {
		return x.xxx_hidden_PackId
	}
	return ""
}

func (x *StickerPackInstall) GetInstalled() bool {
	if x != nil {
		return x.xxx_hidden_Installed
	}
	return false
}

func (x *StickerPackInstall) SetPackId(v string) {
	x.xxx_hidden_PackId = v
}

func (x *StickerPackInstall) SetInstalled(v bool) {
	x.xxx_hidden_Installed = v
}

type StickerPackInstall_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PackId    string
	Installed bool
}

func (b0 StickerPackInstall_builder) Build() *StickerPackInstall {
	m0 := &StickerPackInstall{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PackId = b.PackId
	x.xxx_hidden_Installed = b.Installed
	return m0
}

// fetches the store's packs again
type StickerPacksRefresh struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerPacksRefresh) Reset() {
	*x = StickerPacksRefresh{}
	mi := &file_whatevr_v2_stickers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerPacksRefresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerPacksRefresh) ProtoMessage() {}

func (x *StickerPacksRefresh) ProtoReflect() protoreflect.Message {
	mi := &file_whatevr_v2_stickers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StickerPacksRefresh_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StickerPacksRefresh_builder) Build() *StickerPacksRefresh {
	m0 := &StickerPacksRefresh{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_whatevr_v2_stickers_proto protoreflect.FileDescriptor

const file_whatevr_v2_stickers_proto_rawDesc = "" +
	"\n" +
	"\x19whatevr/v2/stickers.proto\x12\n" +
	"whatevr.v2\"A\n" +
	"\fStickersView\x121\n" +
	"\x06source\x18\x01 \x01(\x0e2\x19.whatevr.v2.StickerSourceR\x06source\"\xc4\x02\n" +
	"\n" +
	"StickerRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x1a\n" +
	"\banimated\x18\x04 \x01(\bR\banimated\x12\x16\n" +
	"\x06lottie\x18\x05 \x01(\bR\x06lottie\x12\x14\n" +
	"\x05width\x18\x06 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\rR\x06height\x12\x16\n" +
	"\x06emojis\x18\b \x03(\tR\x06emojis\x12-\n" +
	"\x12accessibility_text\x18\t \x01(\tR\x11accessibilityText\x12\x17\n" +
	"\apack_id\x18\n" +
	" \x01(\tR\x06packId\x12\x1a\n" +
	"\bfavorite\x18\v \x01(\bR\bfavorite\x12 \n" +
	"\flast_used_ms\x18\f \x01(\x03R\n" +
	"lastUsedMs\"\x12\n" +
	"\x10StickerPacksView\"*\n" +
	"\x0fStickerPackView\x12\x17\n" +
	"\apack_id\x18\x01 \x01(\tR\x06packId\"\x93\x02\n" +
	"\x0eStickerPackRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\banimated\x18\x05 \x01(\bR\banimated\x12\x16\n" +
	"\x06lottie\x18\x06 \x01(\bR\x06lottie\x12\x1b\n" +
	"\ttray_path\x18\a \x01(\tR\btrayPath\x12\x14\n" +
	"\x05count\x18\b \x01(\rR\x05count\x12\x1c\n" +
	"\tinstalled\x18\t \x01(\bR\tinstalled\x12\x18\n" +
	"\afetched\x18\n" +
	" \x01(\bR\afetched\"z\n" +
	"\x0fStickerFavorite\x12\x1f\n" +
	"\n" +
	"sticker_id\x18\x01 \x01(\tH\x00R\tstickerId\x12\x1f\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tH\x00R\tmessageId\x12\x1a\n" +
	"\bfavorite\x18\x03 \x01(\bR\bfavoriteB\t\n" +
	"\asticker\"0\n" +
	"\x0fStickerDownload\x12\x1d\n" +
	"\n" +
	"sticker_id\x18\x01 \x01(\tR\tstickerId\"K\n" +
	"\x12StickerPackInstall\x12\x17\n" +
	"\apack_id\x18\x01 \x01(\tR\x06packId\x12\x1c\n" +
	"\tinstalled\x18\x02 \x01(\bR\tinstalled\"\x15\n" +
	"\x13StickerPacksRefresh*\x7f\n" +
	"\rStickerSource\x12\x1e\n" +
	"\x1aSTICKER_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STICKER_SOURCE_RECENT\x10\x01\x12\x1b\n" +
	"\x17STICKER_SOURCE_FAVORITE\x10\x02\x12\x16\n" +
	"\x12STICKER_SOURCE_ALL\x10\x03B\xa2\x01\n" +
	"\x0ecom.whatevr.v2B\rStickersProtoZ5github.com/codelif/whatevr/proto/whatevr/v2;whatevrv2\xa2\x02\x03WXX\xaa\x02\n" +
	"Whatevr.V2\xca\x02\n" +
	"Whatevr\\V2\xe2\x02\x16Whatevr\\V2\\GPBMetadata\xea\x02\vWhatevr::V2\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_whatevr_v2_stickers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whatevr_v2_stickers_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_whatevr_v2_stickers_proto_goTypes = []any{
	(StickerSource)(0),          // 0: whatevr.v2.StickerSource
	(*StickersView)(nil),        // 1: whatevr.v2.StickersView
	(*StickerRow)(nil),          // 2: whatevr.v2.StickerRow
	(*StickerPacksView)(nil),    // 3: whatevr.v2.StickerPacksView
	(*StickerPackView)(nil),     // 4: whatevr.v2.StickerPackView
	(*StickerPackRow)(nil),      // 5: whatevr.v2.StickerPackRow
	(*StickerFavorite)(nil),     // 6: whatevr.v2.StickerFavorite
	(*StickerDownload)(nil),     // 7: whatevr.v2.StickerDownload
	(*StickerPackInstall)(nil),  // 8: whatevr.v2.StickerPackInstall
	(*StickerPacksRefresh)(nil), // 9: whatevr.v2.StickerPacksRefresh
}
var file_whatevr_v2_stickers_proto_depIdxs = []int32{
	0, // 0: whatevr.v2.StickersView.source:type_name -> whatevr.v2.StickerSource
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_whatevr_v2_stickers_proto_init() }
func file_whatevr_v2_stickers_proto_init() {
	if File_whatevr_v2_stickers_proto != nil {
		return
	}
	file_whatevr_v2_stickers_proto_msgTypes[5].OneofWrappers = []any{
		(*stickerFavorite_StickerId)(nil),
		(*stickerFavorite_MessageId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatevr_v2_stickers_proto_rawDesc), len(file_whatevr_v2_stickers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whatevr_v2_stickers_proto_goTypes,
		DependencyIndexes: file_whatevr_v2_stickers_proto_depIdxs,
		EnumInfos:         file_whatevr_v2_stickers_proto_enumTypes,
		MessageInfos:      file_whatevr_v2_stickers_proto_msgTypes,
	}.Build()
	File_whatevr_v2_stickers_proto = out.File
	file_whatevr_v2_stickers_proto_goTypes = nil
	file_whatevr_v2_stickers_proto_depIdxs = nil
}
