package wa

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/jpeg"
	_ "image/png"
	"math"
	"net/http"
	"os"
	"strings"
	"time"

	"go.mau.fi/util/random"
	"go.mau.fi/whatsmeow"
	"go.mau.fi/whatsmeow/proto/waCommon"
	"go.mau.fi/whatsmeow/proto/waE2E"
	"go.mau.fi/whatsmeow/types"
	"go.mau.fi/whatsmeow/types/events"

	"whatevrd/internal/app"
)

// Development-only message injection, reachable through the daemon's
// `dev.send_raw` command and only when WHATEVR_DEV_COMMANDS=1. It is not part of
// PROTOCOL.md and never registered otherwise.
//
// Section 1 of feature-gap.md is about *receiving*, and the only way to exercise
// the receive path is for something to send. Waiting on a second handset for
// every kind, every time an ingest changes, is not a development loop. This
// builds the waE2E proto WhatsApp would have delivered and pushes it through the
// real handler, so decode, storage, wire encoding and rendering are all the
// production code.

// RawSendRequest is one injected message.
type RawSendRequest struct {
	ChatID string          `json:"chat_id"`
	Kind   string          `json:"kind"`
	Params json.RawMessage `json:"params"`
	// Local injects the message as if it had arrived from the peer, without
	// touching the network. This is the mode that actually tests the receive
	// path, and it costs the peer nothing.
	Local bool `json:"local"`
	// Incoming decides the direction a real send is ingested under. It has no
	// effect in Local mode, where the message is always incoming.
	Incoming bool `json:"incoming"`
}

// rawMessageBuilder turns the command's free-form params into the proto
// WhatsApp would carry. Each phase that teaches the ingest a new kind registers
// its builder here in the same commit, so there is never a kind the ingest
// understands and the test driver cannot produce.
// The daemon's own client is handed in because some kinds cannot be built
// without it: a poll's message secret, which its votes are encrypted against,
// is generated by whatsmeow and belongs to the sending client, and an event
// response has to be sealed against the event it answers.
type rawMessageBuilder func(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error)

var rawMessageBuilders = map[string]rawMessageBuilder{
	"text":          buildRawText,
	"location":      buildRawLocation,
	"live_location": buildRawLiveLocation,
	"live_update":   buildRawLiveLocationUpdate,
	"contact":       buildRawContact,
	"contacts":      buildRawContacts,
	"poll":          buildRawPoll,
	"group_invite":  buildRawGroupInvite,
	"event":         buildRawEvent,
	"event_rsvp":    buildRawEventRSVP,
	"link_preview":  buildRawLinkPreview,
}

// rawSequenceBuilder produces a kind that is not one message. An album is a
// header plus a message per picture, and the pictures only mean anything
// alongside it, so the driver has to be able to produce the whole thing: a
// header sent on its own is exactly the degenerate case, not the feature.
//
// It gets the chat because a picture has to be uploaded before it can be sent,
// and the whole request because a local injection must not touch the network.
type rawSequenceBuilder func(ctx context.Context, c *Client, chatJID types.JID, req RawSendRequest) ([]*waE2E.Message, error)

var rawSequenceBuilders = map[string]rawSequenceBuilder{
	"album": buildRawAlbum,
}

// RawSendKinds lists what the driver can produce, for the tool's help output.
func RawSendKinds() []string {
	kinds := make([]string, 0, len(rawMessageBuilders)+len(rawSequenceBuilders))
	for kind := range rawMessageBuilders {
		kinds = append(kinds, kind)
	}
	for kind := range rawSequenceBuilders {
		kinds = append(kinds, kind)
	}
	return kinds
}

// SendRawMessage builds the named kind and either injects it locally or really
// sends it. It returns the internal message id of the row that resulted (the
// header's, for a kind that is several messages), so a caller can watch for
// that exact upsert.
func (c *Client) SendRawMessage(ctx context.Context, req RawSendRequest) (string, error) {
	client := c.currentClient()
	if client == nil || !client.IsLoggedIn() {
		return "", app.NewCommandError(app.CommandErrorNotLoggedIn, "not logged in")
	}
	chatJID, err := types.ParseJID(req.ChatID)
	if err != nil {
		return "", app.NewCommandError(app.CommandErrorInvalidArgument, "invalid chat_id: %v", err)
	}
	chatJID = c.normalizeJIDForChat(ctx, chatJID)

	var messages []*waE2E.Message
	switch {
	case rawMessageBuilders[req.Kind] != nil:
		message, err := rawMessageBuilders[req.Kind](ctx, c, req.Params)
		if err != nil {
			return "", app.NewCommandError(app.CommandErrorInvalidArgument, "build %s: %v", req.Kind, err)
		}
		messages = []*waE2E.Message{message}
	case rawSequenceBuilders[req.Kind] != nil:
		messages, err = rawSequenceBuilders[req.Kind](ctx, c, chatJID, req)
		if err != nil {
			return "", app.NewCommandError(app.CommandErrorInvalidArgument, "build %s: %v", req.Kind, err)
		}
	default:
		return "", app.NewCommandError(app.CommandErrorInvalidArgument, "no raw builder for kind %q", req.Kind)
	}

	fromMe := !req.Local && !req.Incoming
	headerID := ""
	for i, message := range messages {
		// Every message after the first is part of the first: an album's
		// pictures name their header, and the header's id only exists once it
		// has been generated. Filling the association in here rather than in
		// the builder is what lets the builder stay a pure description.
		if i > 0 {
			linkToRawParent(message, chatJID, messages[0], headerID, fromMe, i-1)
		}
		id, err := c.deliverRawMessage(ctx, client, chatJID, message, req, fromMe)
		if err != nil {
			return "", err
		}
		if i == 0 {
			headerID = id
		}
	}
	return internalMessageIDForChat(chatJID.String(), types.MessageID(headerID)), nil
}

// deliverRawMessage sends one built message (or skips the network in local
// mode) and runs it through the real inbound handler, returning its id.
func (c *Client) deliverRawMessage(ctx context.Context, client *whatsmeow.Client, chatJID types.JID, message *waE2E.Message, req RawSendRequest, fromMe bool) (string, error) {
	messageID := client.GenerateMessageID()
	sentAt := time.Now()

	if !req.Local {
		resp, err := client.SendMessage(ctx, chatJID, message, whatsmeow.SendRequestExtra{ID: messageID})
		if err != nil {
			return "", app.NewCommandError(app.CommandErrorRejected, "send %s: %v", req.Kind, err)
		}
		if !resp.Timestamp.IsZero() {
			sentAt = resp.Timestamp
		}
	}

	evt := &events.Message{
		Info: types.MessageInfo{
			MessageSource: types.MessageSource{
				Chat:     chatJID,
				Sender:   c.rawSendSender(chatJID, fromMe),
				IsFromMe: fromMe,
				IsGroup:  chatJID.Server == types.GroupServer,
			},
			ID:        messageID,
			Timestamp: sentAt,
			PushName:  "Raw send",
		},
		Message: message,
	}

	// A real inbound message has its message secret stored by whatsmeow before
	// our handler ever sees it, and a real outbound one has it stored by the
	// send path. A locally injected message goes through neither, so without
	// this a poll injected with -local could never have a vote encrypted
	// against it and the whole two-way path would be untestable offline.
	c.storeBackfilledMessageSecret(ctx, evt)

	c.handleMessage(ctx, evt, false)
	return string(messageID), nil
}

// linkToRawParent points a follower at the message it belongs to, which for an
// album is the header its pictures hang off.
func linkToRawParent(message *waE2E.Message, chatJID types.JID, parent *waE2E.Message, parentID string, fromMe bool, index int) {
	if parent.GetAlbumMessage() == nil || parentID == "" {
		return
	}
	if message.MessageContextInfo == nil {
		message.MessageContextInfo = &waE2E.MessageContextInfo{}
	}
	message.MessageContextInfo.MessageAssociation = &waE2E.MessageAssociation{
		AssociationType: waE2E.MessageAssociation_MEDIA_ALBUM.Enum(),
		ParentMessageKey: &waCommon.MessageKey{
			RemoteJID: ptrTo(chatJID.String()),
			FromMe:    &fromMe,
			ID:        &parentID,
		},
		MessageIndex: ptrTo(int32(index)),
	}
}

// rawSendSender picks a plausible sender for the injected event: ourselves for
// an outgoing copy, otherwise the peer in a direct chat or the chat itself in a
// group, which is what a real participant JID would resolve through anyway.
func (c *Client) rawSendSender(chatJID types.JID, fromMe bool) types.JID {
	if fromMe {
		if client := c.currentClient(); client != nil {
			if own := client.Store.GetJID(); !own.IsEmpty() {
				return own.ToNonAD()
			}
		}
	}
	return chatJID
}

func buildRawText(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		Text string `json:"text"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	if p.Text == "" {
		p.Text = "raw send"
	}
	return &waE2E.Message{Conversation: &p.Text}, nil
}

// buildRawLinkPreview produces the ExtendedTextMessage a client sends when it
// found a link in what somebody typed and fetched a card for it. The card is
// entirely the sender's: everything the receiving side will render arrives
// inline, which is what makes the preview cost the reader no request.
func buildRawLinkPreview(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		Text        string `json:"text"`
		URL         string `json:"url"`
		Title       string `json:"title"`
		Description string `json:"description"`
		// Type is "video", "image" or empty, matching the wire vocabulary. The
		// first two are what a large card is for.
		Type string `json:"type"`
		// NoThumb produces the case that has no picture at all, which is the
		// layout a plain article link actually gets.
		NoThumb bool `json:"no_thumb"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}

	if p.URL == "" {
		p.URL = "https://en.wikipedia.org/wiki/Bengaluru"
		if p.Title == "" {
			p.Title = "Bengaluru"
		}
		if p.Description == "" {
			p.Description = "Capital of the Indian state of Karnataka, and the centre of its technology industry."
		}
	}
	if p.Text == "" {
		p.Text = p.URL
	}

	preview := waE2E.ExtendedTextMessage_NONE
	switch p.Type {
	case "video":
		preview = waE2E.ExtendedTextMessage_VIDEO
	case "image":
		preview = waE2E.ExtendedTextMessage_IMAGE
	}

	extended := &waE2E.ExtendedTextMessage{
		Text:        &p.Text,
		MatchedText: &p.URL,
		Title:       &p.Title,
		Description: &p.Description,
		PreviewType: &preview,
	}

	if !p.NoThumb {
		// A landscape still for the layouts that show one big, a square for the
		// compact row, so each params combination produces the shape its layout
		// is actually for.
		shape := 2
		if preview != waE2E.ExtendedTextMessage_NONE {
			shape = 0
		}
		picture, err := generateTestPicture(shape, 4)
		if err != nil {
			return nil, err
		}
		extended.JPEGThumbnail = outgoingImageThumbnail(picture)
	}

	return &waE2E.Message{ExtendedTextMessage: extended}, nil
}

// rawLocationParams covers all three location shapes; a builder ignores the
// fields its shape has no room for.
type rawLocationParams struct {
	Lat      float64 `json:"lat"`
	Lng      float64 `json:"lng"`
	Name     string  `json:"name"`
	Address  string  `json:"address"`
	URL      string  `json:"url"`
	Comment  string  `json:"comment"`
	Accuracy uint32  `json:"accuracy_m"`
	Speed    float32 `json:"speed_mps"`
	Heading  uint32  `json:"heading_deg"`
	Sequence int64   `json:"seq"`
}

// defaulted fills in a recognisable place when the caller gave no coordinates,
// so `wa-testsend -chat ... location` with no params still does something.
func (p rawLocationParams) defaulted() rawLocationParams {
	if p.Lat == 0 && p.Lng == 0 {
		p.Lat, p.Lng = 12.9716, 77.5946
		if p.Name == "" {
			p.Name = "Bengaluru"
		}
	}
	return p
}

func buildRawLocation(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p rawLocationParams
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	p = p.defaulted()
	return &waE2E.Message{LocationMessage: &waE2E.LocationMessage{
		DegreesLatitude:  &p.Lat,
		DegreesLongitude: &p.Lng,
		Name:             &p.Name,
		Address:          &p.Address,
		URL:              &p.URL,
		Comment:          &p.Comment,
		AccuracyInMeters: &p.Accuracy,
	}}, nil
}

func buildRawLiveLocation(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	message, err := buildRawLocation(ctx, c, params)
	if err != nil {
		return nil, err
	}
	live := true
	message.LocationMessage.IsLive = &live
	return message, nil
}

// buildRawLiveLocationUpdate is a position update for a share already open,
// which is the only way to exercise the correlation whatsmeow gives us nothing
// for.
func buildRawLiveLocationUpdate(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p rawLocationParams
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	p = p.defaulted()
	return &waE2E.Message{LiveLocationMessage: &waE2E.LiveLocationMessage{
		DegreesLatitude:                   &p.Lat,
		DegreesLongitude:                  &p.Lng,
		AccuracyInMeters:                  &p.Accuracy,
		SpeedInMps:                        &p.Speed,
		DegreesClockwiseFromMagneticNorth: &p.Heading,
		SequenceNumber:                    &p.Sequence,
	}}, nil
}

// rawContactParams builds a vCard the way WhatsApp does, `waid=` and all, so
// the parser is exercised on the shape it will really meet.
type rawContactParams struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
	// WaID marks the number as being on WhatsApp, which is what makes the
	// card's Message action live.
	WaID  string `json:"waid"`
	Email string `json:"email"`
	Org   string `json:"org"`
	Title string `json:"title"`
	// Count repeats the card, for testing the multi-card array shape.
	Count int `json:"count"`
}

func (p rawContactParams) vcard(index int) string {
	name := p.Name
	if name == "" {
		name = "Test Contact"
	}
	if index > 0 {
		name = fmt.Sprintf("%s %d", name, index+1)
	}
	phone := p.Phone
	if phone == "" {
		phone = "+91 70600 29183"
	}
	waid := p.WaID
	if waid == "" {
		waid = strings.NewReplacer("+", "", " ", "", "-", "").Replace(phone)
	}

	var b strings.Builder
	b.WriteString("BEGIN:VCARD\nVERSION:3.0\n")
	fmt.Fprintf(&b, "N:;%s;;;\nFN:%s\n", name, name)
	if p.Org != "" {
		fmt.Fprintf(&b, "ORG:%s;\n", p.Org)
	}
	if p.Title != "" {
		fmt.Fprintf(&b, "TITLE:%s\n", p.Title)
	}
	fmt.Fprintf(&b, "item1.TEL;waid=%s:%s\nitem1.X-ABLabel:Mobile\n", waid, phone)
	if p.Email != "" {
		fmt.Fprintf(&b, "item2.EMAIL;type=INTERNET:%s\nitem2.X-ABLabel:Work\n", p.Email)
	}
	b.WriteString("END:VCARD")
	return b.String()
}

func buildRawContact(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p rawContactParams
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	name := p.Name
	if name == "" {
		name = "Test Contact"
	}
	vcard := p.vcard(0)
	return &waE2E.Message{ContactMessage: &waE2E.ContactMessage{
		DisplayName: &name,
		Vcard:       &vcard,
	}}, nil
}

func buildRawContacts(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p rawContactParams
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	count := p.Count
	if count <= 0 {
		count = 3
	}
	contacts := make([]*waE2E.ContactMessage, 0, count)
	for i := range count {
		name := p.Name
		if name == "" {
			name = "Test Contact"
		}
		name = fmt.Sprintf("%s %d", name, i+1)
		vcard := p.vcard(i)
		contacts = append(contacts, &waE2E.ContactMessage{DisplayName: &name, Vcard: &vcard})
	}
	label := "Shared contacts"
	return &waE2E.Message{ContactsArrayMessage: &waE2E.ContactsArrayMessage{
		DisplayName: &label,
		Contacts:    contacts,
	}}, nil
}

func buildRawPoll(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		Question string   `json:"question"`
		Options  []string `json:"options"`
		// Selectable is how many answers a voter may pick; 1 is the usual poll.
		Selectable int  `json:"selectable"`
		AllowAdd   bool `json:"allow_add"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	if p.Question == "" {
		p.Question = "dinner?"
	}
	if len(p.Options) == 0 {
		p.Options = []string{"Thai", "Pizza", "Sushi"}
	}
	if p.Selectable <= 0 {
		p.Selectable = 1
	}

	// BuildPollCreation generates the message secret the votes are encrypted
	// against and leaves the option hashes empty, exactly as a real client
	// does, so the ingest is exercised on the real shape.
	message := c.currentClient().BuildPollCreation(p.Question, p.Options, p.Selectable)
	if poll := pollCreationFromMessage(message); poll != nil {
		poll.AllowAddOption = &p.AllowAdd
	}
	return message, nil
}

// buildRawGroupInvite offers a group.
//
// With no code given it asks WhatsApp for the group's real invite link, which
// is what makes the resolution path testable at all: an invite whose code is
// made up can only ever exercise the failure branch. Pass one explicitly (any
// string will do) to get that branch back, which is the state a revoked invite
// lands in.
func buildRawGroupInvite(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		GroupJID string `json:"group_jid"`
		Code     string `json:"code"`
		Name     string `json:"name"`
		Caption  string `json:"caption"`
		// ExpiresIn is seconds from now; negative injects an invite that has
		// already lapsed.
		ExpiresIn int64 `json:"expires_in"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	if p.GroupJID == "" {
		return nil, fmt.Errorf("group_jid is required")
	}
	groupJID, err := types.ParseJID(p.GroupJID)
	if err != nil {
		return nil, fmt.Errorf("invalid group_jid: %w", err)
	}
	if p.Code == "" {
		link, err := c.currentClient().GetGroupInviteLink(ctx, groupJID, false)
		if err != nil {
			return nil, fmt.Errorf("fetch invite link for %s: %w", groupJID, err)
		}
		// The link is https://chat.whatsapp.com/<code>; the message carries the
		// code alone.
		p.Code = link[strings.LastIndex(link, "/")+1:]
	}
	if p.Name == "" {
		p.Name = "Test group"
	}
	if p.ExpiresIn == 0 {
		p.ExpiresIn = int64(3 * 24 * time.Hour / time.Second)
	}
	expiration := time.Now().Add(time.Duration(p.ExpiresIn) * time.Second).Unix()
	return &waE2E.Message{GroupInviteMessage: &waE2E.GroupInviteMessage{
		GroupJID:         &p.GroupJID,
		InviteCode:       &p.Code,
		InviteExpiration: &expiration,
		GroupName:        &p.Name,
		Caption:          &p.Caption,
	}}, nil
}

// buildRawEvent schedules something. With a venue it exercises the map path as
// well, which is the same path a shared place takes.
func buildRawEvent(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		Name        string `json:"name"`
		Description string `json:"description"`
		// StartsIn is seconds from now; negative schedules something past.
		StartsIn int64 `json:"starts_in"`
		// LastsFor is seconds, 0 for an event with no stated end.
		LastsFor    int64   `json:"lasts_for"`
		JoinLink    string  `json:"join_link"`
		Lat         float64 `json:"lat"`
		Lng         float64 `json:"lng"`
		PlaceName   string  `json:"place_name"`
		Address     string  `json:"address"`
		Canceled    bool    `json:"canceled"`
		ExtraGuests bool    `json:"extra_guests"`
		Call        bool    `json:"call"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	if p.Name == "" {
		p.Name = "Team dinner"
	}
	if p.StartsIn == 0 {
		p.StartsIn = int64(26 * time.Hour / time.Second)
	}
	start := time.Now().Add(time.Duration(p.StartsIn) * time.Second).Unix()

	event := &waE2E.EventMessage{
		Name:               &p.Name,
		Description:        &p.Description,
		StartTime:          &start,
		IsCanceled:         &p.Canceled,
		ExtraGuestsAllowed: &p.ExtraGuests,
		IsScheduleCall:     &p.Call,
	}
	if p.LastsFor > 0 {
		end := start + p.LastsFor
		event.EndTime = &end
	}
	if p.JoinLink != "" {
		event.JoinLink = &p.JoinLink
	}
	if p.Lat != 0 || p.Lng != 0 {
		event.Location = &waE2E.LocationMessage{
			DegreesLatitude:  &p.Lat,
			DegreesLongitude: &p.Lng,
			Name:             &p.PlaceName,
			Address:          &p.Address,
		}
	}

	// An event's RSVPs are encrypted against its message secret, exactly as a
	// poll's votes are, so an injected event without one could never be
	// answered and the two-way path would be untestable.
	message := &waE2E.Message{
		EventMessage: event,
		MessageContextInfo: &waE2E.MessageContextInfo{
			MessageSecret: random.Bytes(32),
		},
	}
	return message, nil
}

// buildRawEventRSVP answers an event that is already in the chat.
//
// This is the one builder that exists to test the daemon against itself: the
// event-response encryption is ours to maintain rather than whatsmeow's (see
// msgsecret_event.go), and injecting a sealed answer back through the real
// ingest is what proves the encrypt and decrypt halves of that derivation
// actually agree. Inject it with -local to run the whole round trip offline.
func buildRawEventRSVP(ctx context.Context, c *Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		// MessageID is the event's internal id, as `event` returned it.
		MessageID   string `json:"message_id"`
		Response    string `json:"response"`
		ExtraGuests int32  `json:"extra_guests"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	if p.MessageID == "" {
		return nil, fmt.Errorf("message_id of the event is required")
	}
	if p.Response == "" {
		p.Response = "going"
	}
	responseType, ok := eventResponseType(p.Response)
	if !ok {
		return nil, fmt.Errorf("unknown response %q", p.Response)
	}

	message, err := c.store.GetMessage(ctx, p.MessageID)
	if err != nil {
		return nil, fmt.Errorf("no event %s: %w", p.MessageID, err)
	}
	eventInfo, err := c.eventMessageInfo(message)
	if err != nil {
		return nil, err
	}
	// Sealed as whoever the injection will present as the sender, which for a
	// local injection is the peer rather than us. Sealing as ourselves and
	// ingesting as them is exactly the mismatch this builder exists to catch.
	chatJID, err := types.ParseJID(message.ChatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat id %q: %w", message.ChatID, err)
	}
	return c.encryptEventResponse(ctx, eventInfo, c.rawSendSender(chatJID, false), &waE2E.EventResponseMessage{
		Response:        responseType.Enum(),
		TimestampMS:     ptrTo(time.Now().UnixMilli()),
		ExtraGuestCount: &p.ExtraGuests,
	})
}

// buildRawAlbum produces a whole album: the header, then one picture per tile
// naming it.
//
// Pictures are generated rather than required, because the thing being tested
// is the mosaic and a mosaic needs tiles of different shapes to be worth
// looking at. Give it `images` to send real files instead.
func buildRawAlbum(ctx context.Context, c *Client, chatJID types.JID, req RawSendRequest) ([]*waE2E.Message, error) {
	var p struct {
		// Count is how many pictures to generate when none are given.
		Count int `json:"count"`
		// Images are local file paths to send as the tiles.
		Images []string `json:"images"`
		// Captions run alongside the tiles; a short list leaves the rest bare.
		Captions []string `json:"captions"`
		// Short claims more pictures than are sent, so a half-arrived album can
		// be looked at without racing the network to catch one.
		Short int `json:"short"`
	}
	if err := decodeRawParams(req.Params, &p); err != nil {
		return nil, err
	}
	if p.Count <= 0 {
		p.Count = len(p.Images)
	}
	if p.Count <= 0 {
		p.Count = 4
	}

	pictures := make([][]byte, 0, p.Count)
	for i := range p.Count {
		if i < len(p.Images) {
			data, err := os.ReadFile(p.Images[i])
			if err != nil {
				return nil, fmt.Errorf("read %s: %w", p.Images[i], err)
			}
			pictures = append(pictures, data)
			continue
		}
		data, err := generateTestPicture(i, p.Count)
		if err != nil {
			return nil, err
		}
		pictures = append(pictures, data)
	}

	messages := make([]*waE2E.Message, 0, len(pictures)+1)
	messages = append(messages, &waE2E.Message{AlbumMessage: &waE2E.AlbumMessage{
		ExpectedImageCount: ptrTo(uint32(len(pictures) + p.Short)),
	}})
	for i, data := range pictures {
		caption := ""
		if i < len(p.Captions) {
			caption = p.Captions[i]
		}
		image, err := c.buildRawImage(ctx, data, caption, req.Local)
		if err != nil {
			return nil, err
		}
		messages = append(messages, image)
	}
	return messages, nil
}

// buildRawImage wraps picture bytes as an ImageMessage. A local injection
// cannot upload, so it carries the picture as its inline thumbnail and nothing
// to download, which is enough to look at a layout offline; a real send uploads
// and produces a genuine image the other handset can open.
func (c *Client) buildRawImage(ctx context.Context, data []byte, caption string, local bool) (*waE2E.Message, error) {
	config, _, err := image.DecodeConfig(bytes.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("decode picture: %w", err)
	}
	picture := &waE2E.ImageMessage{
		Caption:       ptrTo(caption),
		Mimetype:      ptrTo(http.DetectContentType(data)),
		Width:         ptrTo(uint32(config.Width)),
		Height:        ptrTo(uint32(config.Height)),
		JPEGThumbnail: outgoingImageThumbnail(data),
	}
	if local {
		return &waE2E.Message{ImageMessage: picture}, nil
	}

	client := c.currentClient()
	if client == nil {
		return nil, fmt.Errorf("not connected")
	}
	resp, err := client.Upload(ctx, data, whatsmeow.MediaImage)
	if err != nil {
		return nil, fmt.Errorf("upload picture: %w", err)
	}
	picture.URL = &resp.URL
	picture.DirectPath = &resp.DirectPath
	picture.MediaKey = resp.MediaKey
	picture.FileEncSHA256 = resp.FileEncSHA256
	picture.FileSHA256 = resp.FileSHA256
	picture.FileLength = &resp.FileLength
	return &waE2E.Message{ImageMessage: picture}, nil
}

// generateTestPicture draws tile n of a set: a flat block of colour with a
// circle centred in it, in a shape that differs from its neighbours.
//
// Flat and geometric on purpose. The first version shaded each picture from top
// to bottom, and in a mosaic that read as a vignette the app was drawing on
// every tile, which is exactly the kind of thing a test picture must never
// invent. A circle answers the same question honestly: it is only round when
// the tile's aspect ratio survived, and an oval says the crop is wrong.
func generateTestPicture(n, total int) ([]byte, error) {
	shapes := [][2]int{{1200, 900}, {900, 1200}, {1000, 1000}, {1400, 700}}
	shape := shapes[n%len(shapes)]
	width, height := shape[0], shape[1]
	canvas := image.NewRGBA(image.Rect(0, 0, width, height))

	// A hue per tile, spread over the circle so no two adjacent tiles are close.
	hue := float64(n) / float64(max(total, 1))
	base := color.RGBA{
		R: uint8(127 + 127*math.Sin(2*math.Pi*hue)),
		G: uint8(127 + 127*math.Sin(2*math.Pi*(hue+1.0/3))),
		B: uint8(127 + 127*math.Sin(2*math.Pi*(hue+2.0/3))),
		A: 255,
	}
	draw.Draw(canvas, canvas.Bounds(), &image.Uniform{base}, image.Point{}, draw.Src)

	centerX, centerY := float64(width)/2, float64(height)/2
	radius := math.Min(centerX, centerY) * 0.6
	ring := color.RGBA{R: 20, G: 20, B: 24, A: 255}
	for y := range height {
		for x := range width {
			dx, dy := float64(x)-centerX, float64(y)-centerY
			distance := math.Hypot(dx, dy)
			// A ring rather than a disc, so the colour stays legible through it.
			if distance > radius*0.86 && distance < radius {
				canvas.Set(x, y, ring)
			}
		}
	}
	// A bar under the ring whose length counts the tile: enough to tell tile 3
	// from tile 4 without rendering text.
	barWidth := int(radius * 0.28 * float64(n+1))
	bar := image.Rect(width/2-barWidth/2, int(centerY+radius*1.25),
		width/2+barWidth/2, int(centerY+radius*1.25)+int(radius*0.12))
	draw.Draw(canvas, bar, &image.Uniform{ring}, image.Point{}, draw.Src)

	var out bytes.Buffer
	if err := jpeg.Encode(&out, canvas, &jpeg.Options{Quality: 85}); err != nil {
		return nil, fmt.Errorf("encode picture: %w", err)
	}
	return out.Bytes(), nil
}

func decodeRawParams(params json.RawMessage, out any) error {
	if len(params) == 0 {
		return nil
	}
	if err := json.Unmarshal(params, out); err != nil {
		return fmt.Errorf("malformed params: %w", err)
	}
	return nil
}
