package wa

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"go.mau.fi/whatsmeow"
	"go.mau.fi/whatsmeow/proto/waE2E"
	"go.mau.fi/whatsmeow/types"
	"go.mau.fi/whatsmeow/types/events"

	"whatevrd/internal/app"
)

// Development-only message injection, reachable through the daemon's
// `dev.send_raw` command and only when WHATEVR_DEV_COMMANDS=1. It is not part of
// PROTOCOL.md and never registered otherwise.
//
// Section 1 of feature-gap.md is about *receiving*, and the only way to exercise
// the receive path is for something to send. Waiting on a second handset for
// every kind, every time an ingest changes, is not a development loop. This
// builds the waE2E proto WhatsApp would have delivered and pushes it through the
// real handler, so decode, storage, wire encoding and rendering are all the
// production code.

// RawSendRequest is one injected message.
type RawSendRequest struct {
	ChatID string          `json:"chat_id"`
	Kind   string          `json:"kind"`
	Params json.RawMessage `json:"params"`
	// Local injects the message as if it had arrived from the peer, without
	// touching the network. This is the mode that actually tests the receive
	// path, and it costs the peer nothing.
	Local bool `json:"local"`
	// Incoming decides the direction a real send is ingested under. It has no
	// effect in Local mode, where the message is always incoming.
	Incoming bool `json:"incoming"`
}

// rawMessageBuilder turns the command's free-form params into the proto
// WhatsApp would carry. Each phase that teaches the ingest a new kind registers
// its builder here in the same commit, so there is never a kind the ingest
// understands and the test driver cannot produce.
// The client is handed in because some kinds cannot be built without it: a
// poll's message secret, which its votes are encrypted against, is generated by
// whatsmeow and belongs to the sending client.
type rawMessageBuilder func(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error)

var rawMessageBuilders = map[string]rawMessageBuilder{
	"text":          buildRawText,
	"location":      buildRawLocation,
	"live_location": buildRawLiveLocation,
	"live_update":   buildRawLiveLocationUpdate,
	"contact":       buildRawContact,
	"contacts":      buildRawContacts,
	"poll":          buildRawPoll,
	"group_invite":  buildRawGroupInvite,
}

// RawSendKinds lists what the driver can produce, for the tool's help output.
func RawSendKinds() []string {
	kinds := make([]string, 0, len(rawMessageBuilders))
	for kind := range rawMessageBuilders {
		kinds = append(kinds, kind)
	}
	return kinds
}

// SendRawMessage builds one message of the named kind and either injects it
// locally or really sends it. It returns the internal message id of the row
// that resulted, so a caller can watch for that exact upsert.
func (c *Client) SendRawMessage(ctx context.Context, req RawSendRequest) (string, error) {
	build, ok := rawMessageBuilders[req.Kind]
	if !ok {
		return "", app.NewCommandError(app.CommandErrorInvalidArgument, "no raw builder for kind %q", req.Kind)
	}

	client := c.currentClient()
	if client == nil || !client.IsLoggedIn() {
		return "", app.NewCommandError(app.CommandErrorNotLoggedIn, "not logged in")
	}
	message, err := build(ctx, client, req.Params)
	if err != nil {
		return "", app.NewCommandError(app.CommandErrorInvalidArgument, "build %s: %v", req.Kind, err)
	}
	chatJID, err := types.ParseJID(req.ChatID)
	if err != nil {
		return "", app.NewCommandError(app.CommandErrorInvalidArgument, "invalid chat_id: %v", err)
	}
	chatJID = c.normalizeJIDForChat(ctx, chatJID)

	messageID := client.GenerateMessageID()
	sentAt := time.Now()
	fromMe := !req.Local && !req.Incoming

	if !req.Local {
		resp, err := client.SendMessage(ctx, chatJID, message, whatsmeow.SendRequestExtra{ID: messageID})
		if err != nil {
			return "", app.NewCommandError(app.CommandErrorRejected, "send %s: %v", req.Kind, err)
		}
		if !resp.Timestamp.IsZero() {
			sentAt = resp.Timestamp
		}
	}

	evt := &events.Message{
		Info: types.MessageInfo{
			MessageSource: types.MessageSource{
				Chat:     chatJID,
				Sender:   c.rawSendSender(chatJID, fromMe),
				IsFromMe: fromMe,
				IsGroup:  chatJID.Server == types.GroupServer,
			},
			ID:        messageID,
			Timestamp: sentAt,
			PushName:  "Raw send",
		},
		Message: message,
	}

	// A real inbound message has its message secret stored by whatsmeow before
	// our handler ever sees it, and a real outbound one has it stored by the
	// send path. A locally injected message goes through neither, so without
	// this a poll injected with -local could never have a vote encrypted
	// against it and the whole two-way path would be untestable offline.
	c.storeBackfilledMessageSecret(ctx, evt)

	c.handleMessage(ctx, evt, false)
	return internalMessageIDForChat(chatJID.String(), messageID), nil
}

// rawSendSender picks a plausible sender for the injected event: ourselves for
// an outgoing copy, otherwise the peer in a direct chat or the chat itself in a
// group, which is what a real participant JID would resolve through anyway.
func (c *Client) rawSendSender(chatJID types.JID, fromMe bool) types.JID {
	if fromMe {
		if client := c.currentClient(); client != nil {
			if own := client.Store.GetJID(); !own.IsEmpty() {
				return own.ToNonAD()
			}
		}
	}
	return chatJID
}

func buildRawText(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		Text string `json:"text"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	if p.Text == "" {
		p.Text = "raw send"
	}
	return &waE2E.Message{Conversation: &p.Text}, nil
}

// rawLocationParams covers all three location shapes; a builder ignores the
// fields its shape has no room for.
type rawLocationParams struct {
	Lat      float64 `json:"lat"`
	Lng      float64 `json:"lng"`
	Name     string  `json:"name"`
	Address  string  `json:"address"`
	URL      string  `json:"url"`
	Comment  string  `json:"comment"`
	Accuracy uint32  `json:"accuracy_m"`
	Speed    float32 `json:"speed_mps"`
	Heading  uint32  `json:"heading_deg"`
	Sequence int64   `json:"seq"`
}

// defaulted fills in a recognisable place when the caller gave no coordinates,
// so `wa-testsend -chat ... location` with no params still does something.
func (p rawLocationParams) defaulted() rawLocationParams {
	if p.Lat == 0 && p.Lng == 0 {
		p.Lat, p.Lng = 12.9716, 77.5946
		if p.Name == "" {
			p.Name = "Bengaluru"
		}
	}
	return p
}

func buildRawLocation(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error) {
	var p rawLocationParams
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	p = p.defaulted()
	return &waE2E.Message{LocationMessage: &waE2E.LocationMessage{
		DegreesLatitude:  &p.Lat,
		DegreesLongitude: &p.Lng,
		Name:             &p.Name,
		Address:          &p.Address,
		URL:              &p.URL,
		Comment:          &p.Comment,
		AccuracyInMeters: &p.Accuracy,
	}}, nil
}

func buildRawLiveLocation(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error) {
	message, err := buildRawLocation(ctx, client, params)
	if err != nil {
		return nil, err
	}
	live := true
	message.LocationMessage.IsLive = &live
	return message, nil
}

// buildRawLiveLocationUpdate is a position update for a share already open,
// which is the only way to exercise the correlation whatsmeow gives us nothing
// for.
func buildRawLiveLocationUpdate(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error) {
	var p rawLocationParams
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	p = p.defaulted()
	return &waE2E.Message{LiveLocationMessage: &waE2E.LiveLocationMessage{
		DegreesLatitude:                   &p.Lat,
		DegreesLongitude:                  &p.Lng,
		AccuracyInMeters:                  &p.Accuracy,
		SpeedInMps:                        &p.Speed,
		DegreesClockwiseFromMagneticNorth: &p.Heading,
		SequenceNumber:                    &p.Sequence,
	}}, nil
}

// rawContactParams builds a vCard the way WhatsApp does, `waid=` and all, so
// the parser is exercised on the shape it will really meet.
type rawContactParams struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
	// WaID marks the number as being on WhatsApp, which is what makes the
	// card's Message action live.
	WaID  string `json:"waid"`
	Email string `json:"email"`
	Org   string `json:"org"`
	Title string `json:"title"`
	// Count repeats the card, for testing the multi-card array shape.
	Count int `json:"count"`
}

func (p rawContactParams) vcard(index int) string {
	name := p.Name
	if name == "" {
		name = "Test Contact"
	}
	if index > 0 {
		name = fmt.Sprintf("%s %d", name, index+1)
	}
	phone := p.Phone
	if phone == "" {
		phone = "+91 70600 29183"
	}
	waid := p.WaID
	if waid == "" {
		waid = strings.NewReplacer("+", "", " ", "", "-", "").Replace(phone)
	}

	var b strings.Builder
	b.WriteString("BEGIN:VCARD\nVERSION:3.0\n")
	fmt.Fprintf(&b, "N:;%s;;;\nFN:%s\n", name, name)
	if p.Org != "" {
		fmt.Fprintf(&b, "ORG:%s;\n", p.Org)
	}
	if p.Title != "" {
		fmt.Fprintf(&b, "TITLE:%s\n", p.Title)
	}
	fmt.Fprintf(&b, "item1.TEL;waid=%s:%s\nitem1.X-ABLabel:Mobile\n", waid, phone)
	if p.Email != "" {
		fmt.Fprintf(&b, "item2.EMAIL;type=INTERNET:%s\nitem2.X-ABLabel:Work\n", p.Email)
	}
	b.WriteString("END:VCARD")
	return b.String()
}

func buildRawContact(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error) {
	var p rawContactParams
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	name := p.Name
	if name == "" {
		name = "Test Contact"
	}
	vcard := p.vcard(0)
	return &waE2E.Message{ContactMessage: &waE2E.ContactMessage{
		DisplayName: &name,
		Vcard:       &vcard,
	}}, nil
}

func buildRawContacts(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error) {
	var p rawContactParams
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	count := p.Count
	if count <= 0 {
		count = 3
	}
	contacts := make([]*waE2E.ContactMessage, 0, count)
	for i := range count {
		name := p.Name
		if name == "" {
			name = "Test Contact"
		}
		name = fmt.Sprintf("%s %d", name, i+1)
		vcard := p.vcard(i)
		contacts = append(contacts, &waE2E.ContactMessage{DisplayName: &name, Vcard: &vcard})
	}
	label := "Shared contacts"
	return &waE2E.Message{ContactsArrayMessage: &waE2E.ContactsArrayMessage{
		DisplayName: &label,
		Contacts:    contacts,
	}}, nil
}

func buildRawPoll(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		Question string   `json:"question"`
		Options  []string `json:"options"`
		// Selectable is how many answers a voter may pick; 1 is the usual poll.
		Selectable int  `json:"selectable"`
		AllowAdd   bool `json:"allow_add"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	if p.Question == "" {
		p.Question = "dinner?"
	}
	if len(p.Options) == 0 {
		p.Options = []string{"Thai", "Pizza", "Sushi"}
	}
	if p.Selectable <= 0 {
		p.Selectable = 1
	}

	// BuildPollCreation generates the message secret the votes are encrypted
	// against and leaves the option hashes empty, exactly as a real client
	// does, so the ingest is exercised on the real shape.
	message := client.BuildPollCreation(p.Question, p.Options, p.Selectable)
	if poll := pollCreationFromMessage(message); poll != nil {
		poll.AllowAddOption = &p.AllowAdd
	}
	return message, nil
}

// buildRawGroupInvite offers a group.
//
// With no code given it asks WhatsApp for the group's real invite link, which
// is what makes the resolution path testable at all: an invite whose code is
// made up can only ever exercise the failure branch. Pass one explicitly (any
// string will do) to get that branch back, which is the state a revoked invite
// lands in.
func buildRawGroupInvite(ctx context.Context, client *whatsmeow.Client, params json.RawMessage) (*waE2E.Message, error) {
	var p struct {
		GroupJID string `json:"group_jid"`
		Code     string `json:"code"`
		Name     string `json:"name"`
		Caption  string `json:"caption"`
		// ExpiresIn is seconds from now; negative injects an invite that has
		// already lapsed.
		ExpiresIn int64 `json:"expires_in"`
	}
	if err := decodeRawParams(params, &p); err != nil {
		return nil, err
	}
	if p.GroupJID == "" {
		return nil, fmt.Errorf("group_jid is required")
	}
	groupJID, err := types.ParseJID(p.GroupJID)
	if err != nil {
		return nil, fmt.Errorf("invalid group_jid: %w", err)
	}
	if p.Code == "" {
		link, err := client.GetGroupInviteLink(ctx, groupJID, false)
		if err != nil {
			return nil, fmt.Errorf("fetch invite link for %s: %w", groupJID, err)
		}
		// The link is https://chat.whatsapp.com/<code>; the message carries the
		// code alone.
		p.Code = link[strings.LastIndex(link, "/")+1:]
	}
	if p.Name == "" {
		p.Name = "Test group"
	}
	if p.ExpiresIn == 0 {
		p.ExpiresIn = int64(3 * 24 * time.Hour / time.Second)
	}
	expiration := time.Now().Add(time.Duration(p.ExpiresIn) * time.Second).Unix()
	return &waE2E.Message{GroupInviteMessage: &waE2E.GroupInviteMessage{
		GroupJID:         &p.GroupJID,
		InviteCode:       &p.Code,
		InviteExpiration: &expiration,
		GroupName:        &p.Name,
		Caption:          &p.Caption,
	}}, nil
}

func decodeRawParams(params json.RawMessage, out any) error {
	if len(params) == 0 {
		return nil
	}
	if err := json.Unmarshal(params, out); err != nil {
		return fmt.Errorf("malformed params: %w", err)
	}
	return nil
}
